### ISSUE TITLE
Game stuck at 'USSR triggers Special Relationship'

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite-rust#1002]
This might be hard to replicate but it's a game-ending bug. 

1. USSR, under Red Scare, plays Special Relationship for ops after the event. UK is uncontrolled so nothing should happen.
2. Both players' HUD shows "USSR triggers Special Relationship", game gets stuck there and cannot be advanced.

Screenshot shows the sequence of what happened. I'm also uploading the console log from my side (USSR)
![image](https://user-images.githubusercontent.com/54612963/186451326-5f4cf3c0-c22f-4b1d-a477-3ca16b373264.png)
[Special Relationship bug - USSR Console.log](https://github.com/SaitoTech/saito-lite-rust/files/9417140/Special.Relationship.bug.-.USSR.Console.log)

**Comment by karlsaito** [comment]
How many times did it occur? @Tuch-o

**Comment by Tuch-o** [comment]
Happened once to me, then @trevelyan managed to replicate it and confirm it immediately.

**Comment by trevelyan** [comment]
This is already fixed, thx everyone

**Comment by Tuch-o** [comment]
Confirmed fixed.
