### ISSUE TITLE
Blackjack: can´t place my bet

### ISSUE THREAD

**Issue by telechris8** [SaitoTech/saito-lite-rust#1003]
step 1: create the game
step 2: Play until you have 5 tokens left
step 3: Game won't let you place your bet
![blackjack a](https://user-images.githubusercontent.com/63267624/186535474-df7f0629-92c7-4fd8-9037-3b9c70879cbd.jpg)

**Comment by karlsaito** [comment]
@telechris8  please check this, and close if it's already fixed

**Comment by telechris8** [comment]
fixed
