### ISSUE TITLE
Twilight Struggle: Loading a "saved game" doesnt work and breaks the game

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1010]
**Problem:** Saving a game and trying to load it only works for Player 1. Player 2 cant seem to load the game successfully using the Game Saved Link provided
`
`
**Steps:** 
1) Open a TS game and get a player 2 to join
2) Play some moves and click on "save game"
3) Exit from current game or close tab and then open a new tab
4) Load the "Saved Game" Link provided
5) Both screens from Player 1 and 2 will display an "error 404"
6) In a few seconds, Player 1 "error 404" screen will have a pop up message for saved game recovery
7) Player 1 can successfully load the game back from where it was saved
8) Player 2 gets stuck on "error 404" and no way to recover the game

**Expected outcome:**
1) "Error 404" should not appear on both players
2) Load game message pop up should appear on both players
3) Both players should successfully load the saved game
`
`

Fig.1: Link provided after clicking on "save game"
![save 1](https://user-images.githubusercontent.com/107991527/186811987-ce49fb67-0e01-4d5f-aea7-5ee8107755b8.png)

fig.2: Error 404 after copy pasting the "save game" link (PLAYER 2 is stuck on this screen)
![save2](https://user-images.githubusercontent.com/107991527/186812099-6fd35540-7139-4f62-9fea-5ced868f2390.png)

fig.3: Player 1 screen after a few seconds
![save p1 pov11](https://user-images.githubusercontent.com/107991527/186812159-53ab736d-ab8a-4be8-ab86-7c378745825a.png)

fig.4: Player 1 successfully reloading game (Player 2 permanently stuck on "Error 404" screen)
![save p1 pov1](https://user-images.githubusercontent.com/107991527/186812300-83d109ef-69ae-4309-b8e5-33162e1981cc.png)
`
`
**Additional Minor Issues:**
1) Typo on the "save game" link - double colon after http
![typo1](https://user-images.githubusercontent.com/107991527/186812432-bd16bdd3-8e8a-4396-9ffb-392fb36f2492.png)

2) Typo on the word "ARE"
![typo 2](https://user-images.githubusercontent.com/107991527/186812548-4aa7f83a-8d54-49c2-87e1-ce6d6df19c9e.png)

**Comment by trevelyan** [comment]
thx for reporting this

**Comment by afkafk088** [comment]
**Additional Findings:**
Upon further testing, I have found out that the "Saved Game loading" issue only affects specific browsers. 
1) Test 1: **Brave Browser (P1) vs Firefox (P2)** = Only P2 managed to load the game
2) Test 2: **Brave Browser (P1) vs Brave Browser (P2)** = Both could NOT load the game (stuck at 404 screen)
3) Test 3: **Chrome (P1) vs Chrome (P2)** = Both could NOT load the game (stuck at 404 screen)
4) Test 4: **Firefox (P1) vs Firefox (P2)** = Both managed to load the game (with slight issue - will post on next thread)

**Result:** 
• Loading a saved game only works on **Firefox** (based on my tests)

**Comment by afkafk088** [comment]
**Additional Findings:** 
Upon further testing, I have found out that the "Saved Game Loading" issue affects games differently. Please see data below

**Browser:** Firefox (P1) vs Firefox (P2)
**Game:** Wordblocks

**Steps:**
1) Make WB game on firefox, accept the game using another firefox incog
2) Make some moves, save the game
3) Copy and paste the "Saved Game" link to both firefox browsers
4) Both browser will Load the game successfully
5) However, both browser gets stuck on "Acknowledged.." - NOTE that the game is NOT broken
6) The turning player (who is currently stuck on "Acknowledged") may click on "CANCEL" or try to put random letters Horizontally/Vertically to make your "Tile letters" appear

Fig.1: Please note that I am Alt+tabbing browsers for the test
https://user-images.githubusercontent.com/107991527/187591006-80830daf-35a6-4ecb-8cb6-4424becfa9de.mp4

**Comment by afkafk088** [comment]
**Additional Findings:**

**Browser:** Firefox (P1) vs Firefox (P2)
**Game:** Twilight Struggle

**Result:** 
1) "Saved Game" seem to load successfully on both Firefox browsers
• Only thing to note is there was one instance wherein the other firefox browser got stuck on "Rebroadcasting.."
