### ISSUE TITLE
Twilight Struggle Cards Didn't Load Properly

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#1013]
I encountered this error once and wasn't able to determine the cause.
I was not able to replicate the problem since my next TS game didn't have the issue.

![TS Error Cards](https://user-images.githubusercontent.com/101871246/186914897-9e34cc56-12bf-4872-b14c-1f779ed9bdd9.png)

**Comment by trevelyan** [comment]
The issue is being caused by one of the players having 2 tabs open.

This can be in a single browser, or in a separate workspace (i.e. you full-screen one tab and then come back)

There's no solution other than restricting oneself to one tab.
