### ISSUE TITLE
Red Square: Duplicating Tweets on Red Square lobby

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1014]
Same tweets are randomly duplicating 

https://user-images.githubusercontent.com/107991527/187010487-4be6cc24-74bc-4636-beba-30d70515f80c.mp4

**Comment by Darkuso** [comment]
I noticed this too after replying to tweets, but the duplicate is gone after refreshing. Also, at this moment, the Top Gun image has 3 copies in the red square

**Comment by estapeluo** [comment]
It seems it got fixed at some point.
