### ISSUE TITLE
Stuck Init and games (possible desync)

### ISSUE THREAD

**Issue by Darkuso** [SaitoTech/saito-lite-rust#1017]
During my shift today I and other users in the arcade encountered this issue, at 22 pm UTC and 2 am UTC, both time it lasted for about 30 to 40min.  So far I have tried over 15 wallets in 3 different browsers + incog and nuking my wallets. Other users (organics) are reporting the same, a few games can pass through, but is like they are not syncing correctly, there are no errors showing in the console either, just the plays of the game aren't showing for the other player or the game are just getting stuck. 

The games I could test at that moment, due to the problem with the very long inits (most never-ending) were TS, poker, and Settlers.
In all the games, the plays will not show to the opponent, resulting in the games being stuck, I added two screenshots of the chat of two organics trying to play TS, but it was not possible for me to pass the headline pick.

In settlers, the game was not detecting the placement of the village or roads, refreshing made it detect this but after the first roll of dice, all games ended since it wouldn't show the option to pass (so the other player could roll too), same with poker, after the first bet or fold neither or the players were able to make any other play. 

![image](https://user-images.githubusercontent.com/9855617/187098813-33c6e9aa-50bf-4807-86fd-163138764197.png)

![image](https://user-images.githubusercontent.com/9855617/187098828-9fff7ec4-bab6-44c2-9f9f-e4cf93277b5f.png)

**Comment by estapeluo** [comment]
Will keep issue open for the next 48hr, if it happens again comment it.

**Comment by estapeluo** [comment]
is this still happening? @Darkuso @afkafk088

**Comment by Darkuso** [comment]
We haven't encountered this problem so far. Closing this ticket for now
