### ISSUE TITLE
Red Square: Multiplying empty tweets after posting image with captions

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1027]
**Problem:**
• The poster/retweeter of an "image with a text caption" will see multiple empty tweets on the Red Square lobby (Only the poster/retweeter will see it, others wont) 

**Steps:** I managed to recreate the issue ONLY twice (Cant seem to recreate it after that)
• Tweet an Image with a text caption on it
• Wait for around 30+ minutes (i played in the arcade at the given time)
• Return to Red square after XX number of minutes
• See multiple empty tweets (only the poster/retweeter can see it)

Fig.1: 
https://user-images.githubusercontent.com/107991527/187355058-50256e70-705d-43e0-bab7-ab7bc7b65b6f.mp4

**Comment by estapeluo** [comment]
I see you have 2 tabs open on the same browser (same process) - this might be the problem.

**Comment by Darkuso** [comment]
I had the same issue  last night after rt an image with Kris, it was only visible with the wallet that made the RT
![unknown-28](https://user-images.githubusercontent.com/9855617/187554894-f0aeb610-5944-41ab-8d2c-1eec1b66f08c.png)

**Comment by estapeluo** [comment]
This look it got fixed on the last couple of updates.
