### ISSUE TITLE
TS: Scoring while Shutter Diplomacy is under effect shows "USSR loses one battleground from undefined"

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite-rust#1033]
Steps:
1. Play until Mid War, then trigger Shuttle Diplomacy
2. Score Asia or Middle East, it's gonna misprint "USSR loses one battleground from undefined". It should print "USSR loses one battleground from Shuttle Diplomacy".

![image](https://user-images.githubusercontent.com/54612963/187563993-f08ce6f5-1a26-4692-a6a6-7456c8aa6e66.png)

**Comment by f8daniel** [comment]
omg, this was annoying.
So the game tends to move cards into a discards object, but to prevent Shuttle Diplomacy from getting reshuffled back in with the other discards when it was supposed to be held off to the side somewhere on the table, the source code deleted it with extreme prejudice.
I've changed it to gentle remove it from discards prior to reshuffling, but will need to clean up the discard/shuffling code sometime in the future.

**Comment by Tuch-o** [comment]
Fixed, will close.
![image](https://user-images.githubusercontent.com/54612963/190265063-56f5d835-6107-4fd8-8aca-80189d0a8aec.png)
