### ISSUE TITLE
Settlers - Infinite Build 

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#1039]
When playing Settlers, if you select the option to spend resources on a road and select the place for it, bringing up the "place road here" confirmation box, but then you back out of building a road, the confirmation box is still open and if you select "Yes", you place a road without spending resources. Also affects building Villages and Cities

Videos included

Road:

[Road.zip](https://github.com/SaitoTech/saito-lite-rust/files/9464114/Road.zip)

Villages:

https://user-images.githubusercontent.com/61713323/187762084-95039301-eca9-4365-b925-d6b2a1643052.mp4

**Comment by f8daniel** [comment]
I blame the person who insisted on including the popup confirmation. Lol.
Fix should be live on next update.
