### ISSUE TITLE
Red Square: Tweet does not appear after tweeting, creating another tweet after that is broken

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1068]
Steps: 
1) Create a tweet and post 
2) Tweet will not appear (unless you refresh)
3) When trying to create another tweet, the "create tweet" pop up box is broken

https://user-images.githubusercontent.com/107991527/188558297-9443c8a3-32b6-4867-ac87-bdc8bde29e7e.mp4

**Comment by estapeluo** [comment]
Code Version:

4.325

**Comment by afkafk088** [comment]
issue fixed
