### ISSUE TITLE
Chess: Missing css

### ISSUE THREAD

**Issue by estapeluo** [SaitoTech/saito-lite-rust#1069]
- [ ] Missing css

![image](https://user-images.githubusercontent.com/59634305/188559704-a298570b-9d9b-4a9a-b7e1-37a5c142c8ab.png)

**Comment by estapeluo** [comment]
Code Version:

4.325

**Comment by f8daniel** [comment]
CSS is intact, but no guarantees that chat still isn't causing havoc
