### ISSUE TITLE
Settlers: Game broken on start. 

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1078]
A few seconds after clicking game start, enlarged username icons and chat cover up the whole screen. Tested on different browsers.

https://user-images.githubusercontent.com/107991527/188764708-6eef02f5-ef81-44a1-b5d4-c77e7573f034.mp4

**Comment by afkafk088** [comment]
Further findings:
1) Refreshing fixes the problem.

Additional problem:
1) After refreshing, go to "CHAT" and then "COMMUNITY". The chatbox that appears is the one from Red Square, not the Arcade chatbox

https://user-images.githubusercontent.com/107991527/188765383-26461ffe-efe7-44e9-abdf-545945d5c182.mp4

**Comment by estapeluo** [comment]
Refreshing only "fix" it temporally, but after receiving a new msg on private chat its goes back

**Comment by estapeluo** [comment]
![image](https://user-images.githubusercontent.com/59634305/188815572-c1dbf710-e4a1-4a4b-aa65-308a97485626.png)

**Comment by afkafk088** [comment]
Settlers seem to be working fine already
