### ISSUE TITLE
TS: US isn't able to coup with CIA Created's event

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite-rust#1079]
Test Steps:
1. Play until CIA Created shows up in USSR's hand.
2. Drop DEFCON to 2.
3. As USSR, play CIA Created for the event after OPS. (might also work before OPS)
4. As US, try to coup a country. After clicking, the HUD goes back to "US Plays 1 OPS" and nothing happens. Correct behavior is dropping DEFCON to 1 and awarding the US the win.

![CIA won't let me coup](https://user-images.githubusercontent.com/54612963/188767705-892db0ad-56b9-4f8b-bb63-05a1216f63be.gif)

**Comment by f8daniel** [comment]
There is supposed to be a confirmation box at the top of the screen asking if you were sure you wanted to coup a BG at Defcon 2, but apparently that has been nuked by the css swapover.

**Comment by karlsaito** [comment]
@Tuch-o , can you check if this is still occurring on the latest prod?

**Comment by Tuch-o** [comment]
Fixed, will close.
