### ISSUE TITLE
Wordblocks: Can't place any word

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1080]
Both Horizontal and Vertical button are not working. Only the Cancel button is working

https://user-images.githubusercontent.com/107991527/188769764-3fe01b8c-1b55-437f-b06d-6d532bc13062.mp4

**Comment by afkafk088** [comment]
additional testing:
Just found out I can place a word by clicking individual letters to the board after the recent update. Game is technically not broken, but vertical and horizontal button functionality is more convenient to use

**Comment by f8daniel** [comment]
should be fine now

**Comment by afkafk088** [comment]
Tested it Daniel. It's working now. Thanks!
