### ISSUE TITLE
Settlers - Pop-up not appearing clearly when placing a village

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#1087]
Creating this issue for documentation. It seems the problem no longer persists.

During the initial placement of villages, whenever I click on a spot to try to build a village, the pop-up appears but it is barely visible.

<img width="960" alt="unable to place village" src="https://user-images.githubusercontent.com/101871246/188864734-45b5a21b-2839-4dba-a7cf-38c389179588.png">
<img width="958" alt="pop up not visible" src="https://user-images.githubusercontent.com/101871246/188864752-45f5b242-03f9-4762-84b2-6c11144b6bee.png">

**Comment by f8daniel** [comment]
This should be fixed now

**Comment by noslrac27** [comment]
Looks good. Didn't encounter the problem anymore.
