### ISSUE TITLE
TS - Confirmations, Results, and Warning messages gone (unable to defcon suicide, by own hand or by opponent)

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#1090]
Latest update removed any and all confirmation messages, messages about coup results, space race results and warnings.

When you coup a country, you don't get a confirmation, regardless if newbie mode or expert mode, it just happens immediately and does not report the result, it just resolves it. Additionally it does not allow you to suicide, either by couping a country in defcon 2 or holding a scoring card, which is good for a beginner but there's no message about it, when you try to coup it just returns you to the ops. This is a SERIOUS PROBLEM, because it does not allow defcon suicide, IE when the USSR plays CIA Created in defcon 2, the US cannot coup to end the game, or the same with Grain Sales, or Lone Gunman

https://user-images.githubusercontent.com/61713323/188947173-79c75ad1-a780-45bb-ac1c-0c13526c1c06.mp4

**Comment by trevelyan** [comment]
fixed
