### ISSUE TITLE
Arcade - Log size across games is miniature

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#1091]
As it says on the title, the font size for the log in every game is unacceptably small at 100% zoom.

Examples

![image](https://user-images.githubusercontent.com/61713323/188956521-fdcfe613-8266-4820-baa4-f88b3dd6bf94.png)
![image](https://user-images.githubusercontent.com/61713323/188956560-9c1f5b25-4d9a-429a-9d84-37bba80cb5c5.png)
![image](https://user-images.githubusercontent.com/61713323/188957121-5cbdbaa5-efa0-4861-883f-343561fd0713.png)
this also affect RI text and other games as well like poker.

**Comment by f8daniel** [comment]
I have fixed the font-size in logs
