### ISSUE TITLE
Mahjong - Can't exit game, also this is Mahjong Solitaire, not regular Mahjong, should change the name to avoid confusion

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#1124]
Clicking on the Exit button in the menu does not exit the game, it just shows saving and doesn't actually exit the game. Video included.

Also just to avoid confusion and in the event we ever add classic Mahjong to the arcade, this one should be renamed into Mahjong Solitaire. 

https://user-images.githubusercontent.com/61713323/189790752-355b1f3a-a0e8-4f1a-ba3b-a4d25a48beb1.mp4

**Comment by f8daniel** [comment]
I wanted to call it Taipei (as it was known in the 90s Microsoft Entertainment Pack)

**Comment by pawelpaszki** [comment]
this was fixed here: https://github.com/SaitoTech/saito-lite-rust/pull/1170
