### ISSUE TITLE
Mahjong: Refreshing creates a new game (with different tiles)

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1135]
Steps:
1) Create a Mahjong game
2) Play and then hit refresh mid-game
3) New complete set of tiles will appear (like a new game)

**Comment by pawelpaszki** [comment]
this was fixed here: https://github.com/SaitoTech/saito-lite-rust/pull/1170

**Comment by afkafk088** [comment]
hi @pawelpaszki , tested this one out. While refreshing does not change the mahjong tiles into new ones, it reverts all your previous moves and takes you back to the beginning. 

This is a very minor issue because there is a very low chance players would be hitting refresh in mahjong but just a precautionary measure for accidental refresh / misclicks :) Thanks Pawel

Fig.1:
https://user-images.githubusercontent.com/107991527/191877903-e0611aba-caa1-40cf-b348-3b3f57d6dd03.mp4

**Comment by pawelpaszki** [comment]
that's the case for all single player games I think. I could add a piece of code to save on each move, but not sure what would be the implications when playing on the mainnet (I presume there might be a cost incurred for each save to blockchain)

**Comment by afkafk088** [comment]
Will close this issue :) I think the probability of mahjong needing a refresh is close to 0 anyway. Thanks Pawel! :)
