### ISSUE TITLE
Creating Games with Chess, Wuziqi and Twilight Struggle Fails

### ISSUE THREAD

**Issue by Ramcas42** [SaitoTech/saito-lite-rust#115]
Trying to create either of these 3 games produces a type error prompt.

![image](https://user-images.githubusercontent.com/45575705/150273090-51099ca9-dd8a-4c7c-8fd6-cc910a06cb41.png)

Device used: Web Browser
OS; Windows 11
Browser: Chrome 97.0.4692.71

**Comment by trevelyan** [comment]
sorted.

**Comment by karlsaito** [comment]
@Ramcas42  please ask the tester to verify and move to close column if it's all good
