### ISSUE TITLE
Poker and Blackjack 6p as default 

### ISSUE THREAD

**Issue by Darkuso** [SaitoTech/saito-lite-rust#1163]
The invites of these games (poker and blackjack) are having as default the number of players as 6 instead of 2 

![image](https://user-images.githubusercontent.com/9855617/190942666-0eee5a3b-b1f6-4c20-a54e-3751125ad1c9.png)

**Comment by f8daniel** [comment]
That is an intentional feature, but if it is creating confusion we will remove the ability to set a maximum table size
