### ISSUE TITLE
Clean up tasks - 2022-09-21

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite-rust#1176]
A variety of things that should be brought up to standards.

- [x] Spacing between items in the sidebar and between headings and content are not uniform.
![image](https://user-images.githubusercontent.com/2867779/191426280-e8024154-e306-41e4-acb6-b448e2f68c60.png)

- [x] Games/Wins over lap in league table - there should be more space here.
![image](https://user-images.githubusercontent.com/2867779/191426365-586ea479-7812-4cc6-8704-199cfd939ea1.png)

- [x] Retweet ellipsis should not be cut off and horizontal line should stop in line with the edge of image and text left side...
![image](https://user-images.githubusercontent.com/2867779/191426539-b25f3936-7f03-4ee5-9686-59934c15a844.png)

- [x] Rows in the rankings table should have ```background-colour: var(--saito-gray);``` - as per Live Games.

- [x] Sidebars should not scroll up but stay fixed at all times unless they are taller than the page, in which case they should scroll with the page till the bottom is visible.

- [x] Right sidebar content renders 'high' after use makes a post - loses top padding or something.
![image](https://user-images.githubusercontent.com/2867779/191426872-7c5a6965-5773-4003-8612-ccc6f511e33e.png)

- [x] Live games items should have side padding. Right now content is touching sides.
![image](https://user-images.githubusercontent.com/2867779/191427370-02d1a97f-f1a2-4107-8f53-2aaf333e4379.png)
->
![image](https://user-images.githubusercontent.com/2867779/191428493-05ff767b-fd5a-4398-98b3-f72dcb30944a.png)

- [x] Edge of items and edge of content should line up between row items in tables.
![image](https://user-images.githubusercontent.com/2867779/191429084-bb01e526-e457-499a-8bf1-af52333a0f0f.png)
->
![image](https://user-images.githubusercontent.com/2867779/191428921-13b86017-f456-4dae-bac8-4b2779e1ebf5.png)

**Comment by umairkhannn** [comment]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/104337801/191441917-417b442f-aadd-4ff2-8881-053494525ce7.png">

Adding this one issue, flagged by Dan, too.
Appstore mod influences styles of game create overlay.

**Comment by umairkhannn** [comment]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/104337801/191442843-935e3758-1cb1-47df-a607-8734c7e5b28d.png">

Create game btn creeping into appstore install overlay

**Comment by umairkhannn** [comment]
Fixes merged in:

https://github.com/SaitoTech/saito-lite-rust/pull/1181

**Comment by afkafk088** [comment]
@umairkhannn kindly disregard my message above. It's been fixed already after the update. Thanks!

**Comment by umairkhannn** [comment]
@afkafk088 noted.
