### ISSUE TITLE
Blocks are not getting loaded from disk if accessing pruned blocks

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#119]
Exploratory Testing Bug

Severity: Critical
Test Step: scenario number
Test Plan: link
Module: Core/Server

**Comment by trevelyan** [comment]
I am working on this.

**Comment by trevelyan** [comment]
this should be fixed in browsers. unclear if there are issues with servers, but should file as separate report with more detailed instructions on replicating if so, as I cannot trigger this issue on servers.
