### ISSUE TITLE
Arcade: Could not cancel games created in lobby

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1197]
Steps:

1) Create a game
2) Click cancel button
3) nothing happens

**Comment by estapeluo** [comment]
This is still an issue... @f8daniel any incoming fix?

**Comment by f8daniel** [comment]
Just trying to create parity of functions between Arcade and RedSquare. No cancel button in Redsquare, so break the cancel button in Arcade :-P

**Comment by afkafk088** [comment]
seems to be fixed from the recent update. Closing this one
