### ISSUE TITLE
System is throwing TypeError: this.pruneOldData is not a function at Archive.<anonymous> error

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#120]
Exploratory Testing Bug

**Severity**: Critical
**Test Step**: scenario number
**Test Plan**: link
**Module**: Core/Server

**Comment by SankaD** [comment]
![image](https://user-images.githubusercontent.com/2997480/150461880-2ff7359d-a4ba-4f23-b1e0-149cad7b278e.png)

**Comment by SankaD** [comment]
added the correct method. and changed it to run periodically instead of randomly.
