### ISSUE TITLE
Mahjong Solitaire: Mahjong tile enhancement

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1208]
The recent update done to Mahjong Solitaire's looks a bit awkward
• Mahjong pieces perspective looks a bit off being diagonal and all
• I noticed that the color transitions from bright white to dull white as the mahjong layers go down. But the color seems a bit bleak especially on the lowest layer
![mahjong](https://user-images.githubusercontent.com/107991527/192440548-5a7e94a5-935d-407e-b74f-d35f255c574c.png)

I saw this Mahjong Solitaire on Arkanium, maybe we can get a good inspiration from this reference
![arkadium](https://user-images.githubusercontent.com/107991527/192440932-4af949ef-1573-4280-ba8c-4c5ef7b4a721.png)

**Comment by f8daniel** [comment]
Mahjong is a community project. If you think you can improve the graphics, you are welcome to make a pull request
