### ISSUE TITLE
Red Square: Red Square lobby on Brave browser not showing everything

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1221]
After the recent update, when going to red square, Only certain parts of tweets are appearing. The Create new tweet and text box could not be seen. 

So far, only Brave browser is affected

https://user-images.githubusercontent.com/107991527/192946276-040fe36c-53f5-47a4-a1ee-db7db108b280.mp4

**Comment by estapeluo** [comment]
I think it got fixed after... and unable to replicate
