### ISSUE TITLE
Chess: promote breaks the game 

### ISSUE THREAD

**Issue by telechris8** [SaitoTech/saito-lite-rust#1241]
**steps:**

1. open a chess as black
2. play until you have your king+pawn and white has king+queen(promoted)+pawn
3. promote your pawn to queen

It breaks the game, i can´t get my queen and can´t play anything

![chess bug promote](https://user-images.githubusercontent.com/63267624/194193506-4dd92c6e-7a4d-4b24-b461-0a7e16aecab7.jpg)

**Comment by f8daniel** [comment]
![image](https://user-images.githubusercontent.com/70703104/194483873-3bc17b1d-9eaa-4a1e-bc84-8d92e8465c77.png)

I ran a test game, both sides upgraded 3 pawns to queens no problem...
