### ISSUE TITLE
Quake 3: Option to adjust mouse sensitivity

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1267]
Game is awesome as I remembered but hope to add a mouse sensitivity adjustment. Can get a bit nauseous after few minutes of playing

**Comment by Darkuso** [comment]
You can edit it on the game options
![image](https://user-images.githubusercontent.com/9855617/194995671-73a2b186-b318-43bc-80f7-9d56e232a4f0.png)

**Comment by afkafk088** [comment]
oh sweet! didnt notice that one! Thanks @Darkuso . closing this one
