### ISSUE TITLE
All available/ongoing games appear on the game specific page

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#128]
Exploratory Testing Bug

**Module**: Arcade/2 Player Games
**Test Plan**: n/a
**Test Step**: 

1. Create Chess Game
2. Create Pandemic or Create any game aside from blackjack
3. Click Blackjack in the Arcade Game Section
4. Chess Game and Pandemic games will appear

**Comment by f8daniel** [comment]
Minimal solution is a filter in when filling in the arcade hero (of open games)
Maybe a good time to also reintroduce a tab system with My Games so players don't think Saito deleted their other ongoing games?

**Comment by trevelyan** [comment]
This is fixed.
