### ISSUE TITLE
app.browser.makeDockable

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#1286]
I would like an expansion of the makeDraggable function in browser.ts, which allows users to drag an element anywhere on screen.
However, if the top/right/bottom/left edge of the container ends within 10px of the screen's top/right/bottom/left edge, I would like the element to automatically dock along the edge. Ditto for dragging the element partially off screen.

**Comment by arpee** [comment]
What would 'docking' involve?



Richard Parris - Co-Founder

ph : +86 1860 1221 974

**Comment by f8daniel** [comment]
It just means the component repositions itself to sit flush against the edge of the window. So if you accidentally move something that is draggable, you can just push it partly off the screen so it snaps back into place.
It's not a hard task, just a little time consuming
