### ISSUE TITLE
Settlers - can't select to "do not ask again" while placing villages or roads

### ISSUE THREAD

**Issue by Darkuso** [SaitoTech/saito-lite-rust#1315]
The option is still there but it can be marked or selected, so in every placement, the question will pop up

![image](https://user-images.githubusercontent.com/9855617/197117377-0d47c9b3-e7bf-4194-b41e-1b4943fa94e9.png)

**Comment by f8daniel** [comment]
Fix should be coming with the next update. Someone added a script that preempts all default web actions, like clicking on links or form elements
