### ISSUE TITLE
Arcade Lobby: Some buttons are not working on the hamburger menu

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1316]
Cant access 4 buttons after update. Tested on different browsers

1) Arcade
2) League
3) Forums
4) Red Square

https://user-images.githubusercontent.com/107991527/197123240-2e6dfca1-b69e-4ab9-b180-aa869635a871.mp4

**Comment by f8daniel** [comment]
Fix coming with next deployment
