### ISSUE TITLE
Saito SLR Testnet is not working (Error 404)

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#133]
Exploratory Testing Bug

**Severity**: Critical
**Test Step**: 
1. Open https://rustest.saito.io/
2. throws this error
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/96273856/150476041-a0d3f515-4e5d-42f9-b7a8-f59280cbac1b.png">

**Test Plan**: n/a
**Module**:  Core/Server

**Comment by thaodt** [comment]
![photo_2022-01-21_14-13-38](https://user-images.githubusercontent.com/5485589/150483233-0c615f4b-dc61-4df4-b89e-ca199cd003b0.jpg)

Would like to add the screenshot which took server down.
