### ISSUE TITLE
Feature request: Re-add the setting for the amount of players in Poker games.

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#1340]
By having games always be 6player we are opening an avenue for trolls to sabotage games by joining and refusing to anything.
We are better off adding the ability to limit the amount of players in a game.

**Comment by f8daniel** [comment]
This previously existed but was removed because it was "too hard" to have extra explanatory text in the game creation wizard. I'll try to add a min-player / max-player selection, but can't guarantee it won't be removed later on.
