### ISSUE TITLE
XSS Scripting Vulnerabilities

### ISSUE THREAD

**Issue by trevelyan** [SaitoTech/saito-lite-rust#142]
Once the application suite is up, we should review and make sure our main applications don't have issues with XSS -- i.e. all inputs are sanitized before display from TX to screen in order to prevent script-inserts onto the page.

**Comment by SankaD** [comment]
Applications to be tested

- [ ] public chat
- [ ] personal chat
- [ ] email
- [ ] registering names
- [ ] posts
- [ ] comments
- [ ] uploading images
- [ ] app store

**Comment by SankaD** [comment]
Browsers to be tested

- [ ] Chrome
- [ ] Opera
- [ ] Firefox

**Comment by SankaD** [comment]
Created the following issues to track what's left from this ticket and tests which are required in the future

- https://github.com/SaitoTech/saito-lite-rust/issues/230
- https://github.com/SaitoTech/saito-lite-rust/issues/229
- https://github.com/SaitoTech/saito-lite-rust/issues/226
