### ISSUE TITLE
RedSquare: Inconsistent pop-up when retweeting. Suggestion to have a default size for the pop-up

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1481]
The size of the pop-up box is inconsistent. I think the size is depending on the image size. 

It would look better if there is a default size for the pop-up box when retweeting

https://user-images.githubusercontent.com/107991527/205031852-61a4f338-a2c1-4599-a231-cacfd310a991.mp4

**Comment by estapeluo** [comment]
Quote Retweet (ultra) long post shows a problem:
![Screenshot from 2022-12-01 17-45-20](https://user-images.githubusercontent.com/59634305/205165553-18fabfd4-cefd-443b-8053-aa41a3bd9ef8.png)

To keep consistency, we can add the same ccs property as the pop-up from Comment button:
![Screenshot from 2022-12-01 17-53-27](https://user-images.githubusercontent.com/59634305/205166871-f467eed0-afd0-4799-b45a-498b0d6b16e0.png)
