### ISSUE TITLE
Chatbox is not showing previous messages.

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#149]
Exploratory Testing Bug

**Test Step**:
1. User A Opens Arcade
2. User A Clicks Community Chat in Arcade Page
3. User A chat "abc"
4. User B Opens Arcade
5. User B Opens Chat, **previous messages are not shown**  (Error)

**Expected result -- based on current saito arcade in production**:
When test step 5 is executed,. previous messages should show

**Comment by trevelyan** [comment]
We are now:

1. loading the last 25 messages from community chat when loading the chatbox
2. opening the chatbox by default on the arcade page
