### ISSUE TITLE
Editing Post Shows Unnecessary HTML Codes

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#156]
**Test Steps**:

1. Open Arcade
2. Go to Saitolicious Forum
3. Create a Post
4. Edit a Post (shows the html codes)

**Screenshot**:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/96273856/151485296-c05c9989-edaf-4f38-8a56-c4125719ec10.png">

**Comment by trevelyan** [comment]
The solution here should probably be disabling post editing?

**Comment by trevelyan** [comment]
Post and Comment editing is now possible.

Have also corrected issues with the loading of comment posts after display, and taken steps to make the editing fields more consistent and user-friendly. Believe this offers a non-trivial improvement in usability. Can look at using our new cache mechanism to speed up forum-loading times in the future.
