### ISSUE TITLE
Arcade's Left Menu is Not Scrollable

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#1639]
Scrolling the page on desktop doesn't scroll the menu on the left. Because of this, I am unable to see the games below and also I am unable to open the Community Chat.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/101871246/223062660-1379b143-452b-4118-b760-46390c092fa3.png">

**Comment by f8daniel** [comment]
Meanwhile. If the left sidebar overflows but the central panel is short of content. You can scroll the central panel off into infinity.

**Comment by f8daniel** [comment]
This should be fixed
