### ISSUE TITLE
Appstore is stuck at the uploading of application

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#166]
**Steps**:
1. Open Settings
2. Click Appstore
3. Drag and Drop the application
4. Click Submit
5. Stuck at indexing of application (See Errors)

**Error**:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/96273856/152084708-85d46e2b-a4a5-4ece-84a2-998667a26e8e.png">

<img width="425" alt="errorAppstore" src="https://user-images.githubusercontent.com/96273856/152084741-f5f07d93-7b50-43e2-895f-d0805b5b2557.png">

**Comment by trevelyan** [comment]
I don't believe that this is true -- it does take a considerably long time, but we should not let this be an obstacle at this point, so I am closing.
