### ISSUE TITLE
prevent empty chat/post upload

### ISSUE THREAD

**Issue by pj8912** [SaitoTech/saito-lite-rust#1686]
prevent sending empty chat message and uploading posts, add CTRL+ENTER to upload post and send message

**Comment by arpee** [comment]
Not following here. The behaviour I see in the new post form is that ```enter``` and ```shift+enter``` both add  a new line to the post. 

In chat ```enter``` sends the message while ```shift+enter``` adds a line break.

I think this is pretty standard for messengers (some have send on enter togglable).

What behaviour are you wanting from ```ctrl+enter``` ?

**Comment by pj8912** [comment]
So `ctrl+enter` is widley adopted on pretty much all social media sites to upload post. `Enter+Shift` and `Enter` perform the same no problem.

### Empty chat and post
- In chat prevent sending empty messages
-  In Post prevent uploading empty posts

**Comment by arpee** [comment]
I feel like I am missing something.  I still don't know what you want ```ctrl+enter`` to do? 

You are saying:

 ```ctrl+enter``` - submit form or send chat.
```enter ``` - add line break
```shift+enter``` - add line break 

For both chat and posts?

Note: I am unable to send empty posts using ```enter``` anywhere right now - so you might be seeing different behaviour to me. 

Can you let me know how you send empty posts or chats and on what platform.

**Comment by pj8912** [comment]
_Can you let me know how you send empty posts or chats and on what platform._

uploading empty posts, and empty messages

https://user-images.githubusercontent.com/59218902/230132104-58a10862-27d4-4f9b-89f7-e50f8aa16a26.mp4

**Comment by pj8912** [comment]
`ctrl+enter` 
This works on twitter

**Comment by arpee** [comment]
So you are still having to click the post button. It's not that you are accidentally sending on ```enter```...

So, if I understand correctly - you are asking for two separate changes:

- prevent posting of empty posts by pressing on the 'post button' (or any method)
- add and event so that ```ctrl+enter``` submits the post form.

**Comment by arpee** [comment]
https://github.com/SaitoTech/saito-lite-rust/commit/a673ae20ab6e8668a5f8feb9d148d3fc388c2016

Update pushed - will go out in the next day or so.

Two updates:

- trigger click on post button on ```ctrl+enter```
- bug out of submit action if post is null or only whitespace and has no images attached.

**Comment by pj8912** [comment]
cool

**Comment by arpee** [comment]
Already in the staging branch.
Will likely go to prod in the next day or so.
