### ISSUE TITLE
Invites not seen by other wallets, disappear on refresh

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#169]
Test Steps:
1) Make invite
2) If it doesn't appear at all, refresh on the wallet that created it, it will be gone.
Other information:
- Device Used: PC
 - OS: Win10
 - Browser: Chrome and Firefox, both on incognito.
 - Version:  Firefox 96.03 Chrome 97.0.4692.99
![image](https://user-images.githubusercontent.com/61957527/152090703-30810cbf-16f6-4aca-bb5c-c7c3b9efce98.png)

**Comment by trevelyan** [comment]
no issue, just a delay in txs getting confirmed and blocks downloading. tested.
