### ISSUE TITLE
Chess: Feature Request - See Game Settings Before Joining 

### ISSUE THREAD

**Issue by anthon11786** [SaitoTech/saito-lite-rust#1696]
When seeing an open invite for a chess match in the arcade, I really want to see match settings, specifically, the time setup. If I only have 15 mins I want to only join a 5 min game - I don't want to join an unlimited time match. 

Additionally, (a separate feature though) it would be great if I could suggest a setting for an open invite.  
Currently to create a game I need to preselect the match timer but I may be open to other times as well. It should be possible for an interested party to essentially give a counteroffer to the open invite saying yes, "if we plaly 5mins" for example.

**Comment by arpee** [comment]
The time is visible in the invitation - if set.

On the second request, you are imagining that the time should be able to be adjusted post game start - by agreement?

**Comment by anthon11786** [comment]
Not exactly after the start - I was imagining after clicking on the invite you could suggest new settings like a counter offer to their invite. 

I'm realizing now you can always direct message them to see if they would play a different timer.

**Comment by anthon11786** [comment]
Regarding the first point - I still think explicitly stating that a chess invitation has unlimited time would be helpful.

**Comment by f8daniel** [comment]
I've made the display of clock options more user friendly. It will say "unlimited" if the game invite hasn't set a clock, and will append "minutes" when there is a clock setting.
Also, I've reintroduced a feature that categorizes game invites as "custom" if the inviter has set any of the advanced settings. That should serve as a clue to pay attention to the options before clicking join.

**Comment by anthon11786** [comment]
@f8daniel great! Thank you for the update
