### ISSUE TITLE
RedSquare - (Mobile) Chat Not Rendered on First Try

### ISSUE THREAD

**Issue by anthon11786** [SaitoTech/saito-lite-rust#1722]
On mobile accessing the chat will sometimes take multiple attempts of going to the settings menu and clicking 'chat' before I see the list. 

I found that after clicking on a tweet and trying to go to the chat is easiest to reproduce this problem consistently. 

Additionally, on mobile, after clicking on a post the view will be skewed downward so the top is actually blocked by the Saito red header. This blocks the '<- Red Square' button and in this case the community chat because it's the top of list.

**Comment by f8daniel** [comment]
Note for team: The HTML/CSS for inserting the back button when opening a tweet thread is off. Content sometimes gets stuck under the header.

**Comment by f8daniel** [comment]
There may be other mobile chat issues now, but not these specifically anymore
