### ISSUE TITLE
Comment count in each post is not updating (To some games)

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#173]
**Test Steps**:
1. Create a post from User 1
2. Add comment on the post via User 2
3. **Comment count is not updated**

Issue is prevalent in Wuzuqi and Wordblocks. Need to ensure it's working on the other games

<img width="388" alt="image" src="https://user-images.githubusercontent.com/96273856/152114728-7558bf0d-3ee5-4f32-8cbb-f6474c47217a.png">

**Comment by trevelyan** [comment]
The comment count IS now updating, although it happens after-the-fact as the comments and posts need to hit the blockchain and get confirmed before action is happening. There is no obvious solution to this problem that does not involve a significant amount of workaround in terms of sweat with UI, so we should not worry about fixing this sort of thing until we have a UI/UX flow that actually works and solves the major problems.

Once we have organic forum growth and genuine activity we can smooth out more minor problems like these.
