### ISSUE TITLE
Red Imperium is stuck at initialization

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#175]
**Test steps**:
1. Open 2 Arcades (Player 1 & 2)
2. Player 1 Create Red Imperium
3. Player 2 Join the Game
4. Both Player starts the game
5. Both player stuck at initialization, shows error in console

**Error**:
<img width="1024" alt="RI Initialization" src="https://user-images.githubusercontent.com/96273856/152106403-edcefbe2-b1c1-4d40-8af6-45b7fdc680a4.png">

**Comment by trevelyan** [comment]
This is fixed.

The culprit was gametemplate trying to render the log with render() instead of render(app, mod);
