### ISSUE TITLE
Arcade

### ISSUE THREAD

**Issue by SankaD** [SaitoTech/saito-lite-rust#1752]

**Comment by umairkhannn** [comment]
Fixed arcade issues: 

![image](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/d771a653-7e48-46ef-8424-64cbd9d645b4)

**Comment by arpee** [comment]
Outstanding issue:

* games not being removed from UI when cancelled or forfeited.
* (they are removed on refresh)
