### ISSUE TITLE
Arcade gets stuck on a purple screen, fails to load.

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite-rust#176]
https://rustest.saito.io/arcade/ won't load at the moment, gets stuck on the purple background. 
Wiping cache/hard-refreshing won't work either. Console doesn't show anything, tested on fresh incognitos.

Device Used: Desktop PC 
OS: Windows 11
Browser: Chrome 97.0.4692.99 / Firefox 96.0.3 (64-bit) 

![image](https://user-images.githubusercontent.com/54612963/152258628-c68c4abf-136f-423a-8c8e-be4b5d6c610b.png)

![image](https://user-images.githubusercontent.com/54612963/152258424-9f56551b-42e3-40ba-9986-e12852475e41.png)

**Comment by trevelyan** [comment]
Cannot replicate. Assume that other fixes have solved this.

**Comment by Tuch-o** [comment]
Yeah, arcade is back up at the moment

**Comment by Tuch-o** [comment]
Yeah, arcade is back up at the moment.
