### ISSUE TITLE
Poker

### ISSUE THREAD

**Issue by SankaD** [SaitoTech/saito-lite-rust#1762]

**Comment by umairkhannn** [comment]
Fixed poker issues, working now with wasm code:

![Screenshot from 2023-07-11 13-55-23](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/4e1f23c1-bd27-4955-acdf-b3ca407b2081)
![Screenshot from 2023-07-11 13-54-58](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/3dfb7c9b-712e-4d48-8632-c27146776875)
![Screenshot from 2023-07-11 13-54-09](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/3b6b0bdb-3c7f-4fa5-973b-b16892e715b8)
