### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by SankaD** [SaitoTech/saito-lite-rust#1770]
![Image](https://github.com/SaitoTech/saito-lite-rust/assets/2867779/3dde12a2-ceae-4f55-a2cc-b72ed962be5a)

There is an issue with private key import - otherwise working well for now.

**Comment by umairkhannn** [comment]
Settings overlay now working:

![Screenshot from 2023-07-20 04-06-54](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/2f5e28e0-f2cd-4ca6-91b4-0441c1278d52)

**Comment by umairkhannn** [comment]
Steps to reproduce "import key" issue:
![image](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/51b2f004-1b46-45b1-a347-5aa4e4e7345c)

**Comment by umairkhannn** [comment]
There seems to be an issue with either app.blockchain.resetBlockchain() or app.wallet.save() when importing key. @SankaD's gonna have a look at it.
