### ISSUE TITLE
Wuzuki - Player accepting the game invite stuck on loading animation. 

### ISSUE THREAD

**Issue by estapeluo** [SaitoTech/saito-lite-rust#181]
The player accepting the game invite of Wuzuki is stuck on the loader animation, console log shows its looping.

Workaround: F5 then press continue.

![image](https://user-images.githubusercontent.com/59634305/152475434-bb5a01e1-adea-450f-9db6-ebf32dab5285.png)

**Comment by f8daniel** [comment]
This shouldn't be an issue anymore as there have been many improvements to the game initialization process in the preceding 11 days.
