### ISSUE TITLE
mixin

### ISSUE THREAD

**Issue by SankaD** [SaitoTech/saito-lite-rust#1810]

**Comment by umairkhannn** [comment]
Mixin withdraw, deposit changes:

![image](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/7be2b9d9-7298-4a09-b8ad-55c8113c1306)

**Comment by f8daniel** [comment]
References to app.network.peers results in an error

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/0c3ceb1b-9522-4ae7-b034-4f83d45470a9)
