### ISSUE TITLE
Settlers Action Box Overlapped

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#1861]
The rapid clicking seems to have caused the layout of the Action Box to overlap.
When this happened, clicking on the buttons or anywhere outside the Action Box does not remove it.

We had to abandon the game since refreshing didn't solve the problem.

![image](https://github.com/SaitoTech/saito-lite-rust/assets/101871246/6c53cc3c-d377-4088-b235-c21e2201eb1c)

<img width="960" alt="image" src="https://github.com/SaitoTech/saito-lite-rust/assets/101871246/488bcf2a-34ea-4fbf-9ef8-6dc2c9ac2d11">

**Comment by f8daniel** [comment]
Make a new issue if this happens again
