### ISSUE TITLE
Multiple instance of the block address are shown in the explorer

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#188]
**Issue**:
<img width="813" alt="image" src="https://user-images.githubusercontent.com/96273856/152756183-77497d85-fb64-418a-82a6-7902bd28ee52.png">

**Link tested**:
https://staging.saito.io/explorer/

**Comment by trevelyan** [comment]
This is occurring because the genesis period is quite short, which is not something that will happen in production.

Thus not considered a critical bug.

Genesis period has already been updated to 100,000 blocks.
