### ISSUE TITLE
(PROD) BlackJack: Dealer still wins even if both players have the same hand score

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1895]
Tested multiple times

![bj2](https://github.com/SaitoTech/saito-lite-rust/assets/107991527/602bedef-71f8-434a-938d-50c89f1154f3)

![bj3](https://github.com/SaitoTech/saito-lite-rust/assets/107991527/483f6966-b675-45c4-88a8-798707f8cb79)

**Comment by f8daniel** [comment]
That's how the game is designed
