### ISSUE TITLE
Settlers Card Count Not Reflecting

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#1897]
As seen on the 2 screenshots below, I bought a development card. I got the card but it says “cards: 0” instead of “cards: 1”.

![348363508_1555869251571979_4188786657411415560_n](https://github.com/SaitoTech/saito-lite-rust/assets/101871246/c89fd7f2-ba28-4bf0-b0c4-ffaa4b52e42b)
![348363508_1555869251571979_4188786657411415560_n](https://github.com/SaitoTech/saito-lite-rust/assets/101871246/6d79fcda-4d19-4727-abd5-509e97ede8fb)

**Comment by f8daniel** [comment]
fixed
