### ISSUE TITLE
Pandemic Test #2 (Game Stopped Responding, Leave both players waiting for turn to end)

### ISSUE THREAD

**Issue by andreyconsuelo** [SaitoTech/saito-lite-rust#190]
![image](https://user-images.githubusercontent.com/99187033/152796421-ea2d91ed-b93d-4f22-924d-5e99143bde53.png)

After a turn of Traveling through land both players are now waiting for the turn to finish but the game stopped responding and is stuck with "Waiting for _username_" 
 
 Here is the console log from the moment the game stopped responding and after I refresh both players game and it still hasn't responded:
 
 DevTools failed to load source map: Could not load content for https://staging.saito.io/saito/lib/hammer/hammer.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
saito.js:36 loading blake3
saito.js:36 blake3 :  {default: ƒ}
saito.js:36 Initializing Saito Light Client
saito.js:36 GAME OVER + LAST BLOCK: 0 -- 0 -- 99ce0cb38b69b0430f1accbab218f7028e48c67e1076f3778514b7e2af03cf47195599ac88f0c2691219a70cbc8b902173a918067cd2427cdb6d7242709a60da
saito.js:36 PLAYERS: {"request":"loaded","game":"Pandemic","game_id":"99ce0cb38b69b0430f1accbab218f7028e48c67e1076f3778514b7e2af03cf47195599ac88f0c2691219a70cbc8b902173a918067cd2427cdb6d7242709a60da","options":{"gamename":"Pandemic","game-wizard-players-select":"2","difficulty":"easy","player1":"random","player2":"random"},"players":["268NqZHszUrUG6rzurS8yYAfbMUpPYWsWGJ5vKRWkYQKt","saHBkDoNXTMWBcUoK7Z77yTTCKVPof3R2gnpPwugH89W"],"players_needed":1,"over":0,"last_block":0}
saito.js:36 INCLUDING GAME!
saito.js:36 rendering the hud here...
saito.js:36 *** RESIZING HUD***
saito.js:36 *** RESIZING HUD FROM STATUS***
saito.js:36 Height: 0 Width: 0
saito.js:36 done with resize Hud Height...
saito.js:36 *** RESIZING HUD***
saito.js:36 *** RESIZING HUD FROM STATUS***
saito.js:36 div.status-message 49
saito.js:36 Height: 49 Width: 379
saito.js:36 done with resize Hud Height...
saito.js:36 *** RESIZING HUD***
saito.js:36 *** RESIZING HUD FROM STATUS***
saito.js:36 div.status-message 49
saito.js:36 Height: 49 Width: 379
saito.js:36 done with resize Hud Height...
saito.js:36 {sanfrancisco: {…}, chicago: {…}, montreal: {…}, newyork: {…}, washington: {…}, …}
saito.js:36 QUEUE: round,turn	1,turn	2,infect,draw_player_card	1	2,turn	2,turn	1,turn	2,turn	1
saito.js:36 *** RESIZING HUD***
saito.js:36 *** RESIZING HUD FROM CARDS*** 0
saito.js:36 Mode: 0 7 1 405
saito.js:36 Width: 0 57.857142857142854 600
saito.js:36 81.57857142857142 81
saito.js:36 Height: 81.57857142857142 43
saito.js:36 QUEUE ENTRIES: 9
saito.js:36 LATEST: turn	1
saito.js:36 QUEUE: round,turn	1,turn	2,infect,draw_player_card	1	2,turn	2,turn	1,turn	2,turn	1
saito.js:36 *** RESIZING HUD***
saito.js:36 *** RESIZING HUD FROM CARDS*** 0
saito.js:36 Mode: 0 7 1 405
saito.js:36 Width: 0 57.857142857142854 600
saito.js:36 81.57857142857142 81
saito.js:36 Height: 81.57857142857142 43
saito.js:36 rendering the hud here...
saito.js:36 *** RESIZING HUD***
saito.js:36 *** RESIZING HUD FROM CARDS*** 0
saito.js:36 Mode: 0 7 1 405
saito.js:36 Width: 0 57.857142857142854 600
saito.js:36 81.57857142857142 81
saito.js:36 Height: 81.57857142857142 43
saito.js:36 not sending the transaction to peer as the socket is not open yet
(anonymous) @ saito.js:36
e.propagateTransaction @ saito.js:36
(anonymous) @ saito.js:36
(anonymous) @ saito.js:36
(anonymous) @ saito.js:36
(anonymous) @ saito.js:36
r @ saito.js:36
e.mine @ saito.js:36
(anonymous) @ saito.js:36
(anonymous) @ saito.js:36
(anonymous) @ saito.js:36
(anonymous) @ saito.js:36
r @ saito.js:36
(anonymous) @ saito.js:36
setInterval (async)
e.startMining @ saito.js:36
(anonymous) @ saito.js:36
(anonymous) @ saito.js:36
(anonymous) @ saito.js:36
s @ saito.js:36
Promise.then (async)
c @ saito.js:36
(anonymous) @ saito.js:36
s @ saito.js:36
e.initialize @ saito.js:36
(anonymous) @ saito.js:36
(anonymous) @ saito.js:36
(anonymous) @ saito.js:36
s @ saito.js:36
Promise.then (async)
c @ saito.js:36
s @ saito.js:36
Promise.then (async)
c @ saito.js:36
s @ saito.js:36
Promise.then (async)
c @ saito.js:36
s @ saito.js:36
Promise.then (async)
c @ saito.js:36
(anonymous) @ saito.js:36
r @ saito.js:36
e.init @ saito.js:36
(anonymous) @ saito.js:36
(anonymous) @ saito.js:36
(anonymous) @ saito.js:36
(anonymous) @ saito.js:36
r @ saito.js:36
(anonymous) @ saito.js:36
window.onload @ saito.js:36
load (async)
55038 @ saito.js:36
a @ saito.js:36
(anonymous) @ saito.js:36
(anonymous) @ saito.js:36
saito.js:36 connected to network Event {isTrusted: true, type: 'open', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
saito.js:36 peer handshake complete with: dgMJhF4jPqibih19euTi1G6ijREMYFzPyGSj43WfpQpB
saito.js:36 RECEIVED GSTCHAIN
saito.js:36 adding Ghost to Blockchain!
saito.js:36 block hash now added, but nothing is longest-chain!
saito.js:36 adding Ghost to Blockchain!
saito.js:36 block hash now added, but nothing is longest-chain!
saito.js:36 adding Ghost to Blockchain!
saito.js:36 block hash now added, but nothing is longest-chain!
saito.js:36 adding Ghost to Blockchain!
saito.js:36 block hash now added, but nothing is longest-chain!
saito.js:36 adding Ghost to Blockchain!
saito.js:36 block hash now added, but nothing is longest-chain!
saito.js:36 adding Ghost to Blockchain!
saito.js:36 block hash now added, but nothing is longest-chain!
saito.js:36 adding Ghost to Blockchain!
saito.js:36 block hash now added, but nothing is longest-chain!
saito.js:36 adding Ghost to Blockchain!
saito.js:36 block hash now added, but nothing is longest-chain!
saito.js:36 adding Ghost to Blockchain!
saito.js:36 block hash now added, but nothing is longest-chain!
saito.js:36 adding Ghost to Blockchain!
saito.js:36 block hash now added, but nothing is longest-chain!
saito.js:36 adding Ghost to Blockchain!
saito.js:36 block hash now added, but nothing is longest-chain!
saito.js:36 adding Ghost to Blockchain!
saito.js:36 block hash now added, but nothing is longest-chain!
saito.js:36 adding Ghost to Blockchain!
saito.js:36 block hash now added, but nothing is longest-chain!
saito.js:36 RECEIVED GHOSTCHAIN: {"start":"","prehash":["e3e78c8db030afbbbcf5a9dc90191e1bf864209793bf1a55a65887907910e83b","ea3997dcd5c3fdb3932dd2ecd381458abcca51f28bea3ba411750969f48a96ec","0ac01e5cb3200de793b7124d7022d6d7a82ee3f1598687ddaf93e5f624f97ffe","6e8beddcf4fe040b2a585268bb47cec7a126389ff94f4cc6f2649ef843df6997","0190c4c653ec6abf11da794825a1d4e3c2ae9fc2cd8b039194bd5536f6ab1c98","c26f2e7c2c84b9bb30d1d3979014b2a89728d75d30b333f09155c11d73edcb82","c7e48b157585451583638065c4d992510f324662cc100d77b69afa247e1451c8","040e7a8ee8b31fc86904c99c48fb265e2bd34c93236699e48af3e963dc215fb3","83548144caf95ff67d597923baf9bc6f403fe45c05a148e2662afbd25e98f0f5","2750dbd4df484dbee8e21a32a2e9ea8a8cac5e927af5dfc430986f71dd2085ab","976261edaea3522ef39b0ce068af4392cab45aa335f27184faed280f8d1dc174","68d57d675bac972c02b28f5e02f6ff669b6c0c8af58ac742470c2bee088bdfae","e3c1d9d9c3a0a84745cb4d74f0797c913972449c8fabc6b0327ef6f54b78dde4"],"block_ids":[1,2,3,4,5,6,7,8,9,10,11,12,13],"block_ts":[1644231235997,1644231246003,1644231265015,1644231275020,1644231306044,1644231379100,1644239570392,1644239616417,1644239626422,1644239777515,1644239811534,1644239822542,1644239860562],"txs":[0,0,0,0,0,0,0,0,0,0,0,0,0],"gts":[false,true,true,true,true,true,true,true,true,true,true,true,true]}

Here is also the game log before everything stopped:
> Montreal gains 1 disease cube
> Baghdad gains 1 disease cube
> INFECTION STAGE: 2 cards to draw
> 43 cards left in deck.
> Player 2 built a research station in osaka.
> Operations Expert moves to undefined
> Player 2 built a research station in tokyo.
> St. Petersburg gains 1 disease cube
> Milan gains 1 disease cube
> INFECTION STAGE: 2 cards to draw
> 45 cards left in deck.
> Player 1 removed 3 black cubes from delhi
> Player 1 built a research station in mumbai.
> Mumbai gains 1 disease cube
> Buenos Aires gains 1 disease cube
> INFECTION STAGE: 2 cards to draw
> 47 cards left in deck.
> Operations Expert moves to undefined
> Player 2 built a research station in chicago.
> Operations Expert moves to undefined
> Operations Expert moves to undefined
> Riyadh gains 1 disease cube
> Kolkata gains 1 disease cube
> INFECTION STAGE: 2 cards to draw
> 49 cards left in deck.
> Medic moves to undefined
> Medic moves to undefined
> 44 cards left in deck.
> 48 cards left in deck.
> New York infected with 1 blue
> Tehran infected with 1 black
> Cairo infected with 1 black
> Santiago infected with 2 yellow
> Jakarta infected with 2 red
> Sydney infected with 2 red
> Manila infected with 3 red
> Taipei infected with 3 red
> Delhi infected with 3 black

**Comment by f8daniel** [comment]
I couldn't reproduce the error (may have been an issue with the blockchain level). Nevertheless, many additional improvements to Pandemic have been pushed through (such as the "undefined"s in the gameLog)

**Comment by andreyconsuelo** [comment]
Duly noted, I'll wait for the Staging Site to be updated, and test it
again, really appreciate it, cheers.
