### ISSUE TITLE
(PROD) Wuziki Bar in the middle of the board 

### ISSUE THREAD

**Issue by Darkuso** [SaitoTech/saito-lite-rust#1900]
Currently this bar is in the middle of the screen/board after you open a wuziqi game, there is no way to close it but can be moved around
![image](https://github.com/SaitoTech/saito-lite-rust/assets/9855617/96ffc6be-c221-40c0-bc0b-ecc4107573e8)

**Comment by f8daniel** [comment]
Fixed
