### ISSUE TITLE
(PROD) Chess: Same player can offer a "draw" and accept it as well

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1901]
Steps:
1) Player A offers a "draw" to Player B
2) Player A repeats the process
3) Player A can somehow accept his own offer and Win the game

Issues:
1) A player should not be able to accept his/her own draw offer
2) When the draw offer is accepted, the game should result as a "draw". not a "win"

https://github.com/SaitoTech/saito-lite-rust/assets/107991527/41ca3dea-6537-4270-8476-777cb2430228

**Comment by f8daniel** [comment]
1) fixed: You cannot accept your own draw offer.
2) A draw = a tie = both players are winners...
