### ISSUE TITLE
(PROD) Settlers of Saitoa: Players are not color-coded

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1902]
Player icons does not have any color-codes. Makes it a bit confusing which one you are playing

![settlers1](https://github.com/SaitoTech/saito-lite-rust/assets/107991527/c0359f4e-4056-4e09-afd3-36b36b3ceed4)

**Comment by f8daniel** [comment]
It's hard to do this without making the display ugly, but a trial is coming through
