### ISSUE TITLE
(PROD) Settlers of Saitoa: a player is able to get 2 resources with 1 bank trade

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1903]
*glitch originally found by Tucho/Krom*

Steps:
1) Get enough resources to trade with the bank
2) Click on "Bank"
3) Select the resource you want to trade to
4) After selecting the resource, you can still click on "Bank" again (if you are fast enough)
5) You can successfully get another free resource in the same turn

https://github.com/SaitoTech/saito-lite-rust/assets/107991527/1d9f328c-33dc-4208-a29f-65d02f784f45

**Comment by trevelyan** [comment]
will sort
