### ISSUE TITLE
(PROD) Poker: After ending a round, the cards from the last round are still present in the next round, next to the new Ones in both users

### ISSUE THREAD

**Issue by StatixSx** [SaitoTech/saito-lite-rust#1907]
They only disappear after reloading the page in every round

![Screenshot_31](https://github.com/SaitoTech/saito-lite-rust/assets/106467417/a2daab86-e3fc-448c-917a-3061b0e110fe)
![Screenshot_1810](https://github.com/SaitoTech/saito-lite-rust/assets/106467417/edd12fab-05ee-4444-a931-19d7c3888513)

**Comment by f8daniel** [comment]
Can't replicate the issue. Maybe fixed but not closed?

**Comment by StatixSx** [comment]
yeah, got fixed like 5 days ago, gonna close this report with the comment, thanks for the fixes :).
