### ISSUE TITLE
Unable to Interact with Settlers Interface

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#1914]
Upon starting the game, the 1st player was asked to place his village but was unable to do so.
The cursor is in hand cursor mode which just drags the surface of the play area.
Tried it again with the other player being the 1st player and the issue also happened.

This bug is found right after the most recent update today.

<img width="960" alt="Settlers_HandCursor1" src="https://github.com/SaitoTech/saito-lite-rust/assets/101871246/dc9e3b5c-1d87-4742-bd8b-0ce62866d4b3">

<img width="960" alt="Settlers_HandCursor2" src="https://github.com/SaitoTech/saito-lite-rust/assets/101871246/d4c9cafc-df88-4c34-9cd9-33af54f96887">

**Comment by f8daniel** [comment]
Outdated, game works fine
