### ISSUE TITLE
GIF icon not working

### ISSUE THREAD

**Issue by pj8912** [SaitoTech/saito-lite-rust#1917]
despite the font-awesome version being `Font Awesome Free 6.1.2 by @fontawesome ` the `GIF` is not working

**Comment by pj8912** [comment]
tried this unicode e190 as `.fa-gif{content : "\e190";}` still not working

**Comment by f8daniel** [comment]
Could you be more specific? 
https://fontawesome.com/icons/gif?f=classic&s=solid
That is a pro icon. You have to pay for it.

**Comment by pj8912** [comment]
Oh! ok , Video Icon just confuses me that's why. No problem
