### ISSUE TITLE
TS - Issue with black overlay on cards such as Cambridge Five

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#1924]
When playing Cambridge Five, if the US has a scoring card, a black shade overlay gets put on the screen that does not allow clicking, users must click around to get rid of the overlay before being able to move again, refreshing does not get rid of it, only clicking in the lower part of the screen, as far as tests have shown this is the only way to get rid of this black overlay.

https://github.com/SaitoTech/saito-lite-rust/assets/61713323/0cf36c01-53ca-4deb-9414-20890a25dd6e

**Comment by f8daniel** [comment]
Agreed, should improve the overlay, but at least reduced the blocked click space so it's more natural to close it.
