### ISSUE TITLE
(PROD) Wordblocks: End game issue

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1927]
Tested multiple times and got the same results. 

1) Game does not immediately end when either player finishes tile. Game only "ends" when both player's tiles are used up
2) After a player uses up the last tile, game gets stuck and does not announce the winner in the HUD (it appears it the console however)

**Game stuck when all tiles are used up**
![wb1](https://github.com/SaitoTech/saito-lite-rust/assets/107991527/706783e3-3106-4ebe-a282-138dda79208a)

**Console displays winner (HUD stuck)**
![wb2](https://github.com/SaitoTech/saito-lite-rust/assets/107991527/5f8124fb-865a-4d40-8f64-ab4b49aa030f)

**Comment by f8daniel** [comment]
I'm not sure you are allowed to discard tiles to end the game...

**Comment by f8daniel** [comment]
The game won't check for game over after a discard. So, either we need to 
1) allow a player to end the game by throwing away their tiles
2) remove the ui to discard when there are no tiles left to draw

Thoughts??? @arpee

**Comment by arpee** [comment]
Remove the discard option seems cleanest.

I think.

**Comment by f8daniel** [comment]
fixed
