### ISSUE TITLE
SETTLERS game stuck due trading

### ISSUE THREAD

**Issue by anaelyrm** [SaitoTech/saito-lite-rust#1929]
After making several successful and unsuccessful trades I could not accept or send resources.

![image](https://github.com/SaitoTech/saito-lite-rust/assets/136638656/838b0fc4-d9d5-484f-a731-a15d889d1783)

Finally, the game showed a message to my opponent "rebroadcasting last move" while I was waiting for the "roll dice".

![image](https://github.com/SaitoTech/saito-lite-rust/assets/136638656/4691dd8e-3116-4c79-a8f8-9dd3460e6950)

**Comment by afkafk088** [comment]
**Additional findings:**

Upon testing, I found out that one to one resource trade works. (e.g. 1 wood for 1 brick).

However, if you trade 2 or more resources, the trading gets stuck and eventually broken. Having said that, you can still play the game normally (Only the trading feature breaks).

**Comment by Rammko** [comment]
I tested this to check, it seems it happens only when trading for nothing, been trying regular trades, even trades of 6 resources for 1 resource and the trade happens without issue

**Comment by f8daniel** [comment]
should be fine
