### ISSUE TITLE
Wallets are not syncing invites.

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#193]
When creating invites, other wallets don't see them.

Device Used: PC
OS: Win10
Browser Chrome + Opera
Version Chrome 98.0.4758.82

![image](https://user-images.githubusercontent.com/61957527/153106402-fe787698-87af-4d22-a8ea-f76f6e767377.png)

**Comment by trevelyan** [comment]
Closing as I cannot replicate.
