### ISSUE TITLE
(PROD) Settlers of Saito: Turn getting temporarily stuck when you try to spend with incomplete resources

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1930]
Steps:
1) Click on "Spend" on your turn
2) Select an option where you have an "insufficient resources"
3) player box gets stuck on "processing..." 
4) temporary fix: refresh

https://github.com/SaitoTech/saito-lite-rust/assets/107991527/ab44a6f8-b00d-44ae-a19d-555d9416c128

**Comment by f8daniel** [comment]
not an issue any more
