### ISSUE TITLE
TS- Minor UI issue with position of "Play Event" and "Play Ops"

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#1932]
A recent update flipped the position of these items on the menu. "Play Event" used to be on the top and "Play Ops" used to be below it. It was like this for the last 3+ years and the sudden flip to them, while not an issue per se, Is very disorienting for players who are used to how it was originally. 

![image](https://github.com/SaitoTech/saito-lite-rust/assets/61713323/fc54e0eb-ac52-4a13-a375-dda9e4188303)

Would hope for them to be restored to their original position for convenience.

![image](https://github.com/SaitoTech/saito-lite-rust/assets/61713323/a6d3e03f-e484-488b-b547-2ae721a67eea)

**Comment by f8daniel** [comment]
no problem
