### ISSUE TITLE
In-game Chat Box Doesn't Have Emoji Button

### ISSUE THREAD

**Issue by Badjavii** [SaitoTech/saito-lite-rust#1933]
Within the games, the chat boxes do not have the button to place emojis, that is, you do not have the option of emoji color in your messages, either in the Community Chat or in a private one, unlike the case within the arcade and the RedSquare.

This is how the chat box looks in the case of Arcade and RedSquare (with its respective emoji button) (pov: this is how it should look normally):

![image](https://github.com/SaitoTech/saito-lite-rust/assets/128875626/c5c0d0b0-9289-4d2f-9b8f-548b58b65c9e)
![image](https://github.com/SaitoTech/saito-lite-rust/assets/128875626/316c8b3a-0a7d-4eba-ba2d-a055167657fb)

And this is how the chat box looks with the error in the case of being inside a game (in this case Chess):

![image](https://github.com/SaitoTech/saito-lite-rust/assets/128875626/5dcf5591-2554-444e-a170-2b57a6a400da)

For this report, all the games within the arcade were tested and here is a table with the games in which the error is present and in which it is not (that is, they are fine). *+* means that the error is present and *-* means that the error is not present.

![WhatsApp Image 2023-06-20 at 18 37 30](https://github.com/SaitoTech/saito-lite-rust/assets/128875626/e4dabd7a-8208-4b8a-bfd6-3bf51844e7ea)

**Comment by f8daniel** [comment]
No biggie, we are switching from font awesome 5 to font awesome 6 (as used in the chat popup), but neglected to update all the html files...
