### ISSUE TITLE
(PROD) Poker: Game result does not show up on HUD

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1939]
When a player wins the game, result does not show on HUD (only on console). HUD sort of gets stuck on "clearing the table"

**HUD stuck on "clearing the table" after a player wins**
![poker1](https://github.com/SaitoTech/saito-lite-rust/assets/107991527/f7603c3f-54f3-4357-abe3-820e2b951353)

**Console**
![poker 2](https://github.com/SaitoTech/saito-lite-rust/assets/107991527/09160423-7ba9-4297-9762-6c34a893bac3)

**Comment by f8daniel** [comment]
Not really a bug, but a lack of a status-hud to display the game over notice
