### ISSUE TITLE
TS - Voice of America Return Button Bug

### ISSUE THREAD

**Issue by Kromtastic** [SaitoTech/saito-lite-rust#1943]
Bug: Using the Return Button after removing some influence with Voice of America returns you to your hand of cards without giving back the influence you've removed. This is fixed if you reload the website, BUT the return button will disappear.

https://github.com/SaitoTech/saito-lite-rust/assets/98101498/4d38f7c2-35ab-44f2-93aa-c0a03f936e18

It can be recreated, tested twice.

**Comment by f8daniel** [comment]
Back button removed
