### ISSUE TITLE
(Generic) Create Game on game page does not function...

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#195]
![image](https://user-images.githubusercontent.com/70703104/153114362-cde7493c-7dc9-4d30-a349-8a8b1bab404e.png)

**Comment by trevelyan** [comment]
Just a quick note that I cannot replicate this problem on Master.

**Comment by trevelyan** [comment]
replicated, thanks Dan

**Comment by trevelyan** [comment]
Fixed! Will push shortly.
