### ISSUE TITLE
(PROD) Settlers: Still able to trade even without the chosen resouce

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#1978]
The trade still goes through even if the chosen resource is gone

Example Scenario

Steps: 
1) Player A broadcasts a trade (Player A's Wood trade to Player B's Wool)
2) Player A uses the Wood to build a road (Wood is now gone)
3) Player B accepts the broadcast trade
4) Player B can still receive the Wood (the one missing from Player A's hand)
5) Player A on the other hand, does not receive any Wool

https://github.com/SaitoTech/saito-lite-rust/assets/107991527/cbd2feb2-9682-4786-95ed-42c990dd82ae

**Comment by f8daniel** [comment]
Added controls to check your resources for accepting trades
