### ISSUE TITLE
chat messages are deleted in very short periods of time

### ISSUE THREAD

**Issue by Badjavii** [SaitoTech/saito-lite-rust#1986]
Today, July 20, I sent a message with the text "Hey Hey" at 1:00 p.m. However, when I checked the chat at 1:40 p.m., I realized that this message and others sent around that time had disappeared.

I attached a screenshot of the start of the chat

![image](https://github.com/SaitoTech/saito-lite-rust/assets/128875626/b0d5373e-59f0-495a-98ef-6ef1e094d930)

At the moment, the chat continues to delete messages of approximately 20 minutes

**Comment by f8daniel** [comment]
Good catch, there was a bug there where I was accidentally deleting something
