### ISSUE TITLE
Unthemed Chat in Games

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite-rust#1988]
![Image](https://user-images.githubusercontent.com/2867779/255072587-eee8be25-5819-4835-88af-8780e88f6297.png)

We are seeing chat appear but unthemed or with missing css in games.

**Comment by f8daniel** [comment]
I need more info
![image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/eb20968b-ba8d-4299-be9d-2af792b6c5a3)
