### ISSUE TITLE
Settlers - Players can skip moving the bandit 

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#2038]
When a player rolls the bandit, they have the option to roll the dice without placing the bandit on a tile. Pretty sure this is not intentional as it gives the option to do 2 rolls in one turn. Linked video shows issue in motion

https://github.com/SaitoTech/saito-lite-rust/assets/61713323/28f229da-9d9d-4364-af23-b6c1e21a1956

**Comment by f8daniel** [comment]
Fixed
