### ISSUE TITLE
(PROD) Twilight Struggle: Can coup other countries outside EU when eventing "Tear down this wall" 

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#2068]
As per the card description, only countries in EU can be couped using the card

![tear down](https://github.com/SaitoTech/saito-lite-rust/assets/107991527/6f148d5a-108d-47f2-97ac-6e100bf19adc)

**Comment by f8daniel** [comment]
The region check was inside the defcon check... fixed
