### ISSUE TITLE
(PROD) Twilight Struggle: "Original/Optional deck" switches to "Saito deck"

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#2072]
Steps:
1) Choose original/optional deck when creating a TS game
2) Play normally
3) When reaching turn 3, the deck switches to "Saito Deck" on reshuffle
4) From them on, the game now plays "Saito Deck"

**Comment by Tuch-o** [comment]
this is fixed on the latest version
