### ISSUE TITLE
There is lag when creating a new mixin key

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#2082]
![Untitled](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/775076a6-31ae-4ef5-b954-ea944c6cb897)

When I activated TRX the QR code disappeared for 20 seconds... I thought it was broken.
We should replace the QR code with a spinner and replace the key text with a message "generating keys..." 
so that users have feedback letting them know that something is happening

**Comment by umairkhannn** [comment]
Fix pushed in PR

 https://github.com/SaitoTech/saito-lite-rust/pull/2088
