### ISSUE TITLE
Transaction History UI

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#2085]
![Untitled](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/7c30e176-c78f-449e-b35d-d46256ba90e6)

Green text is not readable against background color... needs a text-shadow, drop-shadow or something to improve contrast (Otherwise green for deposits, red for withdrawals is good UI design)

Pagination should be dependent on exceeding x number of records. I shouldn't be able to click on the errors and break the overlay

![image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/bb7bef39-ead6-48c1-ac4c-274c55ec389e)

**Comment by f8daniel** [comment]
![image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/deb9f15d-870a-4172-8421-f6cce8f7535b)

Should localize timestamps?

**Comment by umairkhannn** [comment]
Thanks for suggestions. 

- The green color in dark theme certainly makes it harder to read. Will try text shadow for text, will probably improve readability. 
- hmm pagination shouldn't be clickable when records doesn't exceed one page (20 records per page is limit)
- Nice catch for date time, didn't realize it was in UTC. Will add the offset local hours to make it local timestamp.

**Comment by f8daniel** [comment]
app.browser.formatDate should be useful
