### ISSUE TITLE
(PROD) Settlers: Players are seeing their names on different colors

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#2092]
![saitostt](https://github.com/SaitoTech/saito-lite-rust/assets/107991527/fed1237c-f8bd-45b0-bb0a-055d3b8dd10b)

on 3p settlers, players are seeing their name on the scoring track board in different colours as compared to the others perspective.

On my side, I see the ff:
J44: blue
Arks: green
Shane: red

On Ark's side, he sees the ff:
Arks: red
J44: blue
Shane: green

and vice versa

**Additional suggestion: add a color outline on playerbox to know which color you are in the game

**Comment by f8daniel** [comment]
I did one test and it looks fine, but I don't doubt that there is sometimes some weirdness around 3p games...
