### ISSUE TITLE
(PROD) Twilight Struggle: Card view display options doesnt look right

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#2124]
https://github.com/SaitoTech/saito-lite-rust/assets/107991527/2e1e30ec-970d-4fc0-b61a-4766ba6d4828

**Comment by f8daniel** [comment]
Oh, the css for hud was rewritten to only consider the long format, unless people really want the square or vertical alignment, it is better just to remove the toggle icon
