### ISSUE TITLE
Settlers: Play Card Button

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#2137]
The play card button is not as visible as it used to be. It is now just text which is placed on top of the trade button.

<img width="946" alt="image" src="https://github.com/SaitoTech/saito-lite-rust/assets/101871246/5539ada6-5382-4a58-9df3-05e1a5f64808">

**Comment by f8daniel** [comment]
1) People requested a way to view their development cards (even when they cannot play them). That requires have a non-intrusive button appear when they have dev cards in their hand. It would be redundant to have both the old button and the new button or confusing to switch back and forth depending on whether it is your turn or not.

2) When you have four optinos (bank/play card/build/end turn), it pushes the UI to the breaking point, especially in mobile. So it is better design to not have the big (play card) button.
