### ISSUE TITLE
Fix chat in mobile

### ISSUE THREAD

**Issue by joelshu1** [SaitoTech/saito-lite-rust#2138]
Not sure why this isn't an open issue here, but i see people mentioning it all the time; for good reason.
This is simply a css responsiveness issue. But some thinking must remain as to how to presumably see the chat menu and switch to another open chat, or create a new one for that matter.

![IMG_4832](https://github.com/SaitoTech/saito-lite-rust/assets/95905420/c3043a2e-3098-4cef-8160-d540c1e63b90)
![IMG_4831](https://github.com/SaitoTech/saito-lite-rust/assets/95905420/4673559c-4df1-43a3-bcab-b9d39b6d866b)
![IMG_4830](https://github.com/SaitoTech/saito-lite-rust/assets/95905420/071ff810-833d-4f70-9e34-178dc1785a19)

**Comment by f8daniel** [comment]
This should be fixed in the next roll out
