### ISSUE TITLE
Nuke Wallet - No Confirmation Button

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#2140]
Nuke Wallet button doesn't get confirmation from the user. It is quite prone to mistakes.
Kindly implement a confirmation prompt.

<img width="211" alt="image" src="https://github.com/SaitoTech/saito-lite-rust/assets/101871246/0e7f24da-b09e-4ef3-aa0d-3cad7d12d689">

**Comment by f8daniel** [comment]
fixed
