### ISSUE TITLE
(PROD) Settlers of Saitoa: No button to use development cards

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#2141]
There is no button that let you use the development cards you have purchased.

https://screenrec.com/share/PVAsUo8ifm

**Comment by f8daniel** [comment]
![image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/d4f08917-2cea-4e49-8daa-2561cf2ba5f6)

**Comment by afkafk088** [comment]
ohhh just saw that one! I think it would be better in a bigger font or in a button form like before. Just my 2 cents! closing this :)
