### ISSUE TITLE
Other users not seeing handle in chat or game invites

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#215]
**Description**:
Users can register a handle but it is not visible to other users.

**Test Steps**:
"Open two browsers.
Person A:
1. Register a handle.
2. Send a chat message.
3. Create a game invite.

Person B:

1. Public key is showing, rather than the handle next to chats and when mousing over the identicon in the game invite."

**Comment by trevelyan** [comment]
This problem should be fixed.
