### ISSUE TITLE
Layout bug after restoring keys

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#217]
**Test Steps**
1. Load the page, layout OK.
2. Restore wallet keys and reload the page, layout NOT OK
3. Pop up message before reloading:
"staging.saito.io says
Server reports it does not contain your Saito javascript bundle. This can happen across server upgrades with remotely-hosted application bundles. Do you wish to reset to use the server default and update your default AppStore to this server?"

**Screenshot**
<img width="1586" alt="Screen Shot 2022-02-15 at 6 30 16 AM - Marc Decourt" src="https://user-images.githubusercontent.com/96273856/154070377-8674713c-2a8d-4b2c-aa1f-90bfe7783d23.png">

**Comment by trevelyan** [comment]
This should be fixed.

The applied fix was to use prependElementToDom(html, OBJ); rather than addElementToDo(html, id);

this forces the sidebar to always be added before the main section in the HTML. They were getting reversed for some
