### ISSUE TITLE
Notifications - Reply notification doesnt update url when clicked on

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#2232]
notifications of replies clicking through original tweet in reply does not update TWEET_ID in url 

Notifications: attachEvent will display the tweet (like, reply, retweet, mention) but not affix the tweet id to the URL string

**Comment by arpee** [comment]
Returned this to Ready for Dev as not seeing this working.

**Comment by f8daniel** [comment]
yes it does



![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/ed12f997-acb2-473a-8557-cb50c0f4a1b5)



![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/85a3d8f4-18b2-4509-b90c-39ea784eda48)
