### ISSUE TITLE
Mouseover adding scrollbar and messing with paragraphs on long posts.

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite-rust#2249]
This is distracting - would be good to (not remove and) have the scrollbar on long posts without mouseover, or have the scrollbar not cause the width to change.

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/2867779/2bfe9854-79bc-4a44-9305-16c9259f1f53)

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/2867779/fc3203e4-17e4-4544-b9be-1f677ae7c70a)

**Comment by f8daniel** [comment]
The width doesn't change, but the scroll bar covers the text... can change to hidden scroll

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/95c69dc8-f3c4-4e0d-86b4-7d9246b4594e)

**Comment by f8daniel** [comment]
Alternate solution: add a padding-right to tweet-text.full (and tweet-text.preview) and have the scroll bar always be visible.

**Comment by arpee** [comment]
![Screenshot_2023-12-22-00-18-37-47_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://github.com/SaitoTech/saito-lite-rust/assets/2867779/0a923c4e-2131-40e2-89ed-bf5c58c8207f)

We now have scrollbars everywhere in mobile. Please fix.

**Comment by f8daniel** [comment]
Not seeing scrollbars on prod or staging or local, firefox or chrome.

**Comment by f8daniel** [comment]
Just change overflow-y: scroll to auto for .tweet-text.full in
saito-tweet.css
