### ISSUE TITLE
Change Pace Settings so it doesn't seem like the website is always crashing

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#2250]
It takes so long for the Pace: loading scroll bar to go away, I connect, I download all the scripts, we run the script, we run onPeerServiceUp, I download and render new RS content, and it still doesn't clear... 

What is broken? Why does it take so long to clear? Also, every time you navigate around Redsquare, it retriggers the load, which is very bad UX

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/9808fb91-c112-4b4a-b538-fa0b112eebf4)

**Comment by arpee** [comment]
I cannot replicate this in a variety of chrome and firefox browsers on machines here. Am asking others in the team to replicated.

**Comment by arpee** [comment]
Khan can you check if you can replicate on windows and linux? FF and Chrome

**Comment by umairkhannn** [comment]
I can replicate this issue on Firefox windows. 
Pace has "active" class which doesnt go away after all content has been downloaded.

![image](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/ea1823df-75fa-4e0a-80a7-d337caafbdcf)


No issues on chrome (windows & linux) and firefox(linux).

**Comment by umairkhannn** [comment]
Have to check if pace.js has a known bug for this.
if not  then remove "active" class after 30 secs.

**Comment by f8daniel** [comment]
jquery to the rescue (jk).
I guess browser.ts -> initialize -> set a 1 second timer with $(".pace-active").addClass(".pace-inactive").removeClass(".pace-active")
(If we are running initialize, it means we have loaded the saito.js and already checked for a version upgrade, so pace *should* be done)
