### ISSUE TITLE
Chat -  initiating a chat with a user from an existing group chat requires adding the user first.

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite-rust#2252]
- "There should be a simple message function in addition to the other capabilities when you click on their username"

** Do we want to allow people to have unencrypted DMs?

**Comment by arpee** [comment]
Also - do we want to have users be able to DM each other without first connecting and having that accepted?

**Comment by f8daniel** [comment]
It's one party consent to add an encrypted contact. Do we slow down the key exchange by requiring the other party to accept?
