### ISSUE TITLE
RS - Replying to post navigation issue

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite-rust#2257]
"often after replying to a post, it returns to the home, but with the post i was replying to missing - until i refresh by hitting the home button again"

**Comment by f8daniel** [comment]
I've not experienced this "problem"
Need someone to investigate how to replicate the issue.

**Comment by umairkhannn** [comment]
Was unable to reproduce this after testing on prod, staging and local.
The reply shows up under the post after posting reply.



![Image](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/c0939480-58eb-4654-a002-9ccd95ceea60)

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/76a9615d-ab92-49c7-a980-028d2cbad92c)
