### ISSUE TITLE
Attempting to encrypt communication with a node crashes the node.

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite-rust#2276]
Don't know why the user (dev) is trying to do this - but the following error occurs when an encrypt message is sent to a node:

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/2867779/a4fd4f8e-ccef-4f81-915c-ffcb49818663)

We should at least have this not permanently disable the node. (the error happens on every restart as the node tries to reprocess the attempt...)

**Comment by f8daniel** [comment]
encrypted communication with the server can work exclusively through public/private key pairs
