### ISSUE TITLE
Dancing Chat popups.

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite-rust#2278]
when clicking into a chat box the border flashes and the content in the box is berifly 'squeezed'

This effect is very confusing when the border is hard to observe.

the effect can be resolved by having the border on the chat popup at all times and changing its color on click.

**Comment by f8daniel** [comment]
![image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/e3374204-dfa8-4900-b54d-1462d47e1acf)

Invisible border is not a good solution

**Comment by f8daniel** [comment]
Do we really need an animation effect for a chat popup becoming "active", when active just means it has a slightly high z-index so it goes above other chat windws

**Comment by umairkhannn** [comment]
@f8daniel have you removed the border animation? I see a commit related to it merged in **staging** branch.
