### ISSUE TITLE
Remove #home from default page load.

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite-rust#2279]
Navigation should not be updated to `#home` without user interaction?

Do we have a double page load now?

We seem to load `saito.io/redsquare` and then load `saito.io/redsquare#home`

**Comment by f8daniel** [comment]
It only looks like a double load because Pace interprets the #-updates as a new page event
We have always used #home / #profile / #notifications as a URL-accessible navigation marker in Redsquare

**Comment by arpee** [comment]
This nicely removes the #home  on the default load - but changes the refresh behaviour. 

Previously - navigating to the home page only caused a refresh if you were already on the home page... otherwise it simply navigated to the home page without a refresh. (from notifications or profile...)

**Comment by umairkhannn** [comment]
Have updated the related PR. Removed the default #home while preserving the previous home page load functionality.
