### ISSUE TITLE
buttons have a slight irregularity

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite-rust#2293]
Is it just me, or does the saito shimmer effect chop off a few pixels from the left of the button?
When you hover it comes back, but you can see the asymmetry of the border-radius

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/99ec602d-ebb0-415a-a85d-55062c9d3a6e)

**Comment by arpee** [comment]
Fixed by changing `background-position` to `1% 1%` rather than `left top`

**Comment by f8daniel** [comment]
thanks!
