### ISSUE TITLE
MIXIN - Integrate new mixin Safe api

### ISSUE THREAD

**Issue by umairkhannn** [SaitoTech/saito-lite-rust#2294]
CONTEXT:
So we updated the mixin sdk to latest version 3.1.16 and tested (on local) with prod keys.
After activating TRX, from saito header, the trx destination is prefixed with "NOTSUPPORTEDANYMORE.." inside **/asset/{assset_id}** api.

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/458fd236-62c4-4cd8-bde8-52ddfa30bd09)

Richard connected me with Mixin support team, where they told us to use the new "safe api" (https://developers.mixin.one/docs/api/safe-apis)

I tested the new safe api by replacing old **/asset/{assset_id}** with new "Get UTXO list" api. But it was failing.

Turns out all users registered with old "/user/" api needs to be registered with new "/safe/users" api else they wont be able to send, receive, fetch balance, fetch history etc.

So need to update following methods inside **mixin.js** with new **safe api**:

**checkBalance(),
createAccount(), 
sendWithdrawalRequest(), 
createWithdrawalAddress(). 
doesWithdrawalAddressExist(), 
fetchSnapshots()
fetchDeposits()**

**Comment by umairkhannn** [comment]
New mixin safe apis have been integrated via node sdk of mixin. Currently deployed to test network for testing.
Branch: mixin/node-sdk

**Comment by f8daniel** [comment]
fetchDeposits() is not a function? See error in issue #2329
