### ISSUE TITLE
Crypto: integrate QR scanner into transfer (withdrawal) overlay

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#2330]
Probably just a little icon right justified in the receiving address input, so I can hold up my phone with a qr code on it.

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/7d56b6ac-b4ab-4119-baf1-ed2225444232)

**Comment by umairkhannn** [comment]
QR scanner added:

![Screenshot from 2024-02-15 04-31-56](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/9b93b54b-a11c-440d-9090-15a99a82c2ae)
