### ISSUE TITLE
Crypto Withdrawal Overlay

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#2333]
Some behavioral quirks need fixing.

If I open through User-Menu, it auto populates the key. Good. 

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/97744058-4397-4e54-8a9f-6cc57a39b079)

- [x] But now, I don't need the scanner icon since the key is already there. [   render(publicKey) vs render()  ]
- [x] If I select a different crypto, the key remains the same.... we need a look up mechanism and auto change the receiving address (and/or add a second thing saying that xxxx is the TRX address for saito key XXXX)

If I close the withdrawal overlay and then click Send from the hamburger menu, I get the same autopopulated field. 

- [x] Change overlay to remove itself on close (not just hide)

**Comment by umairkhannn** [comment]
Issues fixed in branch mixin/node-sdk, deployed changes to test network.

For point 2 I am emptying the address input for now, will have to check how to check and fetch address of selected crypto asset from dropdown.

**Comment by f8daniel** [comment]
understood
