### ISSUE TITLE
Crypto Math

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#2334]
![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/2ad717c0-f1eb-4bf0-a261-cb0cf06326df)

We are seeing JS float operation overflows...

**Comment by umairkhannn** [comment]
Fixed in branch mixin/node-sdk, deployed changes to test network.

**Comment by f8daniel** [comment]
looks good
