### ISSUE TITLE
Web3 Overlay improvements

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#2352]
- [x] sendPayment overlay attempts DOM manipulation after it is closed. Should (a) blockClose() or (b) add some sanity checks before attempting to set innerHTML

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/87f254ba-c739-42a6-9221-4a6a586df344)

- [x] Simplify gameCryptoTransferManager receivePayment overlay. No need to show my key since it is a "Waiting for Payment" overlay. 

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/906714a3-54a0-4f46-a4ad-958e899d6a6c)

- [x] Why do we have a cursor: pointer on the individual lines of the transaction history? Clicking doesn't do anything, though maybe it should? Like open up a smaller overlay with the transaction details...

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/089abab9-7783-4612-8fc2-5b4005200fec)

**Comment by umairkhannn** [comment]
1. removed close btn from receive overlay and added check for element before setting innerHTML
2. "to" removed from receive overlay.

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/11512b96-60d6-4ece-8823-ee78aad9c225)

3. Removed cursor points for now, in future we can enable click by to check for txn status.

Latest changes are in branch: **node_changes_merge**

**Comment by umairkhannn** [comment]
Re-added close btn to in-game receive overlay, in-case if payment doesnt go through the game doesnt get stuck on receive payment overlay.

![Screenshot from 2024-02-27 05-43-57](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/e15a05ef-d606-4d2b-bc81-6e8ba414eab6)
