### ISSUE TITLE
Create a 'Disburse app' module.

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite-rust#2357]
We need a way to distribute main-net tokens to multiple addresses (for rewards, etc.)

Create a module with a simple ui to enter a tab delimited list of saito addresses and amounts.

When the user pastes a list in the ui show:

 - an error if the input does not parse
 - a count of the unique addresses and total to send if the input parses

If the input parses - and the wallet balance is larger than the amount to send:

A 'send' button activates -> onclick it creates a transactions that sends the sums to the addresses.

**Comment by estapeluo** [comment]
https://github.com/SaitoTech/saito-lite-rust/commit/65ba63fe441a9eb7d459d01b90d169f1ec82e46a
