### ISSUE TITLE
Settings button in the sidebar shows a 404

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite-rust#240]
Clicking the Settings button from the sidebar sends you to https://saito.io/wallet/#page=email_appspace&subpage=Settings, which shows a 404. 
You can still access Settings by going to https://saito.io/dev/#email-nav-Settings.
![image](https://user-images.githubusercontent.com/54612963/155181415-b9c4db21-f308-440c-8f72-39aafb15b118.png)

**Comment by karlsaito** [comment]
already fixed on the latest production
