### ISSUE TITLE
Poker interface is distorted

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#241]
The interface on poker is distorted to the point is nearly unusable on chrome and opera.
![image](https://user-images.githubusercontent.com/61957527/155182855-d961b9c9-cf12-418d-8995-e23fe6fed5eb.png)

- Device Used: PC
 - OS: win10
 - Browser Chrome and Opera.
 - Version chrome Version 98.0.4758.102 opera

**Comment by Tuch-o** [comment]
This was happening to me as well until I updated to the latest JS. Working fine now on Chrome 98.0.4758.102 and Firefox 97.0
![image](https://user-images.githubusercontent.com/54612963/155244504-edaa9511-2e03-47f3-ae11-47c06dce998e.png)

**Comment by trevelyan** [comment]
The issue should be outdated stylesheets that are cached in browsers.

Other applications also have this issue, but it does go away when the latest JS is downloaded.

Appropriate response is to leave a comment in the poker forum reminding people to refresh their cached javascript if they have this issue.
