### ISSUE TITLE
Chess log wipes itself if the player reloads the page 

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite-rust#243]
Log shows every move correctly until the player reloads, then it doesn't show any of the previous moves by either player.

Before
![image](https://user-images.githubusercontent.com/54612963/155245386-007a1779-fefc-4595-8566-977bbb3dbb84.png)
After
![image](https://user-images.githubusercontent.com/54612963/155246375-0d0bca17-51ba-40ae-83ee-d355b58365f9.png)

Steps -
1. Make a few moves.
2. Refresh the page.

**Comment by karlsaito** [comment]
@Tuch-o , can you retest if this occurs. if not, close the issue and update the github board. thank you. else, comment that it still persist

**Comment by Tuch-o** [comment]
Move history is now restricted to the sidebar log and refreshing doesn't wipe it so this doesn't happen anymore. Will close.
![image](https://user-images.githubusercontent.com/54612963/171068824-8ef090a2-877e-4875-b738-671de048a942.png)
