### ISSUE TITLE
Gif submission not working in chat.

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite-rust#2473]
![Image](https://github.com/SaitoTech/saito-lite-rust/assets/2867779/e015b3eb-4e0b-4d00-98bd-d86effe14b52)

In a chat - click on the 'emoji' in chat, select gif and select a gif from the options.

Nothing happens - the above error is shown in the terminal

**Comment by f8daniel** [comment]
Also shows up as: 

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/038baff4-6002-43b3-a327-99877b01dd1d)
