### ISSUE TITLE
Filesharing Issues

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#2497]
File Transporter issues.
 - minimise then maximise leaves the bottom portion of the dialog hidden below the bottom of the screen.
 - moving the dialog to the middle of the screen again then minimising leaves the minimised dialog in the middle of the screen
 - 'Download' button should be 'Save'?
 - successfully sent one file (but don't download)- ui breaks with buttons unresponsive trying to send a second
	 - both for sender and recipient

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/2867779/ac83b275-d101-47b4-b257-41a21385b222)

Sender dialog in unresponsive state with artefact download indicator behind dialog.

 - How hard would it be to enable multiple files to transfer? (later feature release?)

**Comment by f8daniel** [comment]
- the first two are just me stupidly using "removeAttr" instead of "removeAttribute" without sufficient testing... fixed!
- not sure about save vs download --- it does go into your downloads folder
- really don't want to worry about multiple downloads (from A to B) or (from A to B and C to B) etc, can be a future release

**Comment by arpee** [comment]
Cool.

On "Download" (no download folder for me) that is firefox on windows default behaviour but by no means standard/universal, but more importantly it's already transferred to my device, no? So it's confusing to now feel like I need to start the download - didn't I already do that?
