### ISSUE TITLE
HIS 2P: Protestant player cannot remove unrest from Catholic spaces

### ISSUE THREAD

**Issue by JoelCFC25** [SaitoTech/saito-lite-rust#2545]
https://github.com/SaitoTech/saito-lite-rust/blob/30893ceef7b507bb804fa1e81e763d7d1810055b/mods/his/src/his-player.js#L6040

I wonder if the checks in this function are reading the Control & Unrest portion of the 2P rules as wholly replacing the standard rules for removing unrest. They should not--they're _additive to_ the standard game rules in 12.4. Item `b` in the Removing Unrest section is still valid in the 2P game.

So this portion of the code seems to explain why I couldn't remove unrest as the Protestant from a Catholic space pre-Schmalkaldic League after having used Carlstadt and failed a Reformation attempt (putting a space into unrest). When trying the Remove Unrest action subsequently, I had no list to pick from, despite there being an eligible space.

**Comment by trevelyan** [comment]
Joel,

Thank you for this. Will look into this and try to get it patched later
today.

FYI -- response and combat cards are unreliable but we're at the stage
where we're trying to get the full game playable for everything else.

I think we are not too far away. Feedback like this is really helpful.

Best,

--david

**Comment by JoelCFC25** [comment]
It's been quite a few years since I was using Github regularly on the jinteki.net Netrunner project, or I'd just have given you a PR. I did note a couple other errors in the 2P setup, I'll put in a separate issue for those.
