### ISSUE TITLE
HIS 2P setup errors

### ISSUE THREAD

**Issue by JoelCFC25** [SaitoTech/saito-lite-rust#2548]
https://github.com/SaitoTech/saito-lite-rust/blob/7040f67480d50771176d35e6d1b05869da340186/mods/his/src/his-setup.js#L95

Here are the errors in the 2P setup: 

* Metz should have 1 independent regular, not 2
* Naples should have 1 Hapsburg squadron, not 2
* Antwerp should have 1 Hapsburg regular, not 3
* Pressburg, Agram, Mohacs, and Szegedin should all start with Ottoman hex control markers
* There should be no At War markers at all in the diplomatic display--only the Hapsburg-HB alliance.

**Comment by trevelyan** [comment]
yes -- it's all in his-setup.js

updated the file with the fixes.

thank you Joel

<img width="1336" alt="Screenshot 2567-08-08 at 12 39 11" src="https://github.com/user-attachments/assets/d10a8eda-e77d-4748-bcfb-ad0547d5fdff">
