### ISSUE TITLE
HIS excommunication effects

### ISSUE THREAD

**Issue by JoelCFC25** [SaitoTech/saito-lite-rust#2549]
https://github.com/SaitoTech/saito-lite-rust/blob/7040f67480d50771176d35e6d1b05869da340186/mods/his/src/his-state.js#L1066

A missed effect of Papal excommunication of a Protestant reformer--the associated debater token gets committed in addition to being temporarily removed from the pool. 

Reproduction steps: 

1. Papacy plays _Papal Bull_ to excommunicate Luther on Turn 1. Choose to initiate a debate.
2. Pick whichever pool to target, uncommitted or committed, doesn't matter.
3. Protestant plays _Here I Stand_ to swap in Luther. 
4. They subsequently roll 6 dice, which is wrong (1 too many, Luther should have been committed in Step 1--the right number of dice is now 5)

I also belatedly noted that the play of the _Here I Stand_ event in this case did not yield a card drawn by the Protestant player.

**Comment by trevelyan** [comment]
got it -- including extra card draw -- thx

<img width="1223" alt="Screenshot 2567-08-08 at 13 40 12" src="https://github.com/user-attachments/assets/5ec7395c-7c1d-4e04-8657-ecbf04e67ac1">


<img width="1213" alt="Screenshot 2567-08-08 at 13 40 01" src="https://github.com/user-attachments/assets/75e4e1bf-98e2-4395-8859-107b7c1b99e6">

**Comment by trevelyan** [comment]
![Uploading Screenshot 2567-08-08 at 13.40.01.png…]()
