### ISSUE TITLE
HIS 2P: remove major power At War markers in setup

### ISSUE THREAD

**Issue by JoelCFC25** [SaitoTech/saito-lite-rust#2563]
https://github.com/SaitoTech/saito-lite-rust/blob/ae132c6f162e1aaca77e13cb76879af9bf5874a7/mods/his/src/his-setup.js#L72

I surmise that this line is presenting an issue for Papal play at the outset of the 2P game. After 95 Theses and Diet have resolved and the Papacy is up to spring deploy, have them move a regular from Rome to Ravenna. Then on the first action round, spend a card for CP and attempt to move or control Modena. The "Control - 1 op" choice is missing from the menu of available actions--it should be permissible here for Papal units in Ravenna to take political control of Modena without being present in the space (no enemies are adjacent). It should also be possible to simply move from Ravenna to Modena, but if you choose the "Move - 1 op" action here, no spaces are eligible to select as the destination, all you get is an empty prompt with the "Acknowledge" button. I think the erroneous presence of the At War state between France-Papacy is interfering, though I don't know the code well enough to spot where/how. 

By comparison, after 95 Theses/Diet, have the Papacy opt not to spring deploy at all. In this case, when spending CP on the first card play, the option to take political control of Siena is correctly presented and works. Similarly, moving into Siena is allowed.

**Comment by trevelyan** [comment]
Yes, that's it 100%.

Odd, because I remember having to add that and being surprised.

Thanks Joel.
