### ISSUE TITLE
Scheduled call feedback.

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite-rust#2586]
![Image](https://github.com/user-attachments/assets/d7c6feb2-d851-4d8a-812b-6b61b24def70)

The user should not see a 'join meeting' option unless there is a meeting to be joined.

---

![Image](https://github.com/user-attachments/assets/96043547-2e7f-4a57-a87c-a2e68e389d54)

The full value should be visible in the drop down.

---

![Image](https://github.com/user-attachments/assets/46f50ebd-627e-43d1-8293-f3182b87f878)

This should not be a button until it is active (just add the `button-primary` class to the div).

---

![Image](https://github.com/user-attachments/assets/50f08a41-1666-4b45-9376-c2a2e6720a0b)

We should add a method to go to redsquare from here.

---

Once a call link has been followed the call detail should be stored in the users options and show in the calendar.

ref @f8daniel on integrating with the schedule module.

**Comment by arpee** [comment]
![Image](https://github.com/user-attachments/assets/48f2e25b-67c1-48b8-bae2-c49978913c27)

Any chance we can make this theme compliant?

All else seems solid now.

**Comment by f8daniel** [comment]
This shouldn't be mandatory

![Image](https://github.com/user-attachments/assets/56fa72bf-896c-4310-b8fe-ba811c3cad07)

**Comment by f8daniel** [comment]
Calendar integration. 
I create a meeting I should see it in my calendar

1. we need a visible icon or symbol on the main calendar that there is an event on that day
2. The overlay when you click on a day needs a total UI redesign



![Image](https://github.com/user-attachments/assets/55d1ff0c-8364-435b-88ed-23395871eb49)
