### ISSUE TITLE
[Settlers] Illegible text trading with the bank

### ISSUE THREAD

**Issue by Darkuso** [SaitoTech/saito-lite-rust#265]
White background with white/greyish text while trying to trade with the bank.

OS: win10
Browser: Chrome Version 98.0.4758.102 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/9855617/156421597-46d5fa9c-911e-4471-8b6f-e46c8fdc5bc9.png)

**Comment by f8daniel** [comment]
Solid logic in place to prevent ever running into that issue again, but changed the warning message anyways so that it will be legible.
