### ISSUE TITLE
Private chat logs lost on refreshing/navigating browser

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#286]
Private chat logs lost on refreshing/navigating browser. logs are not saved

Expectations: conversations should be saved

**Comment by umairkhannn** [comment]
Changes merged in staging branch.

**Comment by The1Duke** [comment]
This still needs to be fixed. @umairkhannn

**Comment by umairkhannn** [comment]
@The1Duke during the take live of this fix I had mentioned that this fix will affect only those games/modules where "chat-render-request" is called. For showing private chats on refresh "chat-render-request" needs to be added in all games/modukes where its missing.
@karlsaito 

![image](https://user-images.githubusercontent.com/104337801/178695143-de7ec2ef-9f57-461f-b242-575a0435e8ac.png)
