### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#29]
![temp](https://user-images.githubusercontent.com/70703104/144476709-8cb364dd-c1de-4a0b-ac23-0709b9f98e2f.png)

Is anyone else getting this error? It prevents me from launching a game

**Comment by arpee** [comment]
I believe this has been fixed - are you still experiencing?

**Comment by f8daniel** [comment]
I bet it is an issue of switching between saito-lite and saito-lite-rust. When I gave up on rust and went back to saito-lite, I had to reset the wallets 4 or 5 times to get it to work again.

Nevertheless, there is a bug in there because one browser hits this error and cancels the game, but the other browser thinks the game is still on. Wherever the code for "aborting game acceptance" is, it also needs to send a message about the abort.
