### ISSUE TITLE
Wordblocks lets you play a word thats already on the field

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#295]
If you click on a part of a word and type the letter you clicked on, or type the word from the beginning, or type a few letters of the word, or type a word that is found inside the same word, it will give you points.

![image](https://user-images.githubusercontent.com/61713323/158504521-5a0864c8-8f54-4a14-9dae-9fb3b719eb8f.png)
![image](https://user-images.githubusercontent.com/61713323/158504570-516e3235-26fd-4f51-bfda-9e808a844e4b.png)
![image](https://user-images.githubusercontent.com/61713323/158504583-cd9fc1a9-0e38-4dee-84fa-53636e7c9c9f.png)

In this case typing the word fate will award the points again, but if you try to click on the A and type Ate, it will award the points for "FATE". Typing "FA" by clicking on the F in Fate or typing "TE" by clicking on the T will also award the points for it. Clicking on any letter of any word and just typing the letter that was clicked, even if the player does not have said letter in their hand will also count the points.

**Comment by f8daniel** [comment]
Beautiful, this is a bug I would never have caught!
