### ISSUE TITLE
Solitrio games not showing up in the arcade.

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#296]
When choosing to exit the game from the menu, you don't see the solitrio game you just left on the arcade's lobby.
The saving function does work properly however, since hitting back on the browser will take you to the game you just left
Device: PC
OS: Win10
Browser: Chrome
Version:  99.0.4844.51

**Comment by estapeluo** [comment]
It's fixed on Staging branch.
