### ISSUE TITLE
Arcade- As a user and game creator, I should be able to share my game to my other social media accounts so that I can invite my friends to join the game

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#308]
Basic Acceptance Criteria

**Basic Steps**
Given that the **user have created a game** and I'm in the arcade lobby
When the user clicks the **INVITE button**
Then **a "share game invite modal" should appear which contains the following widgets**:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/96273856/160079654-0a6aa668-55c7-4aeb-8e8c-bc4c35d31201.png">

**Scenario 1:** Copy URL on clipboard  Widget
Basic Steps
And
When the user **clicks the copy from clipboard icon**, **URL of the game should have been copied to his clipboard**

**Scenario 2:** Post in Twitter
Basic Steps
And
When the user **clicks the twitter icon**
Then he should be redirected to Twitter AND the tweeting functionality should be triggered with the game card (attached URL)

**Scenario 3:** Post in Facebook
Basic Steps
And
When the user **clicks the facebook icon**
Then he should be redirected to FacebookAND the Write Post should be triggered with the game card (attached URL)

**Scenario 3:** Post in Telegram
Basic Steps
And
When the user **clicks the Telegram icon**
Then he should be able to forward the URL as a message to his contacts in Telegram
Reference: https://core.telegram.org/widgets/share#:~:text=A%20Telegram%20Sharing%20Button%20is,your%20link%20will%20be%20shared.

**Scenario 4:** Post in Discord
Basic Steps
And
When the user **clicks the Discord icon**
Then he should be able to forward the URL as a message to his contacts in Discord

**Accepting the URL of the inviter**
Given that URL was sent to the user and a new user of Saito Arcade
When the user clicks the URL for a game 
Then he should be redirected to the arcade and automatically join the game 

**Requirements**:
1. The invite button will only be visible to the creator

**Comment by f8daniel** [comment]
I think we ultimately decided against the utility of posting links to social media platforms where the user may still have to wait 10+ minutes for a friend, and it spams up the social media site with broken links (after the game has been accepted).
