### ISSUE TITLE
Usernames are displayed inconsistently

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#316]
The issue can be replicated as followed in Staging.

_User A_ and _User B_ connect to https://staging.saito.io/arcade/

_User A_:
1.  Open Arcade
2. Click Anonymous Account
3. Registry Modal will appear
4. Type ID name in the input section
5. Click Register username
6. A notification will appear
7. Saito Email should appear on the top right section, beside the side bar button 
8. _User A_ add a message

Expected result: Both _User A_ and _User B_ should see A's registered name in the chatbox with the message.

Now _User C_ connect to https://staging.saito.io/arcade/ 
_User A_: 
1. _User A_ add a message 

**[Fails]** Expected result: _User C_ should see A's registered name in the chatbox with the message.

The image shown next shows _User A_ and _User B_ chat box, B' was present during A's registry; _User C_ joined **After** and was present during B's registry.  _User A_ and _User B_ have each other registry, while _User C_ only have B's

![image](https://user-images.githubusercontent.com/59634305/161613868-d1ed3420-726d-47a3-9cff-c9dc02a752f1.png)

**Comment by trevelyan** [comment]
This bug report is not helpful. 

We need to know how to replicate the problem in order to task it out productively.

Expectation should be that those reporting the bug are capable of basic debugging. Is the DNS server up? Was the username properly registered? etc. etc. Were some users notified of the new username and others not, etc. etc. Did the new username show up on reload? Is the user already in the wallet keychain? etc. etc.

A screenshot showing the problem would also be helpful in these sorts of situations.

**Comment by The1Duke** [comment]
I agree, which is why I hadn't reported this before, I opened the issue following Karl's instructions.

**Comment by The1Duke** [comment]
Also, none of those factors seem to have any bearing on whether they display or not, which again, is why I didn't want to report this under the current circumstances.

**Comment by estapeluo** [comment]
The issue can be replicated as followed in Staging.

_User A_ and _User B_ connect to https://staging.saito.io/arcade/

_User A_:
1.  Open Arcade
2. Click Anonymous Account
3. Registry Modal will appear
4. Type ID name in the input section
5. Click Register username
6. A notification will appear
7. Saito Email should appear on the top right section, beside the side bar button 
8. _User A_ add a message

Expected result: Both _User A_ and _User B_ should see A's registered name in the chatbox with the message.

Now _User C_ connect to https://staging.saito.io/arcade/ 
_User A_: 
1. _User A_ add a message 

Expected result: _User C_ should see A's registered name in the chatbox with the message. **{Fails}**

The image shown next shows _User A_ and _User B_ chat box, B' was present during A's registry; _User C_ joined **After** and was present during B's registry.  _User A_ and _User B_ have each other registry, while _User C_ only have B's

![image](https://user-images.githubusercontent.com/59634305/161613868-d1ed3420-726d-47a3-9cff-c9dc02a752f1.png)

**Comment by arpee** [comment]
@estapeluo - can you validate this on production. There will be issues with persistance (due to the records being deleted on prod) that have been rectified. It would be good to separate out any issues stemming from that, vs, the 'actual bug'.

Thanks.

**Comment by estapeluo** [comment]
Followed the steps above - issue* is present on Production.
[**HUNCH**] I assume it's not related to the module itself but how wallets share known keys registry with each other.

**Comment by karlsaito** [comment]
@trevelyan  could you help us fix the issue? the team is already occupied with the other issues raised.

**Comment by estapeluo** [comment]
@arpee @trevelyan 
Diving in code... and checked in production and local.

1. `keys` from the wallet get added **ONLY** when the browser is connected to the site (and all its peers)
2. `keys` doesn't receive a new update or key no add after: 
- new peers/wallets are connected to the site
- make a game on the arcade
- send a message on the chat

This was working before migrating to lite-rust and before the rework AFAIK.

**Comment by trevelyan** [comment]
done
