### ISSUE TITLE
Placing to the right of 10s in solitrio

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#317]
On Solitrio, you can't place on any of the spaces directly to the right of 10s, regardless of them being empty and not adjacent to them.
I'm not sure if this intended or part of the rules, but the game would be much more easier if this was changed so that you can place on the second (and subsequent) empty spot to the right of 10, as marked with the badly drown blue circle on the attached screenshot.
As an option not to swing too hard the other way, making it so that you can only place 2s on such spaces would probably be a good idea.
![image](https://user-images.githubusercontent.com/61957527/160045285-cb1c7c3c-5a32-4cb9-808d-3941c3d2bc58.png)

**Comment by trevelyan** [comment]
This is the game!

**Comment by trevelyan** [comment]
Yeah, this is the hard thing about the game Duke. :D
