### ISSUE TITLE
Wordblocks UI updates break game flow

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#320]
Problem: Users play a few words. Player 1 leaves game during Player 2's turn. Player 1 returns to game to see new word but game out of sync. Each player thinks it is the others turn.

![image](https://user-images.githubusercontent.com/70703104/160350578-788a6abd-e390-4071-81f6-e0da14820300.png)

Note: need to separate game logic from UI updates (DOM writing), this.browser_active is a way to tell whether the module has control of the module.

(This is an enhancement prerequisite because it will better enable async playing of the game)

**Comment by davikstone2** [comment]
## Notes:
Game tested with @trevelyan , bug could not be replicated.

![Screenshot 2022-03-29 at 10 19 55](https://user-images.githubusercontent.com/102211421/160582871-fc7b281b-84cd-4f8f-ba6a-0b07ea591baf.png)

**Comment by davikstone2** [comment]
### Notes:
Issue could not be replicated.
