### ISSUE TITLE
As a user, I should be able to start another round of game with the other existing players without exiting the game room 

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#328]
Requirement

- Rematch button should be available every end of the game in the menu

Acceptance criteria

Use Case 1 - Chess

Given that the chess game has ended
When a player clicks the menu And the player click the rematch button
Then the game should restart and prompt both users "rematch has been initiated, white to move"

**Comment by trevelyan** [comment]
Is this feedback from a specific user? And specifically with Chess (or which game)?

Asking as I'm not sure if this is something that is really needed?

If someone has completed a game and understands how the Arcade works, is it better to keep them on the game interface or ask them to leave and create a new game? The game creation functionality is all linked to the arcade anyway. So this adds complexity without providing much value.
