### ISSUE TITLE
Web - Twilight Struggle - Cannot remove Cuban Missile Crisis 

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#339]
When clicking on the option to remove "Cuban Missile Crisis" as the US (not tested as the USSR), there is an error in the console and nothing happens.

![image](https://user-images.githubusercontent.com/61713323/161400159-76237fc7-4560-4c2d-a693-617a3bad9e86.png)

Additionally when using a card for ops and choosing the 4th option (Place Influence/Coup/Realign/_**Remove Cuban Missile Crisis**_), clicking on either West Germany or Turkey as the US does nothing, and no message shows up in the console either. No tests of this as the USSR

The only way to remove Cuban Missile Crisis as the US is by placing influence in West Germany or Turkey and choosing the prompt of removing influence from them as you place, However when doing this on Turkey, there is an issue with the influence not being removed properly

![image](https://user-images.githubusercontent.com/61713323/161400261-033c503b-f7c2-4e58-ab80-dfc825efa8d3.png)
![image](https://user-images.githubusercontent.com/61713323/161400263-c0b7dc00-6309-4838-a6f0-722ee1c4899f.png)
![image](https://user-images.githubusercontent.com/61713323/161400267-ad035787-870c-4f0b-adc9-f15a4672d50b.png)

It should be 0 influence in the last screenshot.

**Comment by trevelyan** [comment]
This is a well-documented bug.
