### ISSUE TITLE
Twilight Struggle - Aldrich Ames Remix does not display the US cards on the log

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#342]
When using Aldrich Ames Remix, the cards are shown to the USSR in order to select a card to discard, but after selecting the card, there is no record of what cards the US has. This was believed to have been fixed by adding the US hand to the log in the same way as CIA Created or Lone Gunman, but as of this report, there is nothing in the log to show the US hand.

![image](https://user-images.githubusercontent.com/61713323/161400549-ea23a928-adb5-4ce9-8a32-497e60633b6c.png)

This is important because the card states that "The US will play the remainder of the turn with their hands visible to the USSR", but due to technical limitations this is not something that has been implemented, instead showing the cards on the log is the more logical step

**Comment by trevelyan** [comment]
Yes, we should fix this.

It also means revealing any new cards picked up by the US that turn, which
means modifying Ask Not.

**Comment by trevelyan** [comment]
It isn't perfect, but it's fixed for now, and works with Ask Not as well.
