### ISSUE TITLE
Poker Improvements

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#346]
- [x]  Test: 3-6 players and player elimination 
- [ ] _Feature: Add side pot after 1 player has gone all in_ (this is going to be very difficult)
- [x] Fix: the settlements after each round
- [x] Fix: parameters so players cannot have blinds larger than stake
- [x] Fix: gameflow when player has gone all in
- [x] Enhance: add graphical elements

**Comment by karlsaito** [comment]
@f8daniel , kindly update the list of tasks. thanks.

**Comment by karlsaito** [comment]
@f8daniel , is this completed? can we close this now?

**Comment by f8daniel** [comment]
At some point in the future, it would be nice to add a side pot, but I really don't want to tackle it in the near term
