### ISSUE TITLE
Web - Blackjack - Dealer wins in a Tie

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#351]
### Tested in a 2 player game.

To replicate: 

>1) Play until RNG makes both (all) players have the same number
>2) Make sure both (all) players Stand on the same number  as to avoid going bust of having a different number  
>3) ??? 
>4) Dealer Profit

When both the dealer and the player(s) have the same hand, the game defaults the dealer as the winner and gives him the player(s) bet when in reality its a tie and the bet gets returned to the player(s). These are official rules, unless this implementation of blackjack works by house rules where the dealer wins such cases by default, in which case such a thing should be reflected in the log. 

![image](https://user-images.githubusercontent.com/61713323/161600723-29017809-5d78-41ee-a2b9-cd4313418049.png)

**Comment by f8daniel** [comment]
Read the game instructions.
Game works by house rules. Dealer wins ties
