### ISSUE TITLE
TS: Timer not working

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#352]
Steps:
1) Create TS invite and setting a timer from the advanced settings
2) Start Game
3) There no times being displayed, and game won't end upon the selected amount of time running out.
See:https://youtu.be/_D2dMK2JDvA

**Comment by trevelyan** [comment]
Just as a comment on this.

I do not think we should fix the timer AS IS, but rather treat this as something that needs to be upgraded.

As we don't really have objective time.

Believe that the Server should probably offer a timer module that integrates with the arcade and games optionally.

Exactly how to do this is an open design question.

**Comment by The1Duke** [comment]
Should I tag this as an enhancement?

**Comment by trevelyan** [comment]
fixed, will go live next push
