### ISSUE TITLE
Mobile version: Back to previous page, New Game and How to Play buttons don't work on Game-specific Forums in Mobile Browser

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#354]
Impacted:
All Game-specific forums

Test Steps:
1. Open the Arcade in Mobile browser e.g. Mobile Chrome
2. Click Blackjack Forum Discussion
3. Back to previous page, New Game and How to Play buttons are not working

Example buttons:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/96273856/161695384-29b12e3a-d1eb-4877-b273-1a827882544f.png">

Workaround: Desktop view

**Comment by The1Duke** [comment]
Retested and was able to replicate the issue.

**Comment by karlsaito** [comment]
@The1Duke  what's the update on the retest?

**Comment by The1Duke** [comment]
@karlsaito Issue is fixed.
