### ISSUE TITLE
RI: white text on white background on the console

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#358]
Steps:
1) Make RI game
2) Proceed with gameplay normally

There are several messages on the console that have this white background now. Examples include but are not limited too: Waiting information from peers, Player activates planet, choosing troops to invade a planet, and other messages where the player is required to chose from different options.
![image](https://user-images.githubusercontent.com/61957527/161890854-a631b56b-0e71-46bb-80a1-649bd3d2390a.png)

**Comment by f8daniel** [comment]
Please check that you force refresh (ctrl-shift-r) the latest css for the game
I'm not seeing the white on white
![image](https://user-images.githubusercontent.com/70703104/162136754-f2fea478-0d4d-4a20-94cf-4a35624a6aee.png)

**Comment by The1Duke** [comment]
@f8daniel I test using incognitos only to avoid the kind of problems you mentioned. Retested just now just in case it was somehow fixed on the last update and I still can replicate the issue on Firefox, Chrome and Opera.
see: 
![image](https://user-images.githubusercontent.com/61957527/162147789-492dc8c0-2ec8-4b6f-90bd-afb9bded7acf.png)

**Comment by f8daniel** [comment]
Yes, I couldn't replicate it on local, but I saw the problem and it is a single line of css to fix. It should propagate on the next cycle of system updates
