### ISSUE TITLE
Settlers - When using a card, your resources are hidden 

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#361]
When you use a card with an effect that you must choose a resource, or a player, your resources are hidden and there's no option to go back, which is bad design because you are not allowed to check which specific resources you have in order to select your target/resource accordingly.

![image](https://user-images.githubusercontent.com/61713323/161893397-bbde0de9-c25d-419f-9605-8576c2d91bd5.png)
![image](https://user-images.githubusercontent.com/61713323/161893565-8e254861-bcac-452a-8b06-c8426769443e.png)
![image](https://user-images.githubusercontent.com/61713323/161893416-273f197c-999d-4b97-aa3a-2eae3951d0c2.png)

The final image shows what happens when you use Unexpected Bounty for example, which has you choose free resources, however by that point you can no longer check which resources you previously had and there's no option to go back. 

Suggestions for this issue are:

> Separating the cards from the resources, rather than having them share the same area and switching between them, so that players can always see what cards and which resources they have and they don't overwrite each other since they share the same display.

> Adding an option to go back, which is probably necessary either way outside of this specific issue, since being able to go back on your move seems like something that feels necessary for players, unless there's some unspoken rule in Settlers where you cannot second guess any card after you have already played it.

> An addition to the UI with a simplified display of the player's current number of resources.

**Comment by trevelyan** [comment]
@Rammko -- isn't this something you can tackle?

**Comment by Rammko** [comment]
my VM is not operational atm, due to an issue with my HDDs, so atm i cannot deal with code, even if i knew anything about the new style of coding being used, or if i knew anything about Settlers code, especially diplay stuff like this

**Comment by f8daniel** [comment]
I looked at the possibility of adding a "go back" option for the dev cards, but it does not appear to be a practical enhancement. At some point a player has to commit to their moves and giving them unlimited opportunities to go back or adding popups to confirm their moves adds complexity to the game play without contributing any meaningful value. 

Previous iterations of the UI attempted to show resource and dev cards concurrently. It was rejected for cramming too much on the screen at once. 

Fix: when players choose unexpected bounty/monopoly, the game switches back over to showing the resource cards as they make their decision about which resource(s) they want.
