### ISSUE TITLE
Settlers - Cannot see specific opponent resources (Unsure as to wether it is a bug or a rule of the game)

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#362]
When playing Settlers, you cannot see the other player's resources only total resources in hand, not sure if this is a bug or a feature however. If it is in fact a regular rule in Settlers that players are now allowed to know which specific resources other players have, then discard this issue. If however you are allowed to see what specific resources other players have, then that is something missing from the current version.

I did research on the fact and what i could find was indecisive on whether this is a rule or not, and some sources claim that this falls under House Rules category. If this is the case then a suggestion would be an option on game create that would allow players to select to play with the option to see specific resources or not, therefore giving the choice to the player on how they wish to play in regards to this.

**Comment by f8daniel** [comment]
IRL, unless you are counting cards (which is super easy with the in-game log), you are only seeing the back of the opponents hand, but you can know how many cards they are holding.
