### ISSUE TITLE
Mobile Test Plan - Registry Module (Anonymous Account disappear on cellphone's aspect ratio.)

### ISSUE THREAD

**Issue by estapeluo** [SaitoTech/saito-lite-rust#363]
Module: Registry
Mobile test done with:
iPhone 12 Pro, 390x844 viewport
Galaxy S20 Ultra, 412x915 viewport

Test steps:
1. Open Arcade
2. Click Anonymous Account
3. Registry Modal will appear
4. Type ID name in the input section
5. Click Register username

Expected result:
Saito Email should appear on the top right section, beside the side bar button.

Issue:
Anonymous Account disappear on cellphone's aspect ratio.

Workaround:
Register via dev/wallet settings.

Workaround Steps:
1. Open arcade
2. Click hamburger Menu
3. Click Settings or Dev Center
4. Click wallet settings
5. Click register a username
6. Input desired username

Workaround issues:
Registry modal doesn't re-size and its too big the input.

Image shows on the left the /arcade and on the right the dev/settings
![image](https://user-images.githubusercontent.com/59634305/161899586-efb31ee8-41d6-4c2e-a13f-eeb8da756510.png)

**Comment by karlsaito** [comment]
Moved to major as this is a major functionality for registry module
