### ISSUE TITLE
Arcade - Typo on Settler's how to play

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#369]
Steps:
1) Go to settlers subforum
2) click on how to play

![image](https://user-images.githubusercontent.com/61957527/162116872-8160c1cf-8588-463f-84c6-4079e6fd0404.png)

**Comment by f8daniel** [comment]
Which word is misspelled?

**Comment by The1Duke** [comment]
@f8daniel Saito. It says settlers of saitoA. Everywhere else I've seen it, it says settles of saito.
