### ISSUE TITLE
Community Chat Not Reopening While Inside a Game

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#383]
After closing the community chat while inside a game of Poker, I cannot reopen it anymore. 
This is a recurring issue. The workaround would be to refresh the page but it could cause a connection problem to the game.

**Comment by Darkuso** [comment]
There is another workaround for this problem too, Click: Game > Exit, in the arcade, click to rejoin the game.

**Comment by trevelyan** [comment]
I'll tackle this.

**Comment by f8daniel** [comment]
Group chat in games also is broken, with a error in the console "Uncaught Invalid Address"
