### ISSUE TITLE
Errors in Node Console Output

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite-rust#405]
Prod main node logs are jammed with:

```
23|npm run dev  | error in urlparams: ReferenceError: window is not defined
23|npm run dev  | error in urlparams: ReferenceError: window is not defined
```

This is non-fatal but does look bad, and clog up the logs. 

I am not sure if there is a simple way to locate where in the code this is happening.

Low Priority

**Comment by estapeluo** [comment]
`returnURLParameter(name)` in `browser.ts`, line 222

**Comment by trevelyan** [comment]
dropped that console log -- it's from the server trying to check URL parameters so safe to ignore. Will just report back there are none.
