### ISSUE TITLE
As a user, I should be able to disconnect and drop on the call anytime

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#412]
Use Case:
Given that I am in the call
When I click the “disconnect” button
Then I should be dropped from the video chat session

**Comment by davikstone2** [comment]
### Notes

Disconnect functionality added and pushed here 
https://github.com/SaitoTech/saito-lite-rust/tree/stun-development

**Comment by karlsaito** [comment]
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/96273856/166215072-f4f35e85-0cee-454d-ac06-596285d24038.png">

Reopening. Disconnecting leaves a black window on the UI/
