### ISSUE TITLE
As a developer, I should be able to call a function to the UI element (playerbox) to make it do something to attract attention from the player

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#417]
[] Add a function to Playerbox (following existing API conventions), which applies css changes to the playerbox that make it temporarily more salient
[] Insert css for one or more classes into web/lib/templates/game.css
[] explore possibility of using parameters to enable selection of shaking, flashing, or other attention calling effects
[] explore relative merits of using a timeout or an interval with a window event to remove the class

**Comment by davikstone2** [comment]
## Playerbox Updates 
- Added function   ``` alertNextPlayer```  in GamePlayerBox Class to alert the next player.
- Two alert options "flash" and "shake" are available, can be chosen by passing a parameter, defaults to "flash".
- Alerts are disabled automatically after 4 seconds by default, can be extended by passing a parameter. 
- Provision for disabling alert on next player mouse or input events is available, however it should be noted that browsers only respond to their own events, methods to listen to other players' events should be explored.

**Comment by karlsaito** [comment]
add the correct label of estimate @davikstone2
