### ISSUE TITLE
Chess - Miniature chess board

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#426]
Steps:
1) Join chess game
2) Notice the board being too small upon going inside the game
3) Either zoom in or zoom out (using ctrl++ or ctrl+-) to make board return to the correct size.
See: https://youtu.be/P2-CrKm2P_I
Edit:
4) Moving pieces changes the board size. It will become small again upon refresh.

**Comment by Kromtastic** [comment]
Tested. No longer an issue after Chess update.
