### ISSUE TITLE
`document.getElementById('email-nav-AppStore')` leads to 404

### ISSUE THREAD

**Issue by mattwilson888** [SaitoTech/saito-lite-rust#436]
The `/dev/` directory features three buttons:

The second button is a link to a *www* address for the Saito Wiki.

The first and second buttons are `onclick` events:

The first: `onclick="document.getElementById('email-nav-AppStore').click();"` when clicked on or manually inputted into the browser web console produces a `404 not found` error on the local machine *but not* on the website, while the `onclick="document.getElementById('email-nav-settings').click();"` works as expected in both domains clicked or through the console.

The url directory`localhost:12101/dev/#email-nav-AppStore` produces a `404` on the local node but `https://saito.io/dev/#email-nav-AppStore` works on the website.

**Comment by estapeluo** [comment]
add appstore to your module.config.js on /config 

Closing :}!
