### ISSUE TITLE
As a user, I should be able to copy my public key address through a copy icon in the side bar

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#439]
Acceptance Criteria:
Given that I am at the Arcade and I clicked the Sidebar
When I click the copy icon beside the username
Then the public address should be copied in my clipboard

**Comment by umairkhannn** [comment]
![Screenshot from 2022-05-02 06-51-32](https://user-images.githubusercontent.com/104337801/166182916-03b1cce9-4d21-4f1a-988f-e3ba84e233c0.png)
