### ISSUE TITLE
Settlers of Saitoa - Rules Mistake

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#447]
Steps to replicate:
1. Player One places a road on an edge where at the other end there is a village/city of an opponent
2. During Player One's next turn, he/she can place a road beyond the village/city of an opponent.
This shouldn't be allowed since an opponent piece is blocking the path.

If you build a new road, it must always connect to one of your roads, settlements, or cities.

https://www.catan.com/sites/prod/files/2022-01/strassen1_0.png

In the situation depicted above, the blue player would not be connecting his road piece to his road but to the red player's settlement, which the rule prohibits. Therefore, only the red player may continue to build behind the red settlement.

---------------------------------------------------------------------------------------------------------------

Roads shouldn't be allowed to be placed if there is an opponent village or city blocking the path.

"A player must connect a new road built to one of their existing roads, settlements, or cities. A player can only build one road on a path. A continuous road with at least five roads of the same color that are not intercepted by any opponent game pieces forms the longest road." 

"A player can build anywhere on a vacant spot, including intercepting another player’s road. However, once the player builds a settlement or city at the end of that road, another player cannot continue along the road to develop more. 

A player can build a settlement or a city at the center of another player’s chain of road. If that happens, the second player can build another road to connect a settlement on the other side.

Settlement intercepts another player’s road if it appears at the end of the road if that road is coming to an end on that point. However, if the interception is in the middle of a player’s road, a player can build on the road from the other ends."

**Comment by karlsaito** [comment]
Changing this to an enhancement since it's an unimplemented feature. @arpee  @f8daniel
