### ISSUE TITLE
Wallet missing functions?

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#46]
Is it just me or did the port to rust lose a few functions from wallet.js?
E.g. 
returnActivatedCryptos, returnPreferredCrypto, returnPreferredCryptoBalance

I see them in the source code of the old repository, but not this repository. However, they are still being called in:
email, arcade-main, arcade-game-details, gametemplate, saito-header

To replicate, navigate to Wallet or Settings from the hamburger menu.

**Comment by trevelyan** [comment]
Hey,

Yes -- it did.

We're going to have a better system, although it will work through those
functions when implemented.

Do you want to implement stubs?

**Comment by trevelyan** [comment]
These functions have now been implemented in the wallet. Closing.
