### ISSUE TITLE
RI: Victory message displays Player 1 as the winner, regardless of who actually won the game.

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#466]
Steps:
1) Play Red Imperium to completion
2) See victory message
See screenshot below, Muaat wins the game by reaching 8VP (not updated on the VP track), yet the victory message claims the galactic thread as the winner.
![image](https://user-images.githubusercontent.com/61957527/166239513-88414fa6-c583-4f8d-a3c0-f04dace09ab7.png)

**Comment by trevelyan** [comment]
Theoretically patched!
