### ISSUE TITLE
RI: VP track doesn't update upon reaching the necessary VP for victory.

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#467]
Steps:
1) Play RI
2) Acquire enough VP to win
3) It doesn't get updated on the VP track, you win regardless.

![image](https://user-images.githubusercontent.com/61957527/166239973-16756fc7-b903-4f91-aba4-16a6e54c5678.png)

**Comment by trevelyan** [comment]
Should be fixed in next patch.

Thanks Duke and Karl.
