### ISSUE TITLE
RI: Parts of the console goes out of its "outline", and sometimes off screen.

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#468]
Steps:
1) Play RI
2) get too a point where the console contents are long enough for it to need a sliding bar
3) The console goes out of its own outline
See:
![image](https://user-images.githubusercontent.com/61957527/166240422-2de61684-19db-4368-b9f6-aa9fb01aa79b.png)
![image](https://user-images.githubusercontent.com/61957527/166240596-1778d309-9807-4bcf-b2c3-eccfc4410a6d.png)

**Comment by trevelyan** [comment]
Sorted with CSS update, I believe.
