### ISSUE TITLE
WB: Not Accepting Submitted Word with Some Tiles

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#469]
1. Unable to submit the word "wire" on the right side of the board. The tiles that are in my hand are the letters 'w', 'i', and 'r'. Mu
Tried methods: 
     a. Click tiles then click board to place tiles.
     b. Click appropriate empty space, type the word "wire" or "wir", and then submit.
![Wire not being placed](https://user-images.githubusercontent.com/101871246/166242159-38035f6a-b5ee-4c49-afe5-b66c048c1866.png)
2. The tiles just return back to my hand.
3. I tried the word "wire" again but this time connecting it to a different 'e'. 
4. The word "wire" was submitted successfully.
![managed to do wire with another E](https://user-images.githubusercontent.com/101871246/166242207-85ef541f-31f8-4409-b408-9029fba092d4.png)
5. I also tried to form the word "do" and "or" by placing the letter 'o' as illustrated in the photo below.
6. I encountered the same problem as no. 1.
<img width="954" alt="Do Or not being accepted" src="https://user-images.githubusercontent.com/101871246/166242529-9d96c50d-84b3-4b22-9947-611e7058731f.png">

My suspicion is that there are certain tiles that are problematic.

**Comment by estapeluo** [comment]
losing as per #474, words on the right side edges nows accepts letters from both drag and type inputs.
