### ISSUE TITLE
Arcade invites still show when game finish or opponent resign.

### ISSUE THREAD

**Issue by estapeluo** [SaitoTech/saito-lite-rust#480]
**Test steps**

1. User A, B go to saito.io/arcade
2. User A make a game Poker public
3. User B join the game
(game starts)
4.1 User A go back to saito.io/arcade and cancel the game
 -or-
4.2 User A wins the game.

https://user-images.githubusercontent.com/59634305/166633770-4e00d761-ff70-48fb-8aaf-38d3f932e5b0.mp4

or in Settlers

https://user-images.githubusercontent.com/59634305/166634981-8647ca02-d536-4029-8d93-229272e03a01.mp4

**Comment by estapeluo** [comment]
@f8daniel

**Comment by estapeluo** [comment]
Arcade self-purge the game invites after X amount (30min?).

**Comment by f8daniel** [comment]
Thanks
There was also the issue that Player A creates an open invite, Player B joins. Player A&B play the game. Player C visits Arcade and still see's Player A's invite.

Fixes should already be live on staging.saito.io  @estapeluo

**Comment by estapeluo** [comment]
Closing as per above
