### ISSUE TITLE
Private Game is stuck at initialization

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#498]
Test Steps:
1. Create Settlers Private Game for 2 players
2. Send link to another player
3. Second player joins the game
4. Game starts to initialize
5. Stuck at initialization, and console throws an error after 1 minute and 30 seconds (from the onset of initialization)

<img width="824" alt="image" src="https://user-images.githubusercontent.com/96273856/167060958-ee80afcc-3632-46ac-8b1c-b0bb3e777752.png">

**Comment by estapeluo** [comment]
unable to replicate, is this a consistence issue?

**Comment by trevelyan** [comment]
seems fixed, no?
