### ISSUE TITLE
Withdraw Functionality is not working. Throws an error: type error: value must be a string

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#513]
Test Steps:
1. Go to Settings -> Mixin'
2. Click Withdraw Button
3. Add the address and the amount
4. Alert box appears on transaction fee, click OK
5. Amount is not deducted, console throws Error

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/96273856/167822281-3c59e331-07ef-4b77-a7bd-cdf01feda9c1.png">

**Comment by karlsaito** [comment]
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/96273856/168509554-d7d26746-2193-44cb-9d35-9d67de8977cf.png">
Issue found when doing the same test step with a total balance less than the network fee

Input used
Total balance in wallet 1.1 TRX
Coin to withdraw: 1 TRX
Network fee: 23 TRX

@umairkhannn

**Comment by karlsaito** [comment]
1. Try executing the same test steps as the original bug.
2. Console throws this information
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/96273856/168521338-481f6c8d-ca78-4270-a236-7c3602c1d6cd.png">
3. Wait for 30 mins, refresh the page, **nothing has been deducted on the original balance**

**Comment by karlsaito** [comment]
Issues has been fixed, this can be merged into staging @umairkhannn

**Comment by umairkhannn** [comment]
Changes merged into Staging

**Comment by trevelyan** [comment]
Fixed.
