### ISSUE TITLE
Convert Core (Jscript) to Typescript

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#52]
- [x] Block
- [x] Transaction
- [x] Slip

**Comment by escapedcat** [comment]
Good way to handle this for us was using it as one requirement for PR DoDs. Every file which is being touched for a PR needs to be switched to TS. Over time everyhting will be switched.

**Comment by SankaD** [comment]
Originally that was the plan. But there was a one file which was an access point for every file which caused the changes to flow towards most of the files. That's why the large change.
