### ISSUE TITLE
Rearchitecture of Video Module

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#525]
Subtasks:

- [x] Redesigned architecture (documentation) - small (sprint 5)
- [x] Separate Core and UI Modules
- [x] Test functionalities:

**Comment by karlsaito** [comment]
@umairkhannn please assign to yourself and check the tasks if they are applicable, else kindly edit this issue card

**Comment by umairkhannn** [comment]
@karlsaito two of the sub-tasks are done:
- Redesigned architecture
- Separate Core and UI Modules

**Test functionalities** is remaining.

**Comment by umairkhannn** [comment]
These issues should be handled separately as this ticket is for restructuring of STUN module:

https://github.com/SaitoTech/saito-lite-rust/issues/411
https://github.com/SaitoTech/saito-lite-rust/issues/414
https://github.com/SaitoTech/saito-lite-rust/issues/413
https://github.com/SaitoTech/saito-lite-rust/issues/325
