### ISSUE TITLE
Twilight struggle cards

### ISSUE THREAD

**Issue by Darkuso** [SaitoTech/saito-lite-rust#526]
There are currently two problems with the cards, first, mid and late-game cards are being drawn in early game, and even on turn one. 

![image](https://user-images.githubusercontent.com/9855617/168411486-c1bdf13f-1d38-41ca-be83-736dcca04b68.png)

The second problem is that even creating a new game or even using a different wallet, is getting the same cards
These two images are from 2 different games with a new wallet

![image](https://user-images.githubusercontent.com/9855617/168411530-1f8c1412-2de4-47a1-bc3a-612db7099730.png)

![image](https://user-images.githubusercontent.com/9855617/168411612-4b36afa7-da52-4dda-8a86-18db186099da.png)

**Comment by estapeluo** [comment]
Already pushed the commit https://github.com/SaitoTech/saito-lite-rust/commit/e33c1f1e31036b37a1cd0e9530ea66b5ed95e73c

**Comment by estapeluo** [comment]
Closing as per https://github.com/SaitoTech/saito-lite-rust/commit/3b09f1c3e308d3049c60eea4b143a1261834f0be
