### ISSUE TITLE
Arcade notification sounds

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#529]
Adding sound notifications to both chat, and game invites being taken, to make sure people on other tabs know when games are being taken as well as to keep them engaged in the conversations chat.
The ability to turn them off would great too.

**Comment by f8daniel** [comment]
There is a notification sound (a 4 note "song") that should play if and only if you are on another tab and your game enters the ready state in the Arcade. There are also visual notifications flashing in the tab to alert you when (a) the game is ready or (b) game moves have arrived
