### ISSUE TITLE
Link to "Saito Arcade" telegram group on the arcade

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#530]
Adding an icon to the "Saito Arcade" telegram group on the arcade, with a message along the lines of "Need more players to start your games? drop an invite on the Saito Arcade Telegram Group", so that people are able to find opponents to invites with more players more easily.
Link to group: https://t.me/SaitoArcadeChat

**Comment by estapeluo** [comment]
Closing, it was implemented at some point,
