### ISSUE TITLE
Fix recievePayment type error in wallet

### ISSUE THREAD

**Issue by umairkhannn** [SaitoTech/saito-lite-rust#534]
<img width="328" alt="image" src="https://user-images.githubusercontent.com/104337801/168562184-3420b098-7f97-4718-8029-2f5d4b3c4a60.png">

Getting this error in wallet.

**Comment by karlsaito** [comment]
@umairkhannn is this fixed?

**Comment by umairkhannn** [comment]
@karlsaito this was fixed by @trevelyan last night and has merged the changes.

**Comment by trevelyan** [comment]
Fixed
