### ISSUE TITLE
As a user, I should be able to withdraw token by accessing the functionality in the side bar with the new enhanced UI/template

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#550]

**Comment by karlsaito** [comment]
please update @umairkhannn

**Comment by umairkhannn** [comment]
@karlsaito couldnt completed this yesterday. Will be complete and deployed to test instance by today.

**Comment by umairkhannn** [comment]
Changes deployed on test instance @karlsaito

**Comment by karlsaito** [comment]
basic functionality works on withdrawal. however, the user is able to proceed with withdrawal even if the amount is higher than the balance

<img width="674" alt="image" src="https://user-images.githubusercontent.com/96273856/169950777-ab349d76-dd8a-4d0c-b888-cb5fe3b98c7a.png">

you may close this ticket once you have merged to staging, however, i'm reopening #516 , as it's not totally fixed yet 

@umairkhannn
