### ISSUE TITLE
Pandemic - As a user, i should be able to see the count of remaining cards, discarded and remove

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#556]
Add card count on the draw piles

Current implementation of LABELS (please disregard the card itself):
<img width="173" alt="image" src="https://user-images.githubusercontent.com/96273856/169737598-544cad3b-c406-449c-b9fb-5f807600697a.png">

Proposed implementation of LABELS (please disregard the card itself):
<img width="106" alt="image" src="https://user-images.githubusercontent.com/96273856/169737640-2aa46030-64c7-4ca1-8fb5-8c8d4cedffc8.png">

**Comment by f8daniel** [comment]
The new Pandemic design has a widget showing remaining card count.

Old pandemic used graphics to give one a sense of how many cards are in either pile. Graphics > Text
