### ISSUE TITLE
Wuziqi moves not showing to the opponent 

### ISSUE THREAD

**Issue by Darkuso** [SaitoTech/saito-lite-rust#561]
Game moves are not showing for the opponent, so the game is dead after the first turn.

Steps to recreate:
1)create wuziqi invite
2) try to play (move the first piece)
3) game is stuck, the opponent never see the first move

![image](https://user-images.githubusercontent.com/9855617/170196021-c8a4f486-05fc-4403-a812-4e67f9dd9e22.png)

Also it looks to be that black is always taking the first starting turn (tested in about 10 games). Duke helped me out and still occurs the same all the time

Device Used: desktop/Web Browser
OS: Windows 10 Pro 64bits     Version	10.0.19043 Build 19043
Browsers: Chrome and Firefox
Versions: Chrome Version 101.0.4951.67 (Official Build) (64-bit)
                Firefox Version 100.0.2 (64-bit)

**Comment by estapeluo** [comment]
This is happening on staging as well. Flagging it.
