### ISSUE TITLE
Clicking Stand and Hit on Blackjack after a few rounds is unresponsive

### ISSUE THREAD

**Issue by andreyconsuelo** [SaitoTech/saito-lite-rust#564]
[console-export-2022-5-26_8-57-15.txt](https://github.com/SaitoTech/saito-lite-rust/files/8775443/console-export-2022-5-26_8-57-15.txt)

After a number of rounds in Blackjack, an issue arose where a player's options do not respond, clicking the moves STAND or HIT does not do anything. Refreshing, rejoining the game still gave the same issue and did not give a fix. 

Here is a supplemented console export from the game.

**Comment by karlsaito** [comment]
@andreyconsuelo please retest on the latest production, kindly reply back the status of the bug

**Comment by Tuch-o** [comment]
Tested this for 50+ rounds, even let the game idle for a couple hours and then went back and played without any issues so I'll close this. Feel free to reopen if you encounter it again.
