### ISSUE TITLE
TS - Ask not gave more cards than were discarded

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#577]
A user reported playing Ask Not and discarded 4 cards, but the game dealt about 10 cards back. Screenshots from the user that found the issue and the log of the discard ahead: 
![image](https://user-images.githubusercontent.com/61713323/170838354-e97d9631-ebeb-4d38-9bc0-37b581af436e.png)
http://puu.sh/J2PfB/fda2934697.jpg

**Comment by f8daniel** [comment]
I wish you included the console log. I've just tried three times and it deals the correct number each time.

![image](https://user-images.githubusercontent.com/70703104/170906492-1d595879-6dbf-4694-9ceb-bc7ab5b61bda.png)

**Comment by Rammko** [comment]
I wish i had as well, but it was a user that experienced the error and from my side the console looked clean. Will keep an eye out for this happening again and if it does will ask for console details from whoever experiences it.

**Comment by f8daniel** [comment]
Even if it is your opponent, your console will log how many cards are being
dealt. It is weird that Central America scoring was listed twice as a
discard, so there many have been some issue with multiple clicking. The
code has been changed to prevent that possibility.

**Comment by trevelyan** [comment]
> The code has been changed to prevent that possibility.

Let's see if it happens again.
