### ISSUE TITLE
RI: Game breaks after first scoring

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#578]
Steps:
1) Join RI game
2) Play first turn to completion
3) Get past the scoring
4)Game breaks

See:
![image](https://user-images.githubusercontent.com/61957527/170892640-e457d4b5-4980-43fb-b712-444546d89731.png)

![image](https://user-images.githubusercontent.com/61957527/170892649-47561dfc-de12-4853-a976-49e7f4ac2785.png)

Other information:
- Device Used: PC
 - OS: Win11
 - Browser: all browsers

**Comment by trevelyan** [comment]
Deleting this bug report for being underspecified.

There is no information here that can assist with debugging this.

**Comment by trevelyan** [comment]
My apologies -- the screenshots took a long time to load -- I had not seen that information.

**Comment by trevelyan** [comment]
thank you Duke, fixed.
