### ISSUE TITLE
TS, Settlers, Chess - HUD incorrectly shows "Status: Game Over: Opponent Quit" when a game ends

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite-rust#587]
Steps: 
1. Create a game.
2. Play until the game finishes. 
3. Check the HUD at the end of the game. It should print the actual winner instead of "Status: Game Over: Opponent Quit" for both players

Note: Seems to affect Twilight Struggle, Settlers and Chess. Rest of the games work fine.

![image](https://user-images.githubusercontent.com/54612963/171077525-d1d0c9d1-b879-401c-826e-f61572e21998.png)
(I lost this game, it should show "Kromtastic wins")

![image](https://user-images.githubusercontent.com/54612963/171078198-d297c3ee-4136-4b78-9fdc-47820e117397.png)

**Comment by trevelyan** [comment]
This issue will be patched in next push.
