### ISSUE TITLE
Private TS Game Doesn't Load the Cards Properly

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#600]
The cards are not loaded properly in Private TS game.
Steps to Recreate:
1. Create a private game of Twilight Struggle.
2. Send link to opponent.
3. Start the game,
4. The cards appear like the one on the screenshot.

<img width="960" alt="private TS bug" src="https://user-images.githubusercontent.com/101871246/172159138-42b5ae8a-6dd4-407d-af1b-c5f66394303d.png">

**Comment by noslrac27** [comment]
<img width="960" alt="private TS bug" src="https://user-images.githubusercontent.com/101871246/172160102-70de71d0-a992-4e64-9260-c4048ac64002.png">

**Comment by f8daniel** [comment]
Also documented on issue #588

**Comment by Kromtastic** [comment]
Tested several times and on different browsers, it no longer happens.
