### ISSUE TITLE
TS: minor errors

### ISSUE THREAD

**Issue by trevelyan** [SaitoTech/saito-lite-rust#601]
1 NORAD does not always trigger when DEFCON falls to 2.

- last failed attempt involved CIA - USSR gives US the coup, US refuses to take it. USSR then coups. no bonus
- occasionally there is a bonus - this change seems related to the last major upgrade

2. When displaying opponent influence on your status-message it adjusts it based on Red Purge / Brezhnev / Containment -- showing hte wrong influence opponent gets.

<img width="465" alt="Screen Shot 2565-06-07 at 21 16 16" src="https://user-images.githubusercontent.com/919135/172403247-a4551779-efc1-48a8-a538-79326b56e0a5.png">

**Comment by Tuch-o** [comment]
@trevelyan - just tested both issues:

1) NORAD is fixed - working just fine, found no problems with it after several tries.

2) Status message now shows the correct amount of ops when under Brezhnev, Containment, and Red Scare/Purge, but the log still doesn't account for it and prints the original amount, causing a discrepancy between HUD and log.

      US under Red Scare: HUD shows, correctly, "US plays Nuclear Test Ban for 3 OPS"
![image](https://user-images.githubusercontent.com/54612963/176501297-8a034b61-dca1-4ab2-b438-3eadd6b90181.png)

    but the log will show "US plays Nuclear Test Ban for 4 OPS" instead
![image](https://user-images.githubusercontent.com/54612963/176501524-848f7406-700d-4bdb-8b2d-b76e51a3eec7.png)

**Comment by trevelyan** [comment]
What was the cause?

Was Defectors headlined that round?

Are we sure this didn't happen in the headline phase?

**Comment by karlsaito** [comment]
@Tuch-o , can you confirm and answer @trevelyan  question

**Comment by trevelyan** [comment]
I'm not sure if this issue still exists. Why don't we keep our eye open for it.

**Comment by Tuch-o** [comment]
It's very minor, but it does still happen. I'll open a standalone issue in order to avoid confusion and we can keep this one closed since most of what was here originally _has_ been fixed.
