### ISSUE TITLE
TS - Ask Not doesn't show the discard animation for Scoring Cards

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite-rust#603]
Steps:
1. Start a game and play until Ask Not shows up.
2. Trigger Ask Not What Your Country Can Do For You (doesn't matter if US or USSR) with scoring cards in-hand
3. Try to discard the Scorings. You won't see an animation, but they will be discarded once you click Finished.

This is what it looks like:
![ASK NOT BUG_edit_0](https://user-images.githubusercontent.com/54612963/172446746-1b7491ea-a7e0-4b00-ad89-b5f12a8674f1.gif)

Hand after clicking Finished - shows they do get discarded:
![image](https://user-images.githubusercontent.com/54612963/172448220-7cf72e94-3af3-4802-b140-e2dde84f7723.png)

**Comment by f8daniel** [comment]
Because we use duplicate ids on the dom...
