### ISSUE TITLE
TS: Junta can be used to place infinite influence 

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite-rust#606]
Steps:

1. Start a game and play until Junta shows up. 
2. Set the game to Newbie Mode (this doesn't happen in expert mode due to the lack of a back button)
3. Trigger Junta.
4. Place the 2 influence in any country.
5. Choose to coup or realign.
6. Click the back button - Junta will be back in your hand but the 2 influence will remain. This can be done indefinitely.

![JUNTA GAME-BREAKING_edit_0(1)](https://user-images.githubusercontent.com/54612963/172472711-d63787ae-861d-4d42-a1ae-567dafde4df0.gif)

**Comment by karlsaito** [comment]
@Tuch-o  kindly retest and move the ticket to close in defect board. else reopen if the issue still exist

**Comment by Tuch-o** [comment]
Issue fixed.
