### ISSUE TITLE
Chess - Game is able to make a move and is stuck at player turns after the player exits and rejoins after the other player resigns

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#634]
Test Step
Create and start a game for 2 players
Player 2 exit the game by clicking Game -> Exit
Player 1 resigns on the game
Player 2 rejoins by clicking the continue button
Player 2 is able to take turn and the game is stuck

actual:
Player 2 is able to move and the game is stuck

expected:
game is over, none of the players should be able to take a turn
indication that the game has ended when player 2 re-entered the chess room

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/96273856/173760289-7d7b3d3c-e18d-430e-a558-96a353fe2316.png">

**Comment by f8daniel** [comment]
There was an issue with the game resignation, but should be fixed (in Staging)

**Comment by telechris8** [comment]
Test Step
Create and start a game for 2 players
![1](https://user-images.githubusercontent.com/63267624/176571565-6aa33441-0e6d-4510-8d24-0bebf67dad87.jpg)

Player 2 exit the game by clicking Game -> Exit
Player 1 resigns on the game

![2](https://user-images.githubusercontent.com/63267624/176571600-4caab6fc-0238-4397-87b5-ca31e08bca2b.jpg)

Player 2 rejoins by clicking the continue button
Player 2 is able to take turn and the game is stuck

![3](https://user-images.githubusercontent.com/63267624/176571613-4a19396e-7164-49d0-af82-717a12314e79.jpg)

after 10 seconds:

![4](https://user-images.githubusercontent.com/63267624/176571691-2d137b10-212e-4bc2-9c0e-4973aad3f5ba.jpg)

**Comment by f8daniel** [comment]
Seems to be entirely dependent on network speed and timing of the players. While moving from game to arcade or back again, player is disconnected from the Saito network and won't receive fast messages about game moves, so they have to wait a few (or 10) minutes for the block to be completed and get caught up on the game from the blockchain.
