### ISSUE TITLE
Twilight Struggle timer makes a player autoresign as soon as it's their turn.

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#637]
Steps:
1) Start a game with timer enable
2) Game ends.
This affects all time limits, and it's usually the US that loses. There were rare instances where the USSR lost. Games where no player autoresigns are just as rare.
Something of note is that when this bug happens, one side (the one that loses) will see the timer as if it was set to 60 mins, regardless of what the actual duration set on the invite was, the other side will see the correct timer.

![image](https://user-images.githubusercontent.com/61957527/173969537-2bfe3516-6f1d-44ef-ae53-1c6f838244c1.png)

*******************
For re-testing:
1) Does clock countdown when the game is waiting for me to do something?
2) Does clock stop counting down when the game is waiting for opponent?
3) Does game automatically end when my clock reaches 0?

**Comment by f8daniel** [comment]
The fact that the clock is displayed in red tells me that the saito JS bundle is out of date, which is why the bug is occurring. The current (as of three weeks ago) game engine will also say "time out" instead of "Out of Time"

**Comment by Tuch-o** [comment]
Fixed. Games don't autoresign and end properly when timer reaches 0

![image](https://user-images.githubusercontent.com/54612963/176497948-82c6b19d-c6ad-461f-93c7-c6e2cb16dcdb.png)

**Comment by The1Duke** [comment]
> The fact that the clock is displayed in red tells me that the saito JS bundle is out of date, which is why the bug is occurring. The current (as of three weeks ago) game engine will also say "time out" instead of "Out of Time"

it was tested on incognitos, on some timer would go from green and the correct time to 60 mins and red. David had already fixed this though.
