### ISSUE TITLE
TS: Norad triggers every move

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#640]
Test steps:
1)Create TS invite
2) Play until Norad shows up
3) Make sure requirements are met (Canada under US control).
4) Event Norad. As long as Defcon is 2, EVERY move from both players will trigger Norad. Quagmire still cancels this, and removing US control of Canada also stops it, until the US takes control back.

![image](https://user-images.githubusercontent.com/61957527/174325239-0089bdda-cd4a-43b8-b8bd-834ac1207181.png)

**Comment by trevelyan** [comment]
fixed
