### ISSUE TITLE
Saito.io/arcade last forum post disappears after game invite creation or game cancelation.

### ISSUE THREAD

**Issue by estapeluo** [SaitoTech/saito-lite-rust#654]
Last forum post disappears after game invite creation or game cancelation, this affects also user who are just idling in the arcade.

Steps to recreate:
1. 'User A' and 'User B' go to saito.io/arcade
2. 'User A' Creates a (Public or Private) game.
       - or -
                 Cancel the current game.
3. Game creates/cancels successfully and forums post on the side disappear for both user (and idlers users in the arcade).

Workaround:
User need to refresh the browsers

Example from canceling:
![Capture](https://user-images.githubusercontent.com/59634305/174850402-fb8f55cd-d459-4d15-b19e-ce6625680e88.PNG)
after clicking Cancel
![Capture2](https://user-images.githubusercontent.com/59634305/174850578-fa1300c5-dad6-40eb-a551-226c106e138d.PNG)

**Comment by karlsaito** [comment]
@estapeluo  can you confirm if this issue is still valid

**Comment by estapeluo** [comment]
This is still valid on production and staging

**Comment by f8daniel** [comment]
Not a top priority since we are getting rid of forums....
but shouldn't be too hard of a fix
