### ISSUE TITLE
Settlers:  Seems randomization issue with wool port

### ISSUE THREAD

**Issue by joelshu1** [SaitoTech/saito-lite-rust#655]
Module: Arcade/Forum/Settlers

Test Step:

1. Start new game.
2. Game board populates
3. wool port always in a shit place (always fully on one tile, not ever bridging two tiles)

<img width="272" alt="image" src="https://user-images.githubusercontent.com/95905420/175002949-b262934a-df99-437b-a752-f40f73dab459.png">

**Comment by estapeluo** [comment]
@joelshu1  It is expected to always bridge 2 tiles?

**Comment by The1Duke** [comment]
Aren't all ports like this?

**Comment by joelshu1** [comment]
No.  They are randomly assigned to different positions.  But the wool port is always like this, full attached to one tile only.

**Comment by The1Duke** [comment]
I'm 100% sure all ports always appear on the same spots and that they are attached to one tile only, and that that's the way they are meant to be.
Some screenshot from games throughout this week:
![image](https://user-images.githubusercontent.com/61957527/175793321-33d679e1-4269-4b19-bcf9-cc580a4f57ac.png)

![image](https://user-images.githubusercontent.com/61957527/175793325-646bd7d1-0fcb-4b04-bd62-d6e4bf69dd14.png)

![image](https://user-images.githubusercontent.com/61957527/175793330-dc688e60-8815-4c81-b50c-a94372b88f2c.png)

![image](https://user-images.githubusercontent.com/61957527/175793338-072b87dc-c3ae-498b-8f91-0c029ffaad85.png)

![image](https://user-images.githubusercontent.com/61957527/175793341-52ded1b0-6b0c-4c68-ad9d-bd7fe7b7d36c.png)

![image](https://user-images.githubusercontent.com/61957527/175793346-43d2df72-a518-406e-8195-bba092d1be02.png)

**Comment by joelshu1** [comment]
Oh didn’t realize that’s how it works.  But isn’t that a problem then? It shouldn’t really work this way, as the wool port is permanently disadvantaged

**Comment by estapeluo** [comment]
Port is fixed on this version, however you can suggest to add random location for the 2:1 goods.

**Comment by f8daniel** [comment]
I can confirm that port locations are in fixed locations in this implementation of Settlers. It didn't seem necessary to randomize them as the underlying tiles are already randomized. We can look into making some adjustments so that Wool isn't unnecessarily nerfed.

**Comment by f8daniel** [comment]
Ok, it turned out to be fairly easy to randomize the ports

**Comment by Tuch-o** [comment]
This is fixed, ports are random now and wool isn't at a disadvantage.

![image](https://user-images.githubusercontent.com/54612963/176463949-e894999a-4003-4b00-8354-3dd55dedf024.png)

**Comment by joelshu1** [comment]
super nice upgrade. Good job
