### ISSUE TITLE
Settlers: Bandit dumping most cards glitch

### ISSUE THREAD

**Issue by joelshu1** [SaitoTech/saito-lite-rust#656]
Module: Arcade/Forum/Settlers

Test Step:

1. Any player rolls a 7 generating the bandit, while user had 8+ cards in hand
2. User is presented with cards to discard
3. User quickly clicks on half their cards making them disappear from the selection menu
4. Cards suddenly all reappear but the discard counter appears out of sync
5. User is forced to remove more than half their cards to continue

**Comment by estapeluo** [comment]
Can confirm step 3, by clicking fast or tapping.

**Comment by Tuch-o** [comment]
Fixed.
