### ISSUE TITLE
Missing Rules Implemented in Settlers: Opponent's Village Should Split Your Roads Into Two.

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#663]
As seen on the screenshot attached, when I placed a village between the roads of Ark, it should have split his road into two. Meaning he shouldn't have the longest road reward anymore.

To Replicate:
1. Just build a village in between two roads of your opponent. 

![road should have split when i built the village between](https://user-images.githubusercontent.com/101871246/175294956-3ff73e4e-e238-4e59-b973-50dc68274d96.jpg)

**Comment by f8daniel** [comment]
Fix pushed to staging

**Comment by Tuch-o** [comment]
Fixed. The village in pic cut my longest road.
![image](https://user-images.githubusercontent.com/54612963/176472113-00ad16a4-2de3-46e5-8084-ca66b9948269.png)
