### ISSUE TITLE
Unable to Return to Game (Mobile)

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#670]
After tapping on the back button of the phone, I can only see the option of cancelling the game. I tried it twice in a game of Poker 2p.
Should be able to continue.

![Screenshot_20220624-193445_Chrome](https://user-images.githubusercontent.com/101871246/175528853-3cf1a67e-4b5b-4718-808c-a69a456465ef.jpg)

**Comment by Kromtastic** [comment]
Tested several times, on different browsers (Chrome, Firefox, Ad Blocker Browser) and games (TS, Poker, Settlers, Chess), issue no longer happens.
