### ISSUE TITLE
TS: Final scoring is not working

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#674]
Steps: 
1) Play Twilight Struggle
2) Reach the end of turn 10
3) Game ends at "Submitting moves... Awaiting Response from peers." Final scoring doesn't happen, VP doesn't not get awarded for it, and there's no victory message. This forces players to calculate themselves the finally scoring to see who actually won on close matches.

![image](https://user-images.githubusercontent.com/61957527/175679060-529a45ad-829f-415c-bb04-cb624da87c4e.png)

**Comment by f8daniel** [comment]
I wish you had given me more info.
Ran through a sample game and didn't run into this issue.
![image](https://user-images.githubusercontent.com/70703104/176352461-22e06054-67e9-4253-9db9-5f50247e5ba3.png)

**Comment by trevelyan** [comment]
fixed it -- please close!

**Comment by trevelyan** [comment]
closed -- fixed

**Comment by trevelyan** [comment]
as i remember, the problem was that the turn marker advanced off-the-board and a display error halted the game. just fyi. code doesn't halt now and so endgame works as intended.
