### ISSUE TITLE
Twilight Struggle: Defectors does not give 1 VP to US if used by USSR

### ISSUE THREAD

**Issue by Kromtastic** [SaitoTech/saito-lite-rust#677]
Steps:

1- Play Twilight Struggle as USSR

2- Use the card "Defectors" as ops, it won't trigger the event (Which gives 1 VP to the US if the USSR uses this card).

![Defectors not working](https://user-images.githubusercontent.com/98101498/175773955-d0eaec20-2ab7-4004-8e6a-0f15bda98a2c.png)

**Comment by trevelyan** [comment]
Does it not give the VP, or does it not print the VP in the log?

**Comment by Kromtastic** [comment]
It does NOT give the VP at all.

**Comment by trevelyan** [comment]
this was fixed as well -- apologies Dan. I should have removed from Github.

Deleting
