### ISSUE TITLE
Flashing tite bar for Settlers and sound when a game is accepted

### ISSUE THREAD

**Issue by StatixSx** [SaitoTech/saito-lite-rust#685]
Description:

∘ He suggested to add flashing tite bar if its your turn in Settlers and Sound when a game is accepted.

Who Requested: Swap@Saito 

 Type: 

∘ Game Design and Arcade Game Feature

Impacted:

∘ web (Sound when a game is accepted)

**Comment by f8daniel** [comment]
Sound will be annoying, but flashing title bar has been integrated for all games (at least an early rudimentary version)
