### ISSUE TITLE
Settlers: Villages don't cut longest road

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#688]
1) Play Settlers
2) Let other player build longest road
3) Have a road of at least 5 road pieces of length
4) build a village on the other player's road, making his road shorter than yours
5) Longest road is not taken from the player with the cut road.
See:
![2022-06-27 19-01-26 mkv_snapshot_07 51_ 2022 06 27_20 05 20](https://user-images.githubusercontent.com/61957527/176059603-f95483f2-36c7-481c-9a5e-cce6d356d034.jpg)

**Comment by karlsaito** [comment]
@f8daniel , can you take a look at this issue?

**Comment by Tuch-o** [comment]
This is fixed -- the village highlighted in the picture cut my longest road.
![image](https://user-images.githubusercontent.com/54612963/176470606-59447f55-ce5a-4c2d-903a-7c907d557377.png)
