### ISSUE TITLE
Crypto staking on other games

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#693]
Select a non-gambling game (e.g. chess) to see if we can combine the crypto functionality with the game engine's processing of end game conditions

- [x] Chess
- [x] Wuziqi
- [x] Wordblocks

Make sure Poker/Blackjack don't double dip.

**Comment by trevelyan** [comment]
settlers would be a good match. popular game

**Comment by karlsaito** [comment]
Played the games with @Darkuso 

chess
Crypto transfer is not working, issue is tracked via this card.
https://github.com/SaitoTech/saito-lite-rust/issues/764

wuzuqi
same error as above, issue is tracked via this card
https://github.com/SaitoTech/saito-lite-rust/issues/765
