### ISSUE TITLE
TS Enlarged card when hovering is flickering sometimes. This makes it hard to play the game.

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#701]
When I hover my mouse pointer over a card, it shows an enlarged version of the card but this is sometimes flickering which makes it hard to read the card. 
I need to click and hold on the card to stop it from flickering.

**Comment by noslrac27** [comment]
Uploading 20220629_202230.mp4…

**Comment by karlsaito** [comment]
@noslrac27  can you retest this?

**Comment by noslrac27** [comment]
Looks good. Didn't encounter the problem anymore.
