### ISSUE TITLE
Username glitch on chat

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#704]
Username displays differently on 2 different browsers. Refreshing seems to fix the problem

![name bug](https://user-images.githubusercontent.com/107991527/176585858-1217ed48-2fba-485d-9b42-0f32105818ca.png)

**Comment by Darkuso** [comment]
This is an odd bug, I saw him on different browsers, and just opened it again to recheck, On all my tabs are showing the 2nd picture name "sunyuchen"

**Comment by afkafk088** [comment]
Odd bug indeed. I just noticed when I saw gilbert from another  browser because i dont remember any gilbert speaking in chat.
Must have something to do with the wallet reset. Because when Sunyuchen first joined my game, the user icon and hash was different until he spoke in chat.
