### ISSUE TITLE
Settlers of Saitoa: confirmation button

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#706]
I think it would be a good idea to add an optional confirmation button for the ff to avoid misclicks:

1) Upon road placement
2) Choosing resource from banking

**Comment by estapeluo** [comment]
this add additional clicks/button to the gameplay, making the flow of the game slower.
Is this missclick very recurrent?

**Comment by afkafk088** [comment]
I realized it's going to make the gameplay flow slower. But so far I encountered 2 games that had an "accidental" misclick on a road placement. Not sure if those are the trolls giving an excuse when they're losing. Have to check in the coming games.

Perhaps we can do the same option as the one in TS in terms of move confirmation, the "don't ask again(expert mode)" tick box. Just an idea tho
