### ISSUE TITLE
Chess: random color independently of my choice

### ISSUE THREAD

**Issue by telechris8** [SaitoTech/saito-lite-rust#710]
Steps:
1. pick my color (white)
![a](https://user-images.githubusercontent.com/63267624/176822202-a1504c9d-1df4-4bfa-aec8-07250bc18bed.jpg)

2. start the game
![b](https://user-images.githubusercontent.com/63267624/176822225-96b2a3fb-7490-4bd0-bb10-cc6ee5f81814.jpg)

Expectations: i should play as white

Actual: i picked white but i´m playing as black

**Comment by f8daniel** [comment]
This issue is solved (in Staging), it just hasn't percolated up to production yet. New default is random assignation of colors, but initiating player can select their preferred color:
![image](https://user-images.githubusercontent.com/70703104/177449659-9a0db235-e6b5-4f35-8c87-b07444372547.png)

**Comment by telechris8** [comment]
issue fixed
