### ISSUE TITLE
Switchover from Saito-lite to Saito-lite-rust System

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#72]
Acceptance Criteria

-  Switchover from Saito-lite to Saito-lite-rust completed
- Passed UAT Test in Production
-  Release of Communication on new Network
-  Highly Critical Issues found in the next 24 hours are fixed upon Comms
- 

Subtasks

- [x] Preparation for the Switchover
- [x] Exploratory test in Test net (Core team)
- [x] User Acceptance Test in Test net (Arcader team to test, Core team to fix issues)
- [x] Switchover to Production
- [ ] Communicate the new Network
- [ ] Fix Highly Critical Issues in Production

**Comment by trevelyan** [comment]
closing this as switchover complete
