### ISSUE TITLE
Twilight Struggle: Indo-Paki war is not working as intended (modifier not being applied most likely)

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#724]
Played an organic and used indo-paki as the us when they controlled Iran and Afghanistan and the log said US rolled 4, modified 4, so after the game was over went to test it by myself and forced the USSR to control Iran, Afghanistan, AND India, then used indo-paki as the US on Pakistan and won even though mathematically its impossible to do so.

log states that the US rolled a 4, with a modified 4 again, showing in the following screenshot that the mod is not being calculated:
http://puu.sh/J9CgA/890cc359a9.jpg

console not really showing any errors and just showing this:
http://puu.sh/J9Chi/af5453bfff.png

**Comment by karlsaito** [comment]
@Rammko can you retest

**Comment by Rammko** [comment]
> 

Its working as intended now, modifier is being applied properly now
