### ISSUE TITLE
Twilight Struggle: Glasnost (Late War Card) Appearing on 1st Turn

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#733]
It took a while to load our first hand after the initial placement of influence.
Once my hand of cards has loaded, I saw that the Glasnost card is in my hand.
It is a Late War card which shouldn't be available before Late War,

![Uploading late war card appearing.png…]()

**Comment by f8daniel** [comment]
That can happen if we forget to turn off the is_testing flag when bug fixing a specific card (allows us to hard code a specific starting hand including mid/late war cards), but that does not appear to currently be the case.

**Comment by Darkuso** [comment]
I cannot recreate this bug. After a few test games, the card hasn't shown on any of the hands.

**Comment by trevelyan** [comment]
is_testing
