### ISSUE TITLE
TS: olympic games  bonus

### ISSUE THREAD

**Issue by telechris8** [SaitoTech/saito-lite-rust#736]
step 1: start the game
step 2: i play olympic games, my opponent participates
step 3: it shows our rolls but not my bonus (+2)
![olympic games](https://user-images.githubusercontent.com/63267624/178086315-9b88c050-48f2-4e43-9591-1a29c189ef1f.jpg)

**Comment by karlsaito** [comment]
@telechris8 , please retest in staging

**Comment by afkafk088** [comment]
retested this issue on staging. Confirmed fixed on staging
