### ISSUE TITLE
Settlers bug: Not showing which development card was bought

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#737]
Step 1: gather resources needed to buy development card
Step 2: Buy development card (fig.1)
Step 3: You got the development card but doesnt show which one (you'll only know on your next turn upon using) [fig.2]

Fig.1
![card1](https://user-images.githubusercontent.com/107991527/178093091-c978451f-5a36-49af-b89c-a5b89c216c7d.png)

Fig.2
![card2](https://user-images.githubusercontent.com/107991527/178093094-420d5e06-040c-4072-8707-bdc1a188922b.png)

**Comment by karlsaito** [comment]
@f8daniel  kindly tag @afkafk088 so he can be notified for retesting.

@afkafk088 , please ensure that you communicated back if it's working or not, and update the board
