### ISSUE TITLE
Settings page is not working

### ISSUE THREAD

**Issue by The1Duke** [SaitoTech/saito-lite-rust#742]
1. Go to burger menu
2. Settings
3. The settings tab within the settings menu (where the wallet options such as nuke, restore from private key, and so on) doesn't work. It won't load regardless from which menu you try to open it.

**Comment by trevelyan** [comment]
fixed

**Comment by estapeluo** [comment]
This wasn't fixed for over 1month, now settings/dev is 404.

**Comment by estapeluo** [comment]
here #869
