### ISSUE TITLE
TS: Sidebar log doesn't account for OPS modifiers when printing a card being played.

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite-rust#745]
Steps:
1. Start a game and play until Red Scare/Purge shows up. 
2. Trigger Red Scare/Purge.
3. Play a card as the side that's under RS/P - You'll see that the game status will print the correct amount of OPS being played, while the sidebar log won't account for the RS/P modifier and will show a different, incorrect number. 

![image](https://user-images.githubusercontent.com/54612963/178845723-20945f64-d955-471a-a766-9e88f5890a6b.png)
As seen here, US is playing Duck & Cover while under RS/P, so the log should show 2 OPS instead of 3.

**Comment by karlsaito** [comment]
please retest in staging @Tuch-o

**Comment by Tuch-o** [comment]
Fixed in staging. Will close.

![image](https://user-images.githubusercontent.com/54612963/180318727-efe5c419-b32f-4386-b508-fdb7a64ff4f0.png)
