### ISSUE TITLE
Polish settings page’s look and feel

### ISSUE THREAD

**Issue by davikstone2** [SaitoTech/saito-lite-rust#751]
- [x] Remove border from sections
- [x] increase Headers sizes and lose colons
- [x] Remove Bold on labels and replace with text shadow
- [x]  Remove hr
- [x]  Replace  private key input with a div
- [x] Add new color saito-black 
- [x]  work on section separation so ensure clean layout and clear separation.
- [x] Update the website
- [x]  change “wallet information” to “wallet”
- [x]  remove redundant 'Wallet' from 'Backup Wallet' and 'Restore Wallet' buttons.
- [x]  Move wallet buttons into wallet section and make secondary
- [x]  Make register text look active and clickable
- [x]  Convert module checkbox to toggle button
- [x]  move install module section into a saito-overlay
- [x]  Create sections: Version, Help
- [x]   Help section should contain styled social media links
- [x]   Make section headers h6
- [x]   Edit “menu” to be more symmetrical with “community chat” below
- [x]   Fix menu hover animations lag
- [x]   ?Place Version and Help section in right sidebar?

**Comment by arpee** [comment]
- [ ] menu highlight does not reach the side - looks off.
- [ ] menu icons not centered - too far right?
- [ ] text was a grey/subtle colour now all black undermining the lightness of the theme and replacement of bold with black.
- [ ] it would be better if the help icons came before the text so things line up.
- [ ] the help items should link to actual places that exist... this can be pulled from the site and co-ordinated with karl..?
- [ ] help options should linclude github... why is twitter there? 
- [ ] toggles are a bit too strongly colored... can we tiral:
      on = red border, red disk - white background
      off = grey border, grey disl - white background?

**Comment by arpee** [comment]
Can we fix up the toggles?
![image](https://user-images.githubusercontent.com/2867779/179703429-56746b9f-67ec-46bb-bfc0-897d5e8f5410.png)
- [ ] grey border and disk (as per request)
- [ ] get alingnment right (disk too high up - not verticallty centered.
- [ ] For the modal - does it need a title?
- [ ] The modal shoule have a close option - even if it is a click away to close modal.
- [ ] The list of installed modules needs to indicate what it is. 'Installed Modules' title?
- [ ] The installed modules list is still using the 'settings-appspace-app' class - is this right

**Comment by arpee** [comment]
![image](https://user-images.githubusercontent.com/2867779/180006890-7eb6c589-45ec-483c-952f-48f1e723b550.png)
- [ ] fix toggle to match color scheme above
- [ ] fix toggle to have the disk centered in the control vertically.
- [ ] Add 'Installed Modules' title.
- [ ] Add close option [X] in top corner to modal.
- [ ] Talk to Karl and update help options to match reality
- [ ] Talk to Khan or David about moving Version and Help to sidebar.

**Comment by karlsaito** [comment]
@davikstone2 , what's missing here?
