### ISSUE TITLE
Chat displaying yesterday's messages (on selected browsers/wallets)

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#758]
It does not seem to affect incognitos. Restarting browser, wallet nuking, and clearing cache does provide immediate solution
Takes about 30mins-1 hour before it reverts to the latest chat

![text bug](https://user-images.githubusercontent.com/107991527/179342186-dd26f14b-084c-4fbe-93c2-590893f49286.png)

**Comment by estapeluo** [comment]
This is related to #728
