### ISSUE TITLE
As a User, I should be able to join a League

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#772]

**Comment by afkafk088** [comment]
Test 772_1

**Objective:** 
• Join a League

**Steps:**
1) Click on **_Leagues_** Tab on Lobby
2) Click on **_Join_** on any league

**Test Results:**
• League successfully joined

**Comment by afkafk088** [comment]
Test 772_2

**Error 1:**
• Public league game **WITH** player limit disappears from lobby upon reaching max players

**Test Steps:**
1) Join league game **WITH** player limit
2) Nuke wallet
3) Join league game **WITH** player limit until it reaches max number of players
4) Click **OK** on _League Joined_ popup textbox
5) Refresh browser

**Problem:** 
• Said league game suddenly disappears from arcade lobby upon reaching the number of players required after refresh

**Expected:**
• League game with max players should not disappear from arcade lobby

**Temporary Solution:**
1) Wallet Nuke, Hard Reset, Close Browser
2) Said League game re-appears on lobby (not 100% guaranteed)


**Screenshot Output:**

1) Choose a League to join to reach max players (4/5 players on this case)
![WB 1](https://user-images.githubusercontent.com/107991527/179910023-17674b9a-e7be-4860-97bc-e4490c304ac8.png)

2) Click on Join
![bj2](https://user-images.githubusercontent.com/107991527/179910009-7f7ebc4c-7002-427d-9711-a23fed1b0c63.png)

3) After refreshing, league game disappears from lobby
![wb 2](https://user-images.githubusercontent.com/107991527/179910034-d630c871-5afc-49ca-aa7d-00ad364ba98d.png)

**Comment by afkafk088** [comment]
Test 772_3

**Error 2:** - Continuation of Error 1
• Public league game **WITH** player limit display showing the wrong number of players

**Test Steps:**
1) Join league game **WITH** player limit until it reaches max number of players
2) Refresh page - Said league game disappears from lobby
3) Nuke wallet, Hard reset, Close browser ( to make the game to re-appear on lobby )
4) Re-open browser - Said league game should now re-appear on lobby (not 100% guaranteed, have to re-do **_Step 3_** if re-appearing failed)
5) Said league game shows 0 players, Click on **VIEW** to see the actual count

**Problem:** 
• Wrong value display of players on the lobby
 
**Expected:**
• Number display of players in a league should reflect the actual number of players correctly


**Screenshot Output:**

Wrong player count display showing when league game re-appears (after _Step 4_)
![wb 4](https://user-images.githubusercontent.com/107991527/179910844-26dd5865-08a7-41e4-a9b5-9a4777d4d08a.png)

**Comment by afkafk088** [comment]
Test 772_4

**Error 3:** - Continuation of Error 2
• Public league game **WITH** player limit exceeds max number of players

**Test Steps:**
1) Join league game **WITH** player limit until it reaches max number of players
2) Refresh page - Said league game disappears from lobby
3) Nuke wallet, Hard reset, Close browser ( to make the game to re-appear on lobby )
4) Re-open browser - Said league game should now re-appear on lobby (not 100% guaranteed, have to re-do **_Step 3_** if re-appearing failed)
5) Said league game shows 0 players, Click on **VIEW** to see the actual count
6) Click on **JOIN** 
7) Click **OK** on _League Joined_ popup textbox

**Problem:** 
• You can still join a League game with max players filled
 
**Expected:**
• Players should not be able to join an already filled League


**Screenshot Output:**

Managed to join the supposedly already max player league
![wb 5](https://user-images.githubusercontent.com/107991527/179911470-cfdd3050-e21e-4607-9d6c-5718a8a64686.png)

**Comment by f8daniel** [comment]
* 772_2: If the league is full and you are neither it's administrator nor a member, we choose to hide it from view (just like we remove ongoing games from the arcade lobby)

* 772_4: Join button should now be inaccessible if a league is full.

! 772_3: is going to take a while to solve. In general, refreshing should fix the counts, but it depends on the lag between the lite-client and the saito-node for the database queries to come back

**Comment by f8daniel** [comment]
@afkafk088 
Re; 772_3: the League is still sometimes slow to update, but now when you click on view and it pulls the leaderboard it should accurately update the number of players in the league both in the overlay and in the page background

Please retest all these errors (on staging)

**Comment by afkafk088** [comment]
will retest these. Thanks Daniel

**Comment by karlsaito** [comment]
@afkafk088 , update on the retesting? if they have been fixed and no other issues are found, please close this and move to done

**Comment by afkafk088** [comment]
retested everything today, all issues from last testing has been fixed.
