### ISSUE TITLE
As a trusted User, I should be able to create a League

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#777]
I will be the administrator of the league and can set the parameters for the League, including

- [ ] whether the league is public or private
- [ ] which game the league is for
- [ ] the name of the league
- [ ] a text description to distinguish my league from other ones
- [ ] the maximum number of players in the league
- [ ] the ranking algorithm for the league

**Comment by karlsaito** [comment]
Test 778_1

Boundary testing result

System says value must be greater than 0 when adding -1
<img width="502" alt="image" src="https://user-images.githubusercontent.com/96273856/179890197-7b53322a-20b7-494d-9c47-a0c7c92960d1.png">
When adding 4, im getting this message
<img width="482" alt="image" src="https://user-images.githubusercontent.com/96273856/179890254-4ee53ff7-e98c-4ac9-b3e7-e6d35395ba15.png">

Expected **message** when the input is not divisible by 5
1. Number of players should be divisible by 5 (i just based on the accepted value) -- or something similar
@f8daniel

**Comment by karlsaito** [comment]
Test 778_2

Error: the created league does not show up unless refreshed

Test steps:
1. Create a league, fill up the necessary details
2. Click create league 

Problem: the newly created league does not show up. you need to refresh the page for it to appear. First time users will think their league is not created, get frustrated and stop using the functionality

Expected:
1. When  created league button is clicked, it should show up on the list immediately.

Screenshot output:
After creating a league
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/96273856/179891071-f3e14c41-6a73-41b4-b7ca-90126d1d3cd6.png">
After refreshing the page
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/96273856/179891252-0c0c03cf-2d3a-4649-9829-46cfa6520bee.png">

@f8daniel

**Comment by f8daniel** [comment]
777_1: Added explanatory notes to League creation parameters to explain that 0 = no limit. Steps of 5 are merely a convenience if your browser gives you a spinner, but who really needs to cap their league at 37 or 52 players?

777_2: Added code to skip waiting for transactions to pass through the blockchain so that you can immediately see your new league.

@karlsaito retest

**Comment by f8daniel** [comment]
Note, code is now on staging since Stun is being tested on test.saito

**Comment by karlsaito** [comment]
Both 777_1 and 777_2 are now working.

**Comment by karlsaito** [comment]
Test 777_3

Inconsistency in Button position,. Button positions improvement. 
<img width="635" alt="image" src="https://user-images.githubusercontent.com/96273856/180910221-d480d37f-2b99-4973-869d-c4c43aad68b3.png">
<img width="638" alt="image" src="https://user-images.githubusercontent.com/96273856/180909771-deb319b2-d847-4d2d-9931-f0b08b19134b.png">
To 
<img width="470" alt="image" src="https://user-images.githubusercontent.com/96273856/180909655-da56f757-31fc-47ee-bd78-c899ee170eab.png">

Test 777_4

Labels improvement of arrangement, spacing
<img width="693" alt="image" src="https://user-images.githubusercontent.com/96273856/180910341-2e335cc6-a870-4ace-885b-f63452c998f4.png">
Proposal: 1. Move the name of the game above. 2. Enough space between each labels 

@f8daniel

**Comment by f8daniel** [comment]
@karlsaito 
I am not going to waste time on 777_3 and 777_4 because I know within a month we will have to replace all the CSS and completely rebuild the layout.

**Comment by arpee** [comment]
https://github.com/SaitoTech/saito-lite-rust/pull/842 should resolve the above layout issues.

**Comment by karlsaito** [comment]
Closing
