### ISSUE TITLE
As a League Administrator, I should be able to invite other users to join the league

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#778]
Steps: 
1) go to league management page /league
2) click invite
3) copy-paste invitation link

**Comment by karlsaito** [comment]
Boundary testing result

System says value must be greater than 0 when adding -1
<img width="502" alt="image" src="https://user-images.githubusercontent.com/96273856/179890197-7b53322a-20b7-494d-9c47-a0c7c92960d1.png">
When adding 4, im getting this message
<img width="482" alt="image" src="https://user-images.githubusercontent.com/96273856/179890254-4ee53ff7-e98c-4ac9-b3e7-e6d35395ba15.png">

Expected **message** when the input is less than 4
1. The minimum player accepted to create a game is 5 (i just based on the accepted value)
@f8daniel

**Comment by karlsaito** [comment]
Test 778_2

Error: the created league does not show up unless refreshed

Test steps:
1. Create a league, fill up the necessary details
2. Click create league 

Problem: the newly created league does not show up. you need to refresh the page for it to appear

Expected:
1. When  created league button is clicked, it should show up on the list immediately.

Screenshot output:
After creating a league
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/96273856/179891071-f3e14c41-6a73-41b4-b7ca-90126d1d3cd6.png">
After refreshing the page
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/96273856/179891252-0c0c03cf-2d3a-4649-9829-46cfa6520bee.png">

**Comment by karlsaito** [comment]
This is working. moving to Done @f8daniel
