### ISSUE TITLE
As a user, I should be able to navigate to an invitation link to join a private league

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#780]

**Comment by karlsaito** [comment]
following up on this @f8daniel  for 780_1

**Comment by f8daniel** [comment]
@karlsaito 780_1 is fixed (though not deployed yet). 
Expected behavior:
1) user pastes invitation link into browser
2) opens saito.io/league and sees salert saying they are joining the league
3) if successful, will automatically redirect back to arcade (after 2 seconds)
4) if failure, will show a new salert saying that the league is full
5) when user clicks on alert, they are redirected back to arcade

Notes: 
1) It is important to redirect the user to clear the invitation link out of the url. Otherwise any browser refreshs will attempt to process the invitation a second time
2) I think it is better to put them back in the arcade so they can play a game with their new league rather than encourage them to create a bunch of new leagues.
