### ISSUE TITLE
Dominion - Playing "Library" breaks the game.

### ISSUE THREAD

**Issue by estapeluo** [SaitoTech/saito-lite-rust#788]
As soon active player plays Library, its gameplay gets interrupted and unable to proceed.

Steps to recreate:
1. Buy Library
2. Play Library
3. ???
4. Profit.

Screenshots:
![image](https://user-images.githubusercontent.com/59634305/180165395-0fa2badd-dce0-48a6-a48e-0bc00554d7dd.png)

![image](https://user-images.githubusercontent.com/59634305/180165429-1c5c1d3a-f72f-44f7-8b9a-19e4bd7c436e.png)

**Comment by karlsaito** [comment]
@f8daniel , kindly queue on your bug fixes

**Comment by f8daniel** [comment]
I've played dozens of times and not hit that problem with Library. It looks like a similar bug to what happens in all the card games, where the card decryption breaks down...

**Comment by estapeluo** [comment]
This is on the current staging site:
![image](https://user-images.githubusercontent.com/59634305/180593256-28921d97-7756-4e6c-a79a-f0e24f053b44.png)

**Comment by f8daniel** [comment]
Okay, I figured it out. It was a minor omission, but not visible if you play one of six other cards before playing the library.

**Comment by estapeluo** [comment]
Fixed as https://github.com/SaitoTech/saito-lite-rust/commit/4fcbeb8b2be0aac15f35410e3441e23b8a40d32e
