### ISSUE TITLE
Video Module Improvements

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#799]
key Id to map the tasks and usability issues found is through the control number (1-....)

Tasks
- [x] 1. Users should fit on the default screen size. Richard recommended to use the Flexbox.
- [x] 2. Change label from Stun to Video Chat in settings lists (labels)
- [x] 3. Add Video turnoff state icon
- [x] 4.  Disconnect button should be static and shouldn't exceed the panel size when the panel is resized
- [x] 5.  Mic icon shouldn't cause dynamic movement -- should be static, shouldn't move the other icons
- [x] 6.  Fix and clean up the panel sides. It doesn't look great. 

Usability issues found
1. Users does not fit on the default screen size
![image](https://user-images.githubusercontent.com/96273856/180392790-8e514260-7161-4618-8cda-2b227478a9f1.png)
2. Stun is a technical jargon to the general users
<img width="353" alt="image" src="https://user-images.githubusercontent.com/96273856/180692709-c5bc1330-56f9-4a9c-a9df-af126864f7fb.png">
3. There's no distinction on the video icon used  between a turned on and turned off video, whilst turning on and off the microphone does have different icons
<img width="421" alt="image" src="https://user-images.githubusercontent.com/96273856/180697233-f465b4b8-078b-4d56-a042-cf326bc9db3f.png">
4. Disconnect button issue
![image](https://user-images.githubusercontent.com/96273856/180715316-54c62c87-cefc-41c7-863c-f4dc3f6e83db.png)
5. The mic icon causes dynamic movement on the icons when it's turned off
6. Inconsistency in the panel sides. One side doesn't have padding the other side does. Unequal padding sides
<img width="848" alt="image" src="https://user-images.githubusercontent.com/96273856/180715926-a0b6af10-c60d-42b9-bb57-5d646f4fb842.png">

**Comment by arpee** [comment]
4 Should be fixed by CSS changes I have pushed. These also place the video screen vertically and horizontally centered in the screen on open.

With the above in place I think things are good to go.

**Comment by karlsaito** [comment]
@davikstone2  please link this to a PR so we can track which PR this was added
