### ISSUE TITLE
Video Module Issues

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#803]
- [ ] Issue 1: Clicking Stun module in settings create multiple content on the page
Test steps:
1. Open Settings
2. Click Stun module
3. Click again stun module
Error found
<img width="760" alt="image" src="https://user-images.githubusercontent.com/96273856/180720152-34666ce2-f00f-41be-8627-9bbed863351f.png">

**Comment by karlsaito** [comment]
@davikstone2

**Comment by karlsaito** [comment]
please link this to a PR @davikstone2 

where to test? staging or test?

**Comment by estapeluo** [comment]
This is no longer an issue in production nor staging server.

**Comment by estapeluo** [comment]
Closing as this issue isn't longer present.
