### ISSUE TITLE
Arcade - Unable to cancel game invites

### ISSUE THREAD

**Issue by estapeluo** [SaitoTech/saito-lite-rust#810]
Since video module update, games invites can't be cancel (only gets autoremoved after the 30min mark).

https://user-images.githubusercontent.com/59634305/180982886-b71a4350-09c6-4be2-824a-0a18b9d8fb00.mp4

**Comment by estapeluo** [comment]
Staging site is unaffected.

**Comment by karlsaito** [comment]
fix has been pushed by @f8daniel  in staging.

**Comment by estapeluo** [comment]
code is live on prod.
