### ISSUE TITLE
Add improvements to Video feature

### ISSUE THREAD

**Issue by davikstone2** [SaitoTech/saito-lite-rust#812]
The tasks are arranged by priority (top to bottom)

- [x] only show video boxes on connect.
- [x] create shareable links to start video call

**Comment by arpee** [comment]
- [ ] add 'share link' option to pop-up triggered by 'create invite'
- [ ] auto fill join input box with room id on creation

**Comment by estapeluo** [comment]
Closing, its live on Staging and work as intended.
![image](https://user-images.githubusercontent.com/59634305/181896883-370d9737-c7e1-4265-bdb0-de323ea5e4a5.png)
