### ISSUE TITLE
Twilight Struggle: UN intervention missing when clicking on back

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#817]
STEPS:
1) Event UN intervention
2) Select opponent card to be used by the UN intervention
3) Use as OPS (place influence)
4) Change mind and press on back arrow
5) UN intervention is now missing from your hand

![un missing](https://user-images.githubusercontent.com/107991527/181429148-f7f6c68a-bba8-4d18-8499-dd72691aad48.png)

**Comment by karlsaito** [comment]
assigning to @f8daniel

**Comment by karlsaito** [comment]
moving forward, please make sure to add a label @afkafk088 where it was identified. (Production or Staging)

**Comment by f8daniel** [comment]
Note: Playing UN Intervention (or any card) as an event is not cancellable. However, we have fixed the situation where you decide you want to pick a different opponent card to play for ops as part of the UN event. 

Furthermore, the log message on a cancelled OPS play is now accurately reflected on both player's browsers
Furthermore, playing cards for OPS should more consistently give the option to cancel (there was a bug blocking the back button in a number of edge cases)

**Comment by f8daniel** [comment]
@afkafk088 fix deployed on staging

**Comment by afkafk088** [comment]
retesting this one today on production

**Comment by afkafk088** [comment]
hi @f8daniel , I retested this issue just now. I would just like to confirm something regarding the UN intervention. 

You mentioned that  you have fixed the situation where you decide you want to pick a different opponent card to play for ops as part of the UN event. But what if I decided I wanted to pick a different card completely instead of UN intervention? 

This is the part where the UN intervention disappears from the hand. The thing I wanted to clarify is if the disappearance of the card is normal since I already "evented" UN intervention? Kindly refer to the video below (test starts after headline cards).

Thanks Daniel

https://user-images.githubusercontent.com/107991527/182301823-08fe1a19-916b-4804-95a6-afb569796004.mp4

**Comment by f8daniel** [comment]
If you play any other card as an event (whether it is yours, your
opponents, or neutral), you are committed to that card and can't undo it.
So, it makes sense to treat UN intervention the same, thus you can reselect
the card for ops but can't back out of the UN intervention event.
