### ISSUE TITLE
Joining video call via shared link is not functioning. User only sees gray screens/windows from other users who joined.

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#818]
Test Steps:
1. User A creates a video call via shared link
2. User A shares the link to user B
3. User A joins the call
4. User B joins the call
5. Both users only see gray windows/screens of the other attendees

Screenshot:
![image](https://user-images.githubusercontent.com/96273856/181432403-9acf7a69-6361-4967-ba50-c62c175f7c10.png)

**Comment by karlsaito** [comment]
assigning to @davikstone2 

@estapeluo , please follow through for retesting.

**Comment by estapeluo** [comment]
Retesting on Production, doesn't happens however it took longer on Prod than on Staging.

**Comment by karlsaito** [comment]
Issue is still existing in production. @davikstone2

**Comment by estapeluo** [comment]
Tested with @Darkuso on Staging via Sharing URL and works. Also with @davikstone2 early (yesterday).

**Comment by estapeluo** [comment]
Tested with @afkafk088 , same results on staging.

It looks like Production doesn't have the updated code yet @karlsaito, tag me when code is live prod for retest.
