### ISSUE TITLE
Dominion - Playing "Chancellor" makes the game stuck at "Would you like to discard your deck prompt?"

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#822]
1. Played Throne Room
2. Played Chancellor
3. Kept clicking on "Yes" or "No" but the game doesn't do anything.

<img width="960" alt="Stuck Dominion" src="https://user-images.githubusercontent.com/101871246/181505180-dd2db3a2-cf6e-4107-a10c-a23c64c4cc93.png">

**Comment by f8daniel** [comment]
Idk, I just tried it on staging. Played Chancellor 5 times in a row without any difficulties. It is a bit slow to respond to your answer, but doesn't get stuck. Must be something else that happened in game play (probably an internet connection thing).

**Comment by estapeluo** [comment]
Closing, unable to replicate, even on small resolution to check if its an HTML issue.
