### ISSUE TITLE
Settlers: Refreshing the tab during initial road build freezes the game 

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-lite-rust#826]

**Comment by Tuch-o** [comment]
Steps:
1. Start a Settlers game.
2. Place the initial village.
3. When prompted to place the first village's corresponding road, reload the page. You'll still be asked to place it, but won't be able to click anywhere to place a road.

**Comment by f8daniel** [comment]
It's annoying that I fixed this before, but it keeps coming back.
Will be fixed on next deploy

**Comment by f8daniel** [comment]
@Tuch-o fix should be live, please retest

**Comment by Tuch-o** [comment]
Fixed, will close.
