### ISSUE TITLE
Registration UI resets on the leagues whenever i refresh/rejoin the arcade

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#839]
aving a join button again when i should be expecting a view button only can provide a confusion to users if they have really join the league.

it's a network lag according to Dan, it takes 1.5-2 mins before it reflects back. this 1-2 mins is enough time for users to ignore the leagues/or exit. See https://lawsofux.com/en/doherty-threshold/ on the rule of 400ms, why this is a major issue on user experience

Test Plan:
1. Go to arcade
2. Join a league
3. User is able to join
<img width="830" alt="image" src="https://user-images.githubusercontent.com/96273856/182556849-e3a91815-c355-44dc-89b8-88714d2328d0.png">
4. User close browser

5. User access arcade->league
6. User is requested to join again
<img width="830" alt="image" src="https://user-images.githubusercontent.com/96273856/182556973-19d187fb-02d1-4e54-b05f-146f2641f345.png">
7. The UI is updated after 1.5-2 mins

Error:
1. UI on league is not updated when user rejoins the arcade, takes 1.5-2 mins before it reflects. It will provided confusion on registration

**Comment by estapeluo** [comment]
#840 might be related to this

**Comment by f8daniel** [comment]
@estapeluo @karlsaito 
Updated Staging with new code that is more aggressive about rerendering the leagues so the information should update as soon as the sql queries are complete (though to be fair, staging is less laggy than production so we didn't notice this issue before on staging)

**Comment by estapeluo** [comment]
Staging is blazing fast, but solution is working as intended. We will wait for Prod to be updated.
