### ISSUE TITLE
League tab doesn't shows item until a user creates or cancel a game invite

### ISSUE THREAD

**Issue by estapeluo** [SaitoTech/saito-lite-rust#840]
League tab doesn't shows items until a user creates or cancel a game invite.

Test steps:
1) User A and B joins the arcade
2) User B clicks the League tab
3) User A creates a games -> User B sees all the leagues he is in.

Video:

https://user-images.githubusercontent.com/59634305/182560408-95d9ab38-6730-4d7e-80f5-abe44b480266.mp4

**Comment by f8daniel** [comment]
@estapeluo @karlsaito
Updated Staging with new code that is more aggressive about rerendering the leagues so the information should update as soon as the sql queries are complete (though to be fair, staging is less laggy than production so we didn't notice this issue before on staging)
