### ISSUE TITLE
Enhancement: Join user created league on joining game

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#844]
Problem: User creates a league, wants games to count for said league. Some rando accepts public game invite, but isn't member of league, so game (other than being fun) doesn't count

Proposed solution:
1) Add "Create Game" button in League overlay
2) Creating game through there sets a hidden option with the League ID
3) If the League is public and has open slots, display game invite publicly (as normal)
4) On clicking to Join, check if player is member of league (like checking crypto)
5) Prompt player to join league before letting them join game

**Comment by f8daniel** [comment]
Solution is Deployed on Staging

Notes: this only affects user created leagues (not the saito-administered global leagues)

1) Player creates league
2) Player views league and creates a game through the league-view-overlay
Who can see the game invite?
- If league private, only league members
- If league public and full, only league members
- If league can be joined, anyone

This way, if settlersKing wants to challenge people for his League, he just needs to create the game invite through the League and it will make ppl join his League in order to play.

**Comment by estapeluo** [comment]
> 5. Prompt player to join league before letting them join game
Doesn't prompt on staging yet.

**Comment by f8daniel** [comment]
1. Click Play on User created League
![image](https://user-images.githubusercontent.com/70703104/182976824-733e23ea-254c-4ed8-a28c-87f2b393a0aa.png)
2. Confirm Create League game
![image](https://user-images.githubusercontent.com/70703104/182976867-59941cd3-5e05-4102-b074-a6d75a31516c.png)
3. New Key sees invite marked League
![image](https://user-images.githubusercontent.com/70703104/182976919-b5c34120-0680-4190-a5b3-bdf9525ca7d6.png)
4. Prompted to Join
![image](https://user-images.githubusercontent.com/70703104/182976942-6ea35000-3039-4942-a30a-096e423763a4.png)
