### ISSUE TITLE
Settings - It throws 404

### ISSUE THREAD

**Issue by estapeluo** [SaitoTech/saito-lite-rust#869]
Accessing to Settings via sidebar which redirects to https://saito.io/dev/#email-nav-Settings throws 404 error page.

Test steps:
1. Join saito.io/arcade
2. Click the Hamburger menu
3. Click Settings

**Comment by estapeluo** [comment]
Issue present in Staging

**Comment by estapeluo** [comment]
Seems it will be replaced/integrated with the new Redsquare module, with #768 and #751 and others.

**Comment by estapeluo** [comment]
Tagging @karlsaito for tracking records.

**Comment by umairkhannn** [comment]
@estapeluo we're moving **settings** and **crypto** from /dev to /redsquare.
