### ISSUE TITLE
Dominion zoom scrollbar 

### ISSUE THREAD

**Issue by Darkuso** [SaitoTech/saito-lite-rust#871]
The text of the cards is barely visible (I'm playing at 1440p), adding a zoom scrollbar like in TS will improve the gameplay greatly in addition to the current compass feature (magnifying glass).
![image](https://user-images.githubusercontent.com/9855617/183558237-585d9e6d-13e8-4f0e-b7a7-02ebc2ac0030.png)

**Comment by estapeluo** [comment]
This needs some tweaks for mobile view and ultra (not anymore, 1440p will be standard soon) resolution.

Tagging @f8daniel

**Comment by afkafk088** [comment]
+1 on this. Suggestion to put the "enlarged preview" on the left side of the "Carpet" since space is rather big, than over the cards for enhanced playability.
