### ISSUE TITLE
Twilight Struggle: Mil-op penalization did not trigger after final action round (How i learned not to worry)

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#872]
**Scenario:** 
• Mid war, last action round
• Defcon at 2
• **USSR mil-ops 2** vs **US mil-ops 0**

**Steps:** 
1) On final action round, US triggers "How i learned not to worry" as event
2) Move defcon to liking (I clicked Defcon 2 - to avoid USSR from coup-ing EU/Asia next round)
3) Round ends immediately (no counting of mil-ops, no penalization of USSR influence (USSR 2mil-ops vs US 5mil-ops)

**Expected Result:**
• US should  have gained 3 influence due to USSR getting penalized on mil-ops

![no penalized](https://user-images.githubusercontent.com/107991527/183575749-65424ac5-a84f-4d18-b463-497a07997b74.png)

**Comment by karlsaito** [comment]
@afkafk088  check if this is still occurring on the latest production

**Comment by afkafk088** [comment]
will test this out tomorrow. Thanks!

**Comment by afkafk088** [comment]
tested this today. Seems to be working fine already. Closing this
