### ISSUE TITLE
Dominion: No Background for the Prompt After Playing Chancellor

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#877]
There is no background for the question of the prompt that appears after playing Chancellor.
Just need to play Chancellor with the prompt appearing on the top portion of the browser.

This happens when the prompt appears at the top part of the browser.
![298525120_587435192883579_1042740609530385303_n](https://user-images.githubusercontent.com/101871246/183675748-02bad33d-625a-4b3e-83ca-4ea325c352f9.png)
![294823406_1663736880650665_4351727845735743102_n](https://user-images.githubusercontent.com/101871246/183675817-81b6665a-c5c0-4cf7-b551-15967466275f.png)

This doesn't happen if the prompt appears at the bottom part of the browser.
![298374965_825512852138748_1330494171352754518_n](https://user-images.githubusercontent.com/101871246/183675780-b3922c31-bab8-4c27-9341-2c1931cd5bea.png)

**Comment by f8daniel** [comment]
This actually has nothing to do with Chancellor, but a bug in the vertical hud css

**Comment by karlsaito** [comment]
@noslrac27  can you check if this is fixed? if yes, please close the bug

**Comment by noslrac27** [comment]
Looks good. The problem no longer persists.
