### ISSUE TITLE
Redsquare: Missing chat functionality and issues.

### ISSUE THREAD

**Issue by estapeluo** [SaitoTech/saito-lite-rust#884]
- [x] Clicking on the chat-sidebar to open a new window triggers an alert: 

Steps to recreate:
1. User A visit https://saito.io/redsquare/
2. Click at the left side-bar, any of the chats.

Screenshot:
![image](https://user-images.githubusercontent.com/59634305/183833095-6295b1eb-513f-4b7b-bd33-1718e419b305.png)

- [x] Receiving an incoming message opens a chat with no CSS:

Steps to recreate:
1. User A visit https://saito.io/redsquare/
2. User B visit https://saito.io/arcade
3. User B opens chat and send a chat message
3.2 User A waits for an incoming chat message

Screenshot:
![image](https://user-images.githubusercontent.com/59634305/183833305-9034bd5c-e0a5-4ee3-b99a-27d1cc8d1ac0.png)

**Comment by estapeluo** [comment]
Comunity Chat box is a template:
![image](https://user-images.githubusercontent.com/59634305/183833607-cd794be4-a983-406b-a870-14bc22df119a.png)

**Comment by karlsaito** [comment]
@estapeluo kindly verify the first issue in prod, kindly close this once the initial issue has been fixed

Second issue on template has been detailed out on this requirement: #934

**Comment by estapeluo** [comment]
@karlsaito this issue still persist.

**Comment by karlsaito** [comment]
Please detailed out the test step for the issue initially raised. It's not clear on how to replicate them @estapeluo

**Comment by estapeluo** [comment]
Issues had been fixed
