### ISSUE TITLE
Game chat module screen panels disappears (with camera light still on) when other player exits the game without disconnecting

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#887]
Test Step
1. Play a game and open video chat
2. After the game is finished/or a player resigns, one player returns to the arcade or exits the game without disconnecting on the video chat
3. This is shown on the screen of the remaining player, the screen disappears even though the camera light is still on:
![image](https://user-images.githubusercontent.com/96273856/183854283-b99ffad8-491e-46ec-afa2-ad9e535d5ce8.png)

Expectation:
1. The game chat screen should still have the panel (screens)

**Comment by davikstone2** [comment]
Fixed with commit: https://github.com/SaitoTech/saito-lite-rust/commit/3cb5755afa7d4ac2208b2aa6e0e10733801e40a9

**Comment by karlsaito** [comment]
@estapeluo  can you check if this still exist in production? please validate and update the issue

**Comment by estapeluo** [comment]
Returning to the arcade close the video modal instead of just closing the screen panel
