### ISSUE TITLE
Broken UI in Games Page

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#915]
- [ ] When clicking a game that the creator has made, it only shows an empty panel
<img width="967" alt="image" src="https://user-images.githubusercontent.com/96273856/184634818-db0d8bcb-4d41-4aaf-8acd-e34eafb5e4d1.png">

Expected: Invite and Cancel game buttons. similar to the arcade

- [x]  Unreadable and transparent panel of the link sharing

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/96273856/184634159-c3ab7e70-cac5-4c7e-9af2-c18ff7ec7693.png">

- [x]  When How to Play is clicked in the Game page section, the game mechanics overlaps with the page games
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/96273856/184634277-faf36dd9-c260-47c4-a281-b2fee9edcd34.png">

**Comment by davikstone2** [comment]
#### Notes

For the first issue, i don't think the game feature is completed yet

**Comment by davikstone2** [comment]
Fixed in this pull request: https://github.com/SaitoTech/saito-lite-rust/pull/932

**Comment by karlsaito** [comment]
tested and working
