### ISSUE TITLE
Unable to access and reply on previous tweets/replies/original tweet on retweets/share/comments posted

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#918]
Expected: 
User should be able to access any tweets and reply on that tweet
All tweets should have a "standalone" link, which fetches that tweet and its children from the server dynamically

Implemented together with #920 and #913 

Test Steps:
1. Click a retweeted/post
2. Click any of the other tweets. The page does not allow you to access and reply on other tweets
<img width="548" alt="image" src="https://user-images.githubusercontent.com/96273856/184783430-a1426697-9b62-46d1-88bf-64334b629253.png">

**Comment by davikstone2** [comment]
Fixed with this pull request: https://github.com/SaitoTech/saito-lite-rust/pull/960

**Comment by karlsaito** [comment]
already working in prod, closing now
