### ISSUE TITLE
Each Tweet or Post should have a unique URL and should be shareable by copying the address bar

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#920]
Related to #918 

Description:
There should be a unique URL for each post. When someone clicks a post, the address search bar should contain the unique link for the post instead of home)
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/96273856/184586804-33e0a4b4-13be-4bbf-a97f-782fb704d5f3.png">

Recommendation by David for implementation
1. Use this URL template:
redsquare?tweet_id=________________;
2. tip in implementation: app.browser lets us check if URL params exist

**Comment by karlsaito** [comment]
@umairkhannn  related to your bugs

**Comment by umairkhannn** [comment]
@karlsaito thanks. will look into this after the critical/major bug fixes.

**Comment by davikstone2** [comment]
Fixed with this pull request https://github.com/SaitoTech/saito-lite-rust/pull/960

**Comment by karlsaito** [comment]
@davikstone2  PR number of this, please attach on the development section of this
