### ISSUE TITLE
Duplication of chat messages 

### ISSUE THREAD

**Issue by Darkuso** [SaitoTech/saito-lite-rust#922]
After sending any message in chat, it sends multiple copies, it started as 2 or 3, but the number keeps increasing and is now freezing the tabs and browsers. It occurs in the community and in 1-to-1 chats. Also, the message stays in the typing box. 

![image](https://user-images.githubusercontent.com/9855617/184804541-481a463b-c4b9-46b2-b939-c8876e61a449.png)

![image](https://user-images.githubusercontent.com/9855617/184804505-f888e1b8-6c0f-4597-94b4-4e922f2fdaec.png)

**Comment by afkafk088** [comment]
Just adding some "issues" related to the error

1) I can't see messages of other people in the chatbox. I only see the ones i type
![issue 1](https://user-images.githubusercontent.com/107991527/184806376-e4fbac46-69b7-4a4e-9037-486a7e37e980.png)

2) Games not appearing on lobby (on other browser)
![issue 3 not same game on lobby](https://user-images.githubusercontent.com/107991527/184806424-b6cf655e-74bd-4ce1-bb1b-80bffd5dda21.png)

**Comment by estapeluo** [comment]
Purr-fect

**Comment by estapeluo** [comment]
fixed at d2484f640f4c96f38ce3b467b27b5491954fed67
