### ISSUE TITLE
Unable to create New Game

### ISSUE THREAD

**Issue by estapeluo** [SaitoTech/saito-lite-rust#923]
Steps:
1. Go to https://saito.io/redsquare/#games (or go to RS and click Game)
2. Click "Create New Game" Button, next to "Schedule for Later"
3. Select any game

Result:
Big game picture modal shows, only clicking around cancels it. Unable to create the game invite.

Screenshot:
![image](https://user-images.githubusercontent.com/59634305/184806687-77a27092-e596-405c-a15e-4462024b17a6.png)

Expected:
![image](https://user-images.githubusercontent.com/59634305/184806849-e3de1237-c368-499e-bedd-11e522dbf035.png)

Work around: 
Click to close the modal, create game via "Create Game" button from the game's cards.

Version:
Code Version: 4.257
Wallet Version: 4.257

**Comment by estapeluo** [comment]
Issue present on Staging.

Version:
Code Version: 4.249
Wallet Version: 4.249

**Comment by karlsaito** [comment]
@estapeluo  please retest if this is still applicable

**Comment by estapeluo** [comment]
Modal background not longer blocks usability.
