### ISSUE TITLE
Improvement of saito-loader and lazy loading across Red Square

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#926]
- [x] saito-loader should appear as an overlay on the page when it's triggered instead of this. the loader to appear on page-load while the tweets load
<img width="697" alt="image" src="https://user-images.githubusercontent.com/96273856/184812119-62dbee96-51f5-4660-afcc-04bf54d3bbc1.png">

- [x] Show loading animation on page load to show activity

- [ ] Lazy loading of content (load first 10 tweets and load more on scroll)

**Comment by karlsaito** [comment]
@umairkhannn  can you confirm if all these requirements have been implemented

**Comment by umairkhannn** [comment]
@karlsaito i just got to know about these requirements, so no they're not implemented.

**Comment by karlsaito** [comment]
@umairkhannn  please attach the PR 
<img width="256" alt="image" src="https://user-images.githubusercontent.com/96273856/185845449-4ddd54b3-4e1a-4b71-a852-25d07e034ff2.png">
so we know which PR have closed this improvement
