### ISSUE TITLE
Redsquare: Tweet feed doesn't load

### ISSUE THREAD

**Issue by estapeluo** [SaitoTech/saito-lite-rust#927]
Might be related to #928 

Tweet feed doesn't load at: https://staging.saito.io/redsquare/#home

Steps:
1. User goes https://staging.saito.io/redsquare/#home
2. Create new tweet
3. Refresh

Result:
Creating: 
![image](https://user-images.githubusercontent.com/59634305/184815305-4b547978-e1d2-40aa-8f95-a0ca790906cf.png)
After posting:
![image](https://user-images.githubusercontent.com/59634305/184815373-9379aed9-742a-4716-8d19-bc99fabdc8a9.png)
After clicking the load new tweet
![image](https://user-images.githubusercontent.com/59634305/184815415-228d8787-4578-4785-8d09-762485e3ec0a.png)

Expected:
1. Tweets should load upon landing on page
2. New tweet should show after creating a new one

**Comment by karlsaito** [comment]
Additional info, block explorer have added the tweets on the blockchain successfully.

**Comment by estapeluo** [comment]
Log example from step 1

[saito.io-1660633221885.log](https://github.com/SaitoTech/saito-lite-rust/files/9348557/saito.io-1660633221885.log)

**Comment by karlsaito** [comment]
Additional Use case:

1. User add tweet
2. Upon clicking load new tweets, the tweet shows
<img width="430" alt="image" src="https://user-images.githubusercontent.com/96273856/184817664-c639dedd-82ee-4a9c-bd7e-acb00704dfc3.png">
3. Click Refresh
4. Create new Tweet
5. Only the new tweet created on step 4 shows, the tweet from step 2 is not shown on screen
<img width="538" alt="image" src="https://user-images.githubusercontent.com/96273856/184817901-667b8b9d-ae46-4c66-b01b-9e6e9e885fde.png">

**Comment by estapeluo** [comment]
Tweet loads after long wait times, Issue is now https://github.com/SaitoTech/saito-lite-rust/issues/940
