### ISSUE TITLE
saito.io/arcade errors on console.log

### ISSUE THREAD

**Issue by estapeluo** [SaitoTech/saito-lite-rust#929]
saito.js is throwing errors.
Steps:
1. Visit saito.io/arcade

Screenshot: 
![image](https://user-images.githubusercontent.com/59634305/184818285-a531ddb7-d8c2-48dc-b409-5bdd91fcb38e.png)

Log:
[saito.io-1660633550281.log](https://github.com/SaitoTech/saito-lite-rust/files/9348589/saito.io-1660633550281.log)

Version:
Code Version: 4.259
Wallet Version: 4.259

**Comment by estapeluo** [comment]
`{name: 'SyntaxError', message: "Unexpected ''", at: 1, text: ''}`
Seems to be triggered per TX/Block

**Comment by estapeluo** [comment]
Issue not found in Staging site

Version:
Code Version: 4.249
Wallet Version: 4.249

**Comment by karlsaito** [comment]
Issue has been tested w/ @estapeluo  and already passed

**Comment by karlsaito** [comment]
Issue is fixed in prod now.
