### ISSUE TITLE
Registration dialog not firing on test network

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite-rust#93]
In a browser attached to the rustest.saito.io trigger he registration dialog be either

 - trying to create a game invite
 - clicking “register a username" in settings

Enter a valid string and press "REGISTER USERNAME"

Console output appears in the browser for each click but no transaction is sent and the window does not close.

No error appears.

It looks like the message is going to the browser?

NB: This was working well with the registry module on the same single node as everything else. This behaviour appeared after putting the registry module on the second node.

**Comment by trevelyan** [comment]
I do not think this is a bug, as I am seeing this.

What is happening is that the message only fires the first time the wallet
is created.

If someone clicks "skip" we don't harass them again. So it will not show
again unless the browser cache is cleared.

Resetting the wallet does not reset all of the data associated with the
wallet, including this.
