### ISSUE TITLE
Chat Popup repositioning -- current chatbox floats when you scroll down further

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#930]
Test Step:
1. Go to Red Square
2. Click the chatbox
<img width="230" alt="image" src="https://user-images.githubusercontent.com/96273856/184845092-7a74ce20-865a-4516-ae84-ceb855c8deff.png">
4. Chatbox appears on the bottom right side
5. Scroll down and the chatbox floats
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/96273856/184845378-542a89e2-2d36-4281-838d-fe69abcd57a5.png">

expected:

Chatbox is always be positioned on the lower lip-screen or lower right of the screen even if you scroll down. It should be similar to the arcade.

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/96273856/184845654-eb9c0d1d-e258-4aa6-8bd5-7f84632651bb.png">

**Comment by davikstone2** [comment]
Fixed in this pull request : https://github.com/SaitoTech/saito-lite-rust/pull/933

**Comment by karlsaito** [comment]
Issue has been fixed
