### ISSUE TITLE
Games disappearing in lobby after refreshing

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#937]
Might be related to #928 and #929

Games Tested and impacted:
- Poker (Staging and Prod)

All games are disappearing in the lobby after hitting refresh (most likely it takes a very long time to sync)

Step 1: Go to arcade lobby
Step 2: Make a game or check for existing open games by other players
Step 3: Hit refresh
Step 4: All games, including yours, disappear from lobby ( You will then have to create a new one, and vice versa)

Additional Problem: Players will then create new ones because their past games disappears. But for those who doesnt refresh, there will be multiple games on their lobby

Fig.1 - arcade lobby
![step 1](https://user-images.githubusercontent.com/107991527/185022293-e124e024-76ea-4651-b6ea-2226f86d9239.png)

Fig.2 - After hitting refresh
![step 2](https://user-images.githubusercontent.com/107991527/185022315-a92e83a4-ffeb-4f31-96dc-4aae72264c08.png)

**Comment by estapeluo** [comment]
Version:
Code Version: 4.269
Wallet Version: 4.269

**Comment by estapeluo** [comment]
Issue is present on staging site

**Comment by karlsaito** [comment]
Error Shown @f8daniel  in prod

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/96273856/185082381-d521c201-4397-4545-9e29-fc37ae7a5c85.png">

**Comment by estapeluo** [comment]
To expand the issue...
Only browsers watching/idling in the arcade can see the game invite, if you weren't present during game creation you can't see it.

**Comment by karlsaito** [comment]
@umairkhannn  take note of the last comment of arks

**Comment by karlsaito** [comment]
Issue has been fixed together with #928  #929

**Comment by karlsaito** [comment]
Issue is fixed in prod now.
