### ISSUE TITLE
Saito doesn't  load all tweets quickly when users visit the homepage and saito-loader in retrieval of tweets is broken

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#940]
Note:
1. Loading previous tweets is too slow  (shouldn't take 1-2 minutes) since it loads ALL tweets. See #926 - 3rd item for the improvement related for incremental loading, and David proposal below
2. Saito-loader should appear when tweets are being retrieved inside the red square tweets pane . it should appear once the user is directed to the homepage and should tell users the action e.g. retrieving tweets (Should have the saito logo as the icon not just red)
<img width="607" alt="image" src="https://user-images.githubusercontent.com/96273856/185035554-72e88590-cc2a-4ea7-98c4-b73b38359a16.png">

David proposal for first item:

1. modify the SQL command so that it filters out transactions that are LARGER than a certain amount
2. modify the SQL command so that it shows transactions that are parent-level first
4. sub-load to push the comments into the tweet stream

**Test Steps:**
1. User enters the homepage
2. No tweet shown, user is able to navigate around and click items
![image](https://user-images.githubusercontent.com/96273856/185027954-16ffe970-5213-472d-a544-90dd09e20214.png)
5. After 1-2 minutes, page shows the saito-loader with white background
![image](https://user-images.githubusercontent.com/96273856/185027945-adcc3966-9b0c-44fc-a9e3-0ed913a50909.png)
6. After a 5-10 seconds, page shows  Red Square Homepage with all the tweets
![image](https://user-images.githubusercontent.com/96273856/185027976-8598a71a-260f-4595-8b7e-24a1687ce6a8.png)

Expected user experience
1. User opens the homepage
2. Saito-loader appears should appear as loading tweets on the tweet pane
3. Tweet should only show the first 5 recent. and should the user want to further see old tweets, should use lazy loading content. See #926 - 3rd item

**Comment by estapeluo** [comment]
It took 1-2min to fully load/fetch the tweets at 3.7mbit download

**Comment by karlsaito** [comment]
working on the latest master, closing the issue
