### ISSUE TITLE
Calendar UI Issues

### ISSUE THREAD

**Issue by estapeluo** [SaitoTech/saito-lite-rust#941]
- [x] Redsquare is showing invalid calendar for August 2022, its shifted 2 days. Align the calendar dates

Steps:
1. Visit https://saito.io/redsquare/#home

Screenshot:
![image](https://user-images.githubusercontent.com/59634305/185035412-71941b9c-1772-440a-9776-c51a798e7088.png)

- [x] if Friday is the 19th, then Friday the 1st is Monday, and we only have 1 day from the previous month visible, and only 5 rows in the calendar, not 6.
- [x] the dates (1, 14, 29) should be left-aligned in the calendar boxes, and there should be a div in each date where we can insert an icon (if an event is scheduled). this icon will indicate to users that they have something scheduled.

**Comment by estapeluo** [comment]
Expected:
![image](https://user-images.githubusercontent.com/59634305/185035787-bc5c7142-e839-49c3-81e6-699abf09abda.png)

**Comment by karlsaito** [comment]
already part of the priority. @davikstone2 , please don't forget to assign to yourself

FYI @estapeluo

**Comment by davikstone2** [comment]
Please test after merge to staging

**Comment by estapeluo** [comment]
Production is fixed as per `Code Version: 4.283`
