### ISSUE TITLE
Arcade: Game invites URL doesn't work

### ISSUE THREAD

**Issue by estapeluo** [SaitoTech/saito-lite-rust#945]
Sharing the game invite URL (public or private) doesn't work

Steps:
1. User A Create a game invite (public or private)
2. User A copy/share the game invite URL link
3. User B joins

Video:

https://user-images.githubusercontent.com/59634305/185070532-86b2231f-00f8-48ca-aa4b-1a4609612172.mp4

Version:
Code Version: 4.269
Wallet Version: 4.269

**Comment by estapeluo** [comment]
Possible issues related to: https://github.com/SaitoTech/saito-lite-rust/issues/937

**Comment by karlsaito** [comment]
@estapeluo  please verify if it's fixed in prod

**Comment by estapeluo** [comment]
Working.
