### ISSUE TITLE
When user dumps multiple images at the same time, and uploads them, the images are scattered on the homepage, and some pictures uploaded are missing

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#953]
Test Step
1. Go to RS Homepage
2. Click Create New Tweet
3. Drag and Upload 2+ images at the same time
**4. Images are scaterred (ERROR 1):**
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/96273856/185287785-c691a553-ec16-487f-8688-b5dd4e0a2056.png">
5. Click Tweet
**6. The other image uploaded retains on the screen (ERROR 2):**
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/96273856/185287879-8aa7dae4-df39-44ff-9e74-872aae40ae26.png">
7. Click Load new tweet
**8. The other image is missing (ERROR 3):**
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/96273856/185287977-7c3c22e0-e9b1-4887-87e7-5cfc76053119.png">

**Comment by karlsaito** [comment]
@estapeluo  can you check if this is still happening in prod?

**Comment by estapeluo** [comment]
This work fine for small size imgs, just tried with 4 imgs under 500kb in total.
