### ISSUE TITLE
Red Square: Unable to Create New Tweet

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#961]
Clicking the "Create new tweet" button doesnt do anything. 
When refreshing, "Create new tweet" button is functioning while waiting for the page to load, Once the whole page has loaded, the "Create new tweet" button doesnt do anything again.

https://user-images.githubusercontent.com/107991527/185525357-0225d60c-680a-4585-98d4-06e61499d22a.mp4

**Comment by karlsaito** [comment]
@afkafk088  can you provide screenshot of the console? use F12

**Comment by afkafk088** [comment]
@karlsaito sure, kindly see attached

![1](https://user-images.githubusercontent.com/107991527/185544824-3ed9eebb-3710-4db6-b11f-000b3bc29dc2.png)
![2](https://user-images.githubusercontent.com/107991527/185544832-0efb13b2-723b-46d8-a041-1e17bea0af61.png)

**Comment by estapeluo** [comment]
This has been fixed in both staging and prod.
