### ISSUE TITLE
Leaderboards - incomplete games are being counted

### ISSUE THREAD

**Issue by trevelyan** [SaitoTech/saito-lite-rust#968]
I've had multiple games where errors or other issues (one player needing to leave) has resulted in a loss to whichever player simply closed the game first. This makes it difficult to care about the leaderboard status.

It would be better to simply count completed games towards the league ranking.

Without this issue being solved, people who care about their ranking will simply be unwilling to accept games from players that they don't know, and particularly new players who are more likely to run into problems. It is also always the more experienced player that has to deal with errors and gameplay issues, which means we're penalizing people who want to use Saito and will be more likely to stick around and get others into the rankings.

**Comment by f8daniel** [comment]
Source code changed to not count any games cancelled through the lobby, though trying to preserve the in-game Chess resignation as a loss.
