### ISSUE TITLE
Red Square: Unable to load images on tweet. Uploaded images appear as broken/corrupted

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#994]
I tested with different browsers, different wallets ,different image files

Fig.1: After attaching image on tweet/post
![pic1](https://user-images.githubusercontent.com/107991527/186301803-f58db333-69d1-47b0-9ff9-53699293c34a.png)

Fig.2: Clicking on the Image popup
![pic2](https://user-images.githubusercontent.com/107991527/186301826-4d7d1e29-61a1-4292-a036-9095652eed8c.png)

**Comment by estapeluo** [comment]
already fixed in prod
